### ISSUE TITLE
Safest way to determine if not temporary control plan is running

### ISSUE THREAD

**Issue by halacs** [kubernetes-incubator/bootkube#1014]
Hi,

I have an automated installer package what has bootkube as an underlying subsystem.

There is a short period, when the temporary control plain is down but the final API server is still not available: from kubectl point of view this is an outage on the API server what brakes my whole solution in some rare cases.

What is the most reliable solution to know final control plain is up and running not the temporary one anymore?

Thanks & br,
Halacs

**Comment by redbaron** [comment]
at bootkube just creates manifests it is told to create, you can add label/annotation to bootstrap control plane and wait for real control plane , which would be one without those labels.

another indirect way is to make use of the fact, that bootstrap control plane is run as a static pod, and therefore controllerRef is not the same (probably absent)
