### ISSUE TITLE
allow CA/cert expiration to be configurable

### ISSUE THREAD

**Issue by sym3tri** [kubernetes-incubator/bootkube#104]
And have a valid option (possibly default) to not expire at all.

This has been tripping users up and they've been getting locked out of their clusters (in kube-aws etc). Administrators that care about security should be able to rotate CA/Certs on their own after the cluster is up. We shouldn't make this expiry decision for them. This should be a config parameter when generating the CAs/Certs.

Some of the initial work is already done in:
https://github.com/coreos/pkg/blob/master/k8s-tlsutil/k8s-tlsutil.go
But the option to not expire needs to be added there.

**Comment by flowchartsman** [comment]
Happy to contribute if the project is short on time.

**Comment by flowchartsman** [comment]
I have a patch in upstream for this: https://github.com/coreos/pkg/pull/88 If it's accepted, I can issue a PR with updated vendored dependency and the rest of the changes. If it's not, this support can still be added, just with an explicit expiration of `time.Date(9999, 12, 31, 23, 59, 59, 0, time.UTC)` and maybe a check for a special "none" value of the provided expiration.

**Comment by HarithaRamesh** [comment]
Hi, any update on when this feature might get in?
