### ISSUE TITLE
Do you see files in `/etc/kubernetes/manifests` at all? there should be bootstrap control plane files created by bootkube.

### ISSUE THREAD

**Issue by lswadmin** [kubernetes-incubator/bootkube#1041]
apiVersion: v1
kind: Pod
metadata:
  name: bootstrap-kube-apiserver
  namespace: kube-system
spec:
Jun 02 10:08:58 c1.tectonicsandbox.com bash[11243]: [13278.269463] bootkube[5]: W0602 10:08:58.568072       5 create.go:31] Unable to determine api-server readiness:
Jun 02 10:09:03 c1.tectonicsandbox.com bash[11243]: [13283.267167] bootkube[5]: W0602 10:09:03.565738       5 create.go:31] Unable to determine api-server readiness:
Jun 02 10:09:08 c1.tectonicsandbox.com bash[11243]: [13288.267234] bootkube[5]: W0602 10:09:08.565842       5 create.go:31] Unable to determine api-server readiness:
Jun 02 10:09:13 c1.tectonicsandbox.com bash[11243]: [13293.268693] bootkube[5]: W0602 10:09:13.567241       5 create.go:31] Unable to determine api-server readiness:
Jun 02 10:09:18 c1.tectonicsandbox.com bash[11243]: [13298.268556] bootkube[5]: W0602 10:09:18.567101       5 create.go:31] Unable to determine api-server readiness:
Jun 02 10:09:23 c1.tectonicsandbox.com bash[11243]: [13303.267126] bootkube[5]: W0602 10:09:23.565713       5 create.go:31] Unable to determine api-server readiness:
Jun 02 10:09:28 c1.tectonicsandbox.com bash[11243]: [13308.268372] bootkube[5]: W0602 10:09:28.566912       5 create.go:31] Unable to determine api-server readiness:
lines 1-21/21 (END)
core@c1 /etc/kubernetes/manifests $ exit
logout
'cygwin': unknown terminal type.
Connection to 127.0.0.1 closed.

#!/bin/bashker-k8s-devops-master\chapter9\tectonic-sandbox-1.7.5-tectonic.1>kubectl -n kube-system get pods
Unable to connect to the server: dial tcp 172.17.4.101:443: connectex: No connection could be made because the target machine actively refused it.
# When self-hosted etcd is enabled, bootkube places an static pod manifest in
# /etc/kubernetes/manifests for Kubelet to boot a temporary etcd instance.1>vagrant ssh c1
# However, Kubelet might not have started yet and therefore the folder might
# be missing for now, making bootkube crash.
mkdir -p /etc/kubernetes/manifests/
core@c1 ~ $ systemctl status bootkube
# Move optional experimental manifests into bootkube friendly locations
[ -d /opt/tectonic/experimental ] && mv /opt/tectonic/experimental/* /opt/tectonic/manifests/ && rm -r /opt/tectonic/experimental
[ -d /opt/tectonic/bootstrap-experimental ] && mv /opt/tectonic/bootstrap-experimental/* /opt/tectonic/bootstrap-manifests/ && rm -r /opt/tectonic/bootstrap-experimentalctive: activating (start) since Sun 2019-06-02 10:07:53 UTC; 4min 50
s ago
# Move network related manifests into bootkube friendly locations
~ -d /opt/tectonic/net-manifests ] && mv /opt/tectonic/net-manifests/* /opt/tectonic/manifests/ && rm -r /opt/tectonic/net-manifests
~  Memory: 1.6M
~ shellcheck disable=SC2154
~usr/bin/rkt run \.slice/bootkube.service
~ --trust-keys-from-https \in/bash /opt/tectonic/bootkube.sh
~ --volume assets,kind=host,source="$(pwd)" \-linux-x86-64.so.2 stage1/rootfs/usr/bin/systemd-nspawn --boot --notify-ready=yes -Zsystem_u:system_r:svirt_lxc_net_t:s0~ --mount volume=assets,target=/assets \
apiVersion: v1-kubernetes,kind=host,source=/etc/kubernetes \
kind: Podn: v1me=etc-kubernetes,target=/etc/kubernetes \58.267339] bootkube[5]: W0602 10:11:58.565900       5 create.go:31] Unable to determine api-server readiness:kind: Podo/coreos/bootkube:v0.6.2" \
metadata:ost \3 c1.tectonicsandbox.com bash[11243]: [13463.269680] bootkube[5]: W0602 10:12:03.568257       5 create.go:31] Unable to determine api-server readiness:  name: bootstrap-kube-apiserver
  name: bootstrap-kube-apiserverset-dir=/assets43]: [13468.269210] bootkube[5]: W0602 10:12:08.567752       5 create.go:31] Unable to determine api-server readiness:spec:
  namespace: kube-systemnicsandbox.com bash[11243]: [13473.267260] bootkube[5]: W0602 10:12:13.565837       5 create.go:31] Unable to determine api-server readiness:  - name: kube-apiserver
spec:mage: quay.io/coreos/hyperkube:v1.7.5_coreos.1 [13478.267074] bootkube[5]: W0602 10:12:18.565648       5 create.go:31] Unable to determine api-server readiness:    command:
  containers:n/flockectonicsandbox.com bash[11243]: [13483.268620] bootkube[5]: W0602 10:12:23.566907       5 create.go:31] Unable to determine api-server readiness:    - /var/lock/api-server.lock
apiVersion: v1
kind: Pod
metadata:
  name: bootstrap-kube-apiserver
  namespace: kube-system
spec:
  - name: kube-apiservernicsandbox.com bash[11243]: [13488.266120] bootkube[5]: W0602 10:12:28.564697       5 create.go:31] Unable to determine api-server readiness:    - apiserver
    image: quay.io/coreos/hyperkube:v1.7.5_coreos.1anger,ServiceAccount,DefaultStorageClass,ResourceQuota   5 create.go:31] Unable to determine api-server readiness:    - --allow-privileged=true
    command:orization-mode=RBACbox.com bash[11243]: [13498.267525] bootkube[5]: W0602 10:12:38.566066       5 create.go:31] Unable to determine api-server readiness:    - --bind-address=0.0.0.0
    - /usr/bin/flockle=/etc/kubernetes/secrets/ca.crt13503.268393] bootkube[5]: W0602 10:12:43.566934       5 create.go:31] Unable to determine api-server readiness:    - --cloud-provider=
    - /var/lock/api-server.lockgiven
    - /hyperkubevers=https://172.17.4.101:2379
    - apiserverorum-read=trueic/bootkube.sh
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
    - --allow-privileged=truebernetes/secrets/etcd-client.crt
    - --authorization-mode=RBACnetes/secrets/etcd-client.key
    - --bind-address=0.0.0.0

    - --etcd-keyfile=/etc/kubernetes/secrets/etcd-client.keyaml
    - --insecure-port=0etc/kubernetes/secrets/apiserver.crt
    - --advertise-address=172.17.4.101rnetes/secrets/apiserver.key
    - --kubelet-client-certificate=/etc/kubernetes/secrets/apiserver.crt
    - --kubelet-client-key=/etc/kubernetes/secrets/apiserver.key
    - --secure-port=443ost
    - --service-account-key-file=/etc/kubernetes/secrets/service-account.pub
    - --service-cluster-ip-range=10.3.0.0/16
    - --storage-backend=etcd3
    - --tls-ca-file=/etc/kubernetes/secrets/ca.crtrap-apiserver.yaml
    - --tls-cert-file=/etc/kubernetes/secrets/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/secrets/apiserver.key
    volumeMounts:rueAvailable builtin terminals are:
    - mountPath: /etc/ssl/certs
    buname: ssl-certs-host
    bureadOnly: truee
    - mountPath: /etc/kubernetes/secrets
    luname: secrets'
"bootsreadOnly: true.yaml" 68L, 2166C
    - mountPath: /etc/kubernetes/cloud
      name: etc-kubernetes-cloud
      readOnly: true
    - mountPath: /var/lock
      name: var-lock
      readOnly: false
  hostNetwork: true
  volumes:
  - name: secrets
    hostPath:
      path: /etc/kubernetes/bootstrap-secrets
  - name: etc-kubernetes-cloud
    hostPath:
      path: /etc/kubernetes/cloud
  - name: ssl-certs-host
    hostPath:
      path: /usr/share/ca-certificates
  - name: var-lock

    hostPath:
      path: /var/lock
  updateStrategy:
    rollingUpdate:
    maxUnavailable: 1
    type: RollingUpdate

**Comment by rmenn** [comment]
could you clone the repo and try `make run-multi`, please reopen if you feel this is still an issue
