### ISSUE TITLE
Support check pointing configmaps

### ISSUE THREAD

**Issue by ericchiang** [kubernetes-incubator/bootkube#124]
Chatted with @derekparker about this.

Currently bootkube checkpoints secrets for the bootstrapped API server. This lets the API server refer to secrets in it's manifest (e.g. for TLS assets, config flags, etc). It doesn't support configmaps, which might be more appropriate for non-secret configuration. In my case, this would be a policy file.

**Comment by dhawal55** [comment]
Any update on this? If no one is working on this, I would like to take it and submit a PR.
