### ISSUE TITLE
checkpointer can't find checkpointed apiserver manifest

### ISSUE THREAD

**Issue by ericchiang** [kubernetes-incubator/bootkube#135]
I'm seeing some issues with running bootkube using the coreos-baremetal instructions. bootkube runs and reports that it's working, but the API server is never actually available. The bootstrapped API server fails with something like

```
I0916 17:54:22.088920       1 genericapiserver.go:690] Serving securely on 0.0.0.0:443
I0916 17:54:22.089037       1 genericapiserver.go:735] Serving insecurely on 127.0.0.1:8080
E0916 17:54:22.089963       1 genericapiserver.go:716] Unable to listen for secure (listen tcp 0.0.0.0:443: bind: address already in use); will try again.
```

(but then exits despite promising to try again)

While the checkpointer complains when it gets brought back up that it can't find a checkpointed manifest

```
I0916 18:18:23.712503       1 main.go:52] begin apiserver checkpointing...
I0916 18:18:24.048986       1 main.go:83] no apiserver running, installing temp apiserver static manifest
E0916 18:18:24.049506       1 main.go:86] open /srv/kubernetes/manifests/apiserver.json: no such file or directory
I0916 18:19:24.052212       1 main.go:83] no apiserver running, installing temp apiserver static manifest
E0916 18:19:24.052395       1 main.go:86] open /srv/kubernetes/manifests/apiserver.json: no such file or directory
I0916 18:20:24.055698       1 main.go:83] no apiserver running, installing temp apiserver static manifest
E0916 18:20:24.055852       1 main.go:86] open /srv/kubernetes/manifests/apiserver.json: no such file or directory
I0916 18:21:24.057407       1 main.go:83] no apiserver running, installing temp apiserver static manifest
E0916 18:21:24.057584       1 main.go:86] open /srv/kubernetes/manifests/apiserver.json: no such file or directory
```

Is there some ordering in which these components would be expected to get to this state? E.g. is there something that could fail during an install then cause it? I've been seeing this several times today and yesterday and am trying to figure out if there's something I'm doing wrong.

This is with both bootkube master, and bootkube referring to `quay.io/peanutbutter/hyperkube:v1.3.7_eric.0` which was built from https://github.com/coreos/kubernetes/pull/76

cc @derekparker @aaronlevy

**Comment by aaronlevy** [comment]
What likely happened is that the api-server isn't running long enough to be checkpointed. @ericchiang can you increase the logging verbosity of the api-server so we can see why it's failing?

unable to bind log message likely just happens to be the last log message before the pod exits (but we should see more info with higher verbosity

**Comment by ericchiang** [comment]
@aaronlevy Thanks for the follow up. Will do.

**Comment by aaronlevy** [comment]
The checkpointer has gone through a full rewrite. Going to close this for now, but please let me know if it should be reopened.
