### ISSUE TITLE
Another service could win race for dns service IP allocation

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#136]
We need a pre-assigned service IP for the kubernetes dns service - but it's possible when creating all assets (equivalent of `kubectl create -f cluster/manifests`) that another service is randomly assigned this ip (defaults to 10.3.0.10).

One option would just to force the kube-dns service to be created first - but this seems less than ideal.

**Comment by kenan435** [comment]
@aaronlevy Beside prioritizing asset creation order we could prefix asset file names which IMHO is not a good approach. Anyways I made a pq using the former approach. Let me know what you think.

**Comment by aaronlevy** [comment]
I'm not sure that we need to solve this right away (or potentially in bootkube at all). It is an edge case at the moment, and won't affect bootkube itself right now because kube-dns is the only service we create.

However, a bootkube user was populating the `cluster/manifests` directory with more addons/services, which meant they were all being created at the same time (and one happened to be randomly assigned the dns service IP).

The asset naming scheme is not a bad idea either - this is a systemd convention for managing drop-in units (e.g. 01-foo.conf, 02-foo.conf).

I think it might be an option to solve this upstream as well where maybe we inform the controller-manager of a range which will be statically assigned.

For example:

```
--service-cluster-ip-range=10.3.0.0/24
--service-cluster-ip-range-static=10.3.0.0/28
```

I'll open an upstream issue to discuss the above option.

**Comment by dghubble** [comment]
We have another way to add our addons so this probably isn't pressing. A simpler solution might be for bootkube to used reserved `cluster/system` for itself and `cluster/manifest` for deployer additions. Just to separate manifests bootkube offers guarantees about, from free-form deployer additions.
