### ISSUE TITLE
scheduler + controller-manager should use pod-anti-affinity

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#166]
We are going to install with replicas>1 -- but we want these pods to end up on different nodes (it's for spreading risk of node failure -- not for throughput).

We should add pod-anti-affinity so the scheduler won't add multiple pods to same node during initial bootstrap.

**Comment by aaronlevy** [comment]
The consensus was to wait until v1.6 when these apis stabilize: https://groups.google.com/d/msg/kubernetes-dev/-fwfHQtm9GE/H1TU4yqiBAAJ

/cc @squat @Quentin-M

**Comment by squat** [comment]
@aaronlevy sounds good. I'll submit a new PR when 1.6 is out

**Comment by coresolve** [comment]
💯 How would anti-affinity work if it can't solve the constraint? For example I have a node selector that requires the label master. With anti-affinity if I only have one node labeled 'master' and a replica count of 2. Would I get one pod or would they both be created on the only node labeled 'master'?

**Comment by aaronlevy** [comment]
You can select hard or soft restrictions (last I looked). So you could give a soft restriction that *attempts* to spread the pods, but will co-locate otherwise. Or a hard restriction where it just will remain unscheduled until the scheduling criteria can be satisfied

**Comment by squat** [comment]
@coresolve the adjectives "preferred" and "required" are used in the affinity annotations to specify soft and hard requirements respectively.

**Comment by Quentin-M** [comment]
https://github.com/coreos-inc/tectonic/blob/master/docs-internal/workloads-separation.md

**Comment by Quentin-M** [comment]
@coresolve I suggest you take a look at the related internal documentation on Tectonic.

**Comment by coresolve** [comment]
Thanks!

**Comment by aaronlevy** [comment]
closed in: https://github.com/kubernetes-incubator/bootkube/pull/421
