### ISSUE TITLE
Developing self hosted etcd as a feature flag

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes-incubator/bootkube#174]
We have a working prototype of self hosted etcd.

For the next step, we need to standardize a few things about workflow. The end goal is that we will have self hosted etcd as a feature flag in bootkube.

Here's a list of items I can think of:
- We want to have a feature branch before merging to master. Let's reserve "**etcd**" branch for this purpose. It will be tracked on master regularly.
- All code changes will be submitted as PRs against "etcd" branch. We will have regular review workflow and git history.

Feel free to add more items or comment on it!

**Comment by hongchaodeng** [comment]
@xiang90 @aaronlevy

**Comment by xiang90** [comment]
@hongchaodeng @aaronlevy If it is a feature flag, why not just merge into master? How long do we expect to get this done? days? weeks or months?

**Comment by dghubble** [comment]
In bootkube, this needs to be a feature flag until we're confident in running Kubernetes and production Tectonic clusters this way. If future bootkube were to require self-hosted etcd, that leaves our products without a stable way forward.

**Comment by dghubble** [comment]
The bootkube package is consumed by products which create production clusters which must work reliably. Feature flags allow prototypes to be tried as an opt-in, until they're stable enough to become the default in every bootkube release (master is cut into a release when Kubernetes is bumped).

**Comment by xiang90** [comment]
@dghubble I do not understand your reply. My questions was if we have a feature flag, why not merge this into master. I do not want to make the feature flag to be the default setting.

**Comment by dghubble** [comment]
:+1:

**Comment by hongchaodeng** [comment]
We need to rethink about the process and who to work on this.
Closing this now.
