### ISSUE TITLE
Using static Pod manifests instead of Golang for bootstrapping the control plane

### ISSUE THREAD

**Issue by luxas** [kubernetes-incubator/bootkube#208]
Hi,

When will you switch over to using static pod manifests for bootstrapping the control plane instead of vendoring the components into bootkube?
I hope we can do that pretty soon, because we're looking into kubeadm doing the same thing soon...

cc @aaronlevy When will you do this?

**Comment by aaronlevy** [comment]
@luxas I'm going to close this as dupe of https://github.com/kubernetes-incubator/bootkube/issues/168

Unfortunately, I probably won't be able to work on this until after the new year.

**Comment by luxas** [comment]
Oops, didn't see that issue :)
Thanks
