### ISSUE TITLE
GC kubelet rkt images

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#218]
Restarting the kubelet (via kubelet-wrapper) will create a new container filesystem. Eventually this could fill the disk. We should remove the rkt containers when systemd unit exits.

See change here to resolve same issue: https://github.com/coreos/coreos-kubernetes/commit/ea3bd80f9cc380df67b7c20033b44f1f7c79d5a0

**Comment by bassam** [comment]
Also #251 highlights this GC issue. My disk fills up quickly after a pivot. Can we check the lock before running the rkt container in a wrapper script?

I wonder if the "on-host" kubelet need to be quiesced or even masked after pivot. Or is the concern that if the self-hosted kubelet dies you still need the on-host kubelet to be started?
