### ISSUE TITLE
use upstream labels for member roles

### ISSUE THREAD

**Issue by philips** [kubernetes-incubator/bootkube#246]
`kubernetes.io/role=master` and `kubernetes.io/role=node`.

https://github.com/kubernetes/kubernetes/pull/35975/files#diff-c8063ac1e636c387ca8169633ddee1bdR54

**Comment by philips** [comment]
cc @sym3tri

**Comment by philips** [comment]
Actually, I found an issue with this: https://github.com/kubernetes/kubernetes/pull/39112

**Comment by aaronlevy** [comment]
closed in https://github.com/kubernetes-incubator/bootkube/pull/436
