### ISSUE TITLE
cluster fails to bootstrap due to self-hosted flannel

### ISSUE THREAD

**Issue by bassam** [kubernetes-incubator/bootkube#258]
My multi-node vagrant cluster is failing to come up with the latest bits from master including self-hosted flannel. If I wait long enough bootkube times out (10 mins ) and a few minutes after that the self-hosted api server eventually comes up:

```
> kubectl --kubeconfig=cluster/auth/kubeconfig get pods --all-namespaces
NAMESPACE     NAME                                       READY     STATUS              RESTARTS   AGE
kube-system   checkpoint-installer-98c7p                 1/1       Running             0          40m
kube-system   kube-apiserver-5h7bt                       1/1       Running             7          40m
kube-system   kube-controller-manager-3438979800-0v6w2   0/1       ContainerCreating   0          42m
kube-system   kube-controller-manager-3438979800-4lb31   0/1       ContainerCreating   0          42m
kube-system   kube-dns-4101612645-014zb                  0/4       ContainerCreating   0          42m
kube-system   kube-flannel-htjh0                         2/2       Running             1          40m
kube-system   kube-flannel-jthx5                         2/2       Running             0          40m
kube-system   kube-proxy-gm67t                           1/1       Running             0          40m
kube-system   kube-proxy-kdcz6                           1/1       Running             0          40m
kube-system   kube-scheduler-694795526-9mlvn             0/1       ContainerCreating   0          42m
kube-system   kube-scheduler-694795526-ls7bq             0/1       ContainerCreating   0          42m
kube-system   pod-checkpointer-172.17.4.101              1/1       Running             0          38m
```

but none of the pods that require CNI (flannel) ever come up.  The flannel pod is failing due to:

```
core@c1 ~ $ docker logs 6d9ea6e93fb7
I0104 05:12:21.968019       1 kube.go:109] Waiting 10m0s for node controller to sync
I0104 05:12:21.968096       1 kube.go:289] starting kube subnet manager
I0104 05:12:22.975642       1 kube.go:116] Node controller sync successful
I0104 05:12:22.975676       1 main.go:132] Installing signal handlers
I0104 05:12:22.975769       1 manager.go:124] Searching for interface using 172.17.4.101
I0104 05:12:22.977301       1 manager.go:149] Using interface with name eth1 and address 172.17.4.101
I0104 05:12:22.977320       1 manager.go:166] Defaulting external address to interface address (172.17.4.101)
E0104 05:12:23.005003       1 network.go:102] failed to register network: failed to acquire lease: node "172.17.4.101" pod cidr not assigned
E0104 05:12:24.005353       1 network.go:102] failed to register network: failed to acquire lease: node "172.17.4.101" pod cidr not assigned
E0104 05:12:25.005695       1 network.go:102] failed to register network: failed to acquire lease: node "172.17.4.101" pod cidr not assigned
```

and the controller-manager pods are not coming up at all:

```
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  39m		38m		8	{default-scheduler }			Warning		FailedScheduling	no nodes available to schedule pods
  37m		37m		1	{default-scheduler }			Normal		Scheduled		Successfully assigned kube-controller-manager-3438979800-4lb31 to 172.17.4.101
  37m		35m		68	{kubelet 172.17.4.101}			Warning		FailedSync		Error syncing pod, skipping: failed to "SetupNetwork" for "kube-controller-manager-3438979800-4lb31_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-controller-manager-3438979800-4lb31_kube-system(cd49b204-d23b-11e6-bbef-001c42bb320c)\" using network plugins \"cni\": cni config unintialized; Skipping pod"

  29m	25m	10	{kubelet 172.17.4.101}		Warning	FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/secret/cd49b204-d23b-11e6-bbef-001c42bb320c-secrets" (spec.Name: "secrets") pod "cd49b204-d23b-11e6-bbef-001c42bb320c" (UID: "cd49b204-d23b-11e6-bbef-001c42bb320c") with: Get https://172.17.4.101:443/api/v1/namespaces/kube-system/secrets/kube-controller-manager: dial tcp 172.17.4.101:443: getsockopt: connection refused
  29m	25m	10	{kubelet 172.17.4.101}		Warning	FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/secret/cd49b204-d23b-11e6-bbef-001c42bb320c-default-token-2pwks" (spec.Name: "default-token-2pwks") pod "cd49b204-d23b-11e6-bbef-001c42bb320c" (UID: "cd49b204-d23b-11e6-bbef-001c42bb320c") with: Get https://172.17.4.101:443/api/v1/namespaces/kube-system/secrets/default-token-2pwks: dial tcp 172.17.4.101:443: getsockopt: connection refused
  35m	1s	1892	{kubelet 172.17.4.101}		Warning	FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "kube-controller-manager-3438979800-4lb31_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-controller-manager-3438979800-4lb31_kube-system(cd49b204-d23b-11e6-bbef-001c42bb320c)\" using network plugins \"cni\": open /run/flannel/subnet.env: no such file or directory; Skipping pod"
```

This feels like a race -- the controller-manager is needed to setup the podCIDR and it can't come up due to flannel not finding podCIDR. Does this sound reasonable?

/cc @aaronlevy

**Comment by bassam** [comment]
If I change the self-hosted controller manager to use the host network, the cluster comes up for me. I wonder why the bootstrap controller manager did not set the node PodCIDR correctly.

**Comment by aaronlevy** [comment]
@bassam An interesting piece in that log is: 

> failed to "SetupNetwork" for "kube-controller-manager-3438979800-4lb31_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-controller-manager-3438979800-4lb31_kube-system(cd49b204-d23b-11e6-bbef-001c42bb320c)\" using network plugins \"cni\": cni config unintialized; Skipping pod

The coordination point for "a pod network has been deployed" is that a CNI configuration file exists (default: /etc/cni/net.d). So the kubelet will try and start any hostNetwork pods, but then skip podNetwork pods until valid CNI configuration is in place -- (and why we see the skip here).

The flannel daemonset/pod should be copying the CNI configuration into place (in a slightly different location described below) -- so it would seem from those logs that the file is missing (but both containers in kube-flannel pod seem to be running based on your output above).

There are a couple assumptions we have here, like that `/etc/kubernetes` on the host is properly mounted through to the kube-flannel pod (so that any file placed under that directory, will survive both the kubelet being restarted, and flannel pod being restarted).

On the kubelet side, we rely on the kubelet-wrapper to mount this from the host to the rkt-run kubelet: https://github.com/coreos/coreos-overlay/blob/master/app-admin/kubelet-wrapper/files/kubelet-wrapper#L65

Then in the kube-flannel pod, the CNI sub-directory should also be a volume mount: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L604-L606
Which is then exposed to the pod as /etc/cni/net.d (default search path): https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L588-L589

A hunch is that the CNI configuration file is not being copied / exposed properly and the kubelet will never start pods which require the podNetwork to be configured.

As a first step, can you check `/etc/kubernetes/cni/net.d` and see if any file has been created there?

**Comment by bassam** [comment]
here's whats in the that directory:

```
core@c1 ~ $ ls -hal /etc/kubernetes/cni/net.d/
total 24K
drwxr-xr-x. 2 root root 4.0K Jan  4 18:17 .
drwxr-xr-x. 3 root root 4.0K Jan  4 18:14 ..
-rw-r--r--. 1 root root   92 Jan  4 18:17 10-flannel.conf
core@c1 ~ $ cat /etc/kubernetes/cni/net.d/10-flannel.conf 
{
  "name": "cbr0",
  "type": "flannel",
  "delegate": {
    "isDefaultGateway": true
  }
}
```

I'm still suspecting the controller manager podCIDR issue. It does not seem that the bootstrap controller-manager is creating the podCIDR settings on the node:

```> kubectl --kubeconfig=cluster/auth/kubeconfig describe nodes | grep -i PodCIDR
```

and until the self-hosted controller manager is not running due to CNI not working. I also noticed that the bootstrap controller-manager complains about CIDR parsing:

```
I0104 18:14:39.394206    1463 plugins.go:94] No cloud provider specified.
W0104 18:14:39.394341    1463 controllermanager.go:285] Unsuccessful parsing of cluster CIDR : invalid CIDR address: 
W0104 18:14:39.394929    1463 controllermanager.go:289] Unsuccessful parsing of service CIDR : invalid CIDR address: 
```

could this be a flag parsing issue here https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/bootkube/bootkube.go#L60?

**Comment by aaronlevy** [comment]
That is bizarre - and just to confirm this is being built off master with no changes? I'll try and re-build from master and check myself in a few minutes.

**Comment by bassam** [comment]
yes from master no changes.

**Comment by bassam** [comment]
I did a`make clean` and somehow this all cleared up. I think I had a stale bootkube in my _output dir. Sorry for the false alarm.
