### ISSUE TITLE
self hosted etcd: remove boot etcd manifest after migration

### ISSUE THREAD

**Issue by xiang90** [kubernetes-incubator/bootkube#283]
We create the boot etcd static pod manifest for creating the initial out-cluster etcd. After we successfully migrate etcd into Kubernetes cluster, we should remove that static manifest. 

Or the kubelet will try to start the boot etcd again when it restarts (even if the restart policy is Never).

One thing I do not understand is that the boot etcd will be started as expected by Kubelet after a reboot, but it is always pending.

**Comment by hongchaodeng** [comment]
It doesn't need to wait after migration.
We can just remove it once kubelet starts boot etcd.

**Comment by xiang90** [comment]
@hongchaodeng sure. we just need to remove it at some point. after migration seems a good point.

**Comment by xiang90** [comment]
@hongchaodeng Can you fix this?
