### ISSUE TITLE
Possibly deploy checkpointer to all nodes.

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#288]
Now that we allow checkpointing of arbitrary pods, we might want to deploy this on more than just master nodes.

One use-case is self-hosted etcd pods - we need to checkpoint these, but right now they can end up on any node.

/cc @xiang90

**Comment by rphillips** [comment]
Since the checkpointer is watching kube-system only, should we close this issue?

**Comment by ericchiang** [comment]
works for me.
