### ISSUE TITLE
Worker Node behind NAT gateway (external IP handling)

### ISSUE THREAD

**Issue by InAnimaTe** [kubernetes-incubator/bootkube#292]
Decided to open an issue here to track and help solve this use-case/problem. I have another issue around this on the tectonic forum [here](https://github.com/coreos/tectonic-forum/issues/41).

I'm doing an interesting deployment of Tectonic whereas I have a controller node in the cloud and a worker node at home, behind NAT (all incoming traffic passed directly to it though). As you can see below, I already know there needs to be configuration passed to flannel for this to work properly. The problem lies in that passing that configuration is much harder with the new way flannel is deployed (`kube-flannel` daemonset other than local `flanneld`). I hope we can solve this and help others who might have deployments in which they need this scenario to work.

### Tectonic Version 

1.5.2-tectonic.1

### Environment

* 1x Controller Node is VPS with public IPv4 Address (Vultr allows for iPXE endpoints)
* 1x Worker Node (bare-metal) behind NAT address (so interface has internal IP but has to be accessed via external public IP)

### Current Status

My cluster is 3/4 of the way created; Hanging at `Waiting for Kubernetes components.` via a `journalctl`
Presumably, this is because flannel is having a heart attack over the worker node IP.

Pre-1.5, you just needed something like:

```
$ cat /etc/systemd/system/flanneld.service.d/10-custom.conf  
[Service]
Environment="FLANNELD_PUBLIC_IP=1.2.3.4"
```
Now, it seems flannel is running as a DaemonSet, which makes configuring it a bit harder.

I took a look at its yaml config and see that it takes some configuration from (on the host) `/etc/kubernetes/cni/net.d`, but that config seems to be specific to what it provides, not core configuration like `--public-ip`:

```
worker net.d # cat 10-flannel.conf
{
  "name": "cbr0",
  "type": "flannel",
  "delegate": {
    "isDefaultGateway": true
  }
}
```

### The best way to approach this?

At the moment, I'm currently trying to modify the pod deployment yaml with the appropriate variable/config to specify the public IP. This is really gross and only having a couple weeks of k8s under my belt, a bit challenging. I'm really looking to the community here for some guidance on the best way to achieve this. Is there some config file on the host I could be using? Is there a way I can setup the configset differently? Should I have done something different at deploy time?

**Comment by InAnimaTe** [comment]
Since I can't actually apply pod level configuration for a particular pod deployed once that daemonset starts it, I have no way of modifying this option specifically for this one host. 

At this point, I really don't have a clue how I'd do this then, without ripping out the daemonset and recreating kube-flannel manually as pods, which is obviously not gonna fly.

Really could use some insight here.

**Comment by InAnimaTe** [comment]
![screenshot from 2017-02-02 18-22-28](https://cloud.githubusercontent.com/assets/1192726/22573230/001b4f16-e976-11e6-82c5-e2440e169db9.png)

Presently the screen I'm looking at.

**Comment by coresolve** [comment]
Take a look at kubectl get node -o yaml The public ip is specified in the annotations of the node.

**Comment by coresolve** [comment]
$ kubectl get node -o json | jq .items[].metadata.annotations
{
  "flannel.alpha.coreos.com/backend-data": "{\"VtepMAC\":\"7e:27:6b:7c:55:44\"}",
  "flannel.alpha.coreos.com/backend-type": "vxlan",
  "flannel.alpha.coreos.com/kube-subnet-manager": "true",
  "flannel.alpha.coreos.com/public-ip": "10.0.0.50",
  "node-agent.v1.coreos.com/current-kubelet-image": "quay.io/coreos/hyperkube:v1.5.2_coreos.1",
  "volumes.kubernetes.io/controller-managed-attach-detach": "true"
}
{
  "flannel.alpha.coreos.com/backend-data": "{\"VtepMAC\":\"2e:4b:35:2d:f4:2a\"}",
  "flannel.alpha.coreos.com/backend-type": "vxlan",
  "flannel.alpha.coreos.com/kube-subnet-manager": "true",
  "flannel.alpha.coreos.com/public-ip": "10.0.53.59",
  "node-agent.v1.coreos.com/current-kubelet-image": "quay.io/coreos/hyperkube:v1.5.2_coreos.1",
  "volumes.kubernetes.io/controller-managed-attach-detach": "true"
}
{
  "flannel.alpha.coreos.com/backend-data": "{\"VtepMAC\":\"c6:2b:c7:0f:01:cb\"}",
  "flannel.alpha.coreos.com/backend-type": "vxlan",
  "flannel.alpha.coreos.com/kube-subnet-manager": "true",
  "flannel.alpha.coreos.com/public-ip": "10.0.93.144",
  "node-agent.v1.coreos.com/current-kubelet-image": "quay.io/coreos/hyperkube:v1.5.2_coreos.1",
  "volumes.kubernetes.io/controller-managed-attach-detach": "true"

**Comment by InAnimaTe** [comment]
Yeah this was actually just answered earlier today in the other thread I have on the tectonic forum [here](https://github.com/coreos/tectonic-forum/issues/41)

Kind of frustrating that this isn't more well documented somewhere. Hopefully in the future, it's a bit more clear how setting this up might work ;)
