### ISSUE TITLE
api-server: stop listening with insecure port

### ISSUE THREAD

**Issue by philips** [kubernetes-incubator/bootkube#324]
As discussed we should stop doing this with the API as we don't use it anymore.

cc @aaronlevy

**Comment by aaronlevy** [comment]
I don't believe we use the insecure port anymore, so this might just be a matter of removing flag / testing installation (but I could be wrong, and there is some lingering bootstrap use).

**Comment by jamiehannaford** [comment]
I'd like to grab this if that's okay. Just to confirm, this is to disable both the boot cluster's use of the insecure port and the real api-server, right?

Relevant lines:

https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/bootkube/bootkube.go#L91
https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L160

**Comment by aaronlevy** [comment]
I know that the temporary control-plane does use the insecure port (e.g. for scheduler/controller-manager, self-hosted etcd, etc). I would think disabling this would be of lower-priority as it is only used once during bootstrap on a single node. It could work, but it will definitely require more changes than just changing the flag - and I don't think of this as much of a concern.

RE: Changes to the real api-server: I just want to note that this change would likely affect other installation tools that use bootkube. @ericchiang @dghubble -- any thoughts / concerns here?

**Comment by ericchiang** [comment]
@aaronlevy yeah this would impact us but it wouldn't be too hard to work around this and is probably something we shouldn't be relying on.

**Comment by dghubble** [comment]
If we're relying on this, I'm not aware of it. We can try it out.

**Comment by aaronlevy** [comment]
@jamiehannaford If you're interested in taking a look at this, I'd be happy to review / be available for any questions. It is somewhat of an "unknown" if this will be more difficult than we thought (so maybe the low-hanging fruit label is a bit off) - but if you're interested in at least taking a look - that would be great.

**Comment by bzub** [comment]
Could you change the default secure port to something like 6443, while you're at it? Admins of smaller clusters might have better uses for 443. `kubeconfig`s can be updated to use a nonstandard https port.

**Comment by ericchiang** [comment]
@bzub sounds like a separate issue.

**Comment by aaronlevy** [comment]
@bzub see https://github.com/kubernetes-incubator/bootkube/issues/354 for discussion on that topic

**Comment by aaronlevy** [comment]
I used @jamiehannaford PR but with some minor updates here: https://github.com/kubernetes-incubator/bootkube/pull/443

However I'm still running into ownership issues (discussed inline of that PR)

**Comment by aaronlevy** [comment]
Woops my comment above was meant for a different PR
