### ISSUE TITLE
When self-hosting etcd - we should set --etcd-servers based on service-cidr

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#329]
Opened from: https://github.com/kubernetes-incubator/bootkube/pull/318#issuecomment-282104244

**Comment by aaronlevy** [comment]
For clarity: if you select a custom `--service-cidr` - the deployer would also have to know that they need to set `--etcd-servers` to the service CIDR base ip + 15  (e.g. 10.3.0.0/24 -> 10.3.0.15).

Deployer shouldn't need to know this - and likely will cause people problems - so if we are self-hosting etcd, just pick the correct ip from the service cidr and override the `--etcd-servers` flag.

**Comment by lblackstone** [comment]
I'll take a crack at this one.

**Comment by aaronlevy** [comment]
@lblackstone that would be great, thank you!
