### ISSUE TITLE
checkpoint/recovery iptables for self hosted etcd deployement

### ISSUE THREAD

**Issue by xiang90** [kubernetes-incubator/bootkube#335]
We wrote a small tool (kenc) that can checkpoint/recovery iptables to/from a given file.

It can help self hosted etcd Kubernetes deployment to recover from a full API components down case.

I propose to have the kenc running as recovery mode as an init container. Then add the kenc running in checkpointing mode into the API server pod.

@aaronlevy opinion?

**Comment by aaronlevy** [comment]
I believe this is a duplicate of https://github.com/kubernetes-incubator/bootkube/issues/284 -- can we keep discussion there / in one place?

**Comment by xiang90** [comment]
closing.
