### ISSUE TITLE
Support easily launching self-hosted etcd clusters with all hack/* examples

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#337]
self-hosted etcd clusters are only easily launched via the `hack/multi-node` example. We should expand this support into all `hack/*` examples. This will also allow the GCE based conformance tests to exercise self-hosted etcd installations.

/cc @xiang90 @hongchaodeng

**Comment by hongchaodeng** [comment]
From user perspective, what are the steps to bootstrap a bootkube with self-hosted etcd cluster?

**Comment by aaronlevy** [comment]
@hongchaodeng I'm not super clear on what you mean.

Currently the only way to "easily" launch is via the multi-node vagrant installation, via `SELF_HOST_ETCD=true ./bootkube-up`.

Ideally all examples provide a simple way to launch a cluster (optionally) using self-hosted etcd. Since all of the examples are using bash - my assumption would be that we could gate this on an env var. 

Does that answer your question?

**Comment by hongchaodeng** [comment]
So I was wondering what's your thought to bootstrap SHE cluster in `hack/*` examples. Is it the same as passing `SELF_HOST_ETCD=true`?

**Comment by aaronlevy** [comment]
That would seem reasonable. For the quickstart examples, it would just mean adding that env var to: https://github.com/kubernetes-incubator/bootkube/blob/master/hack/quickstart/init-master.sh and then gating the etcd configuration based on the value.

**Comment by aaronlevy** [comment]
This is being added for the quickstart examples here: https://github.com/kubernetes-incubator/bootkube/issues/337

Last place would be the single-node example.

**Comment by aaronlevy** [comment]
Single node added in: https://github.com/kubernetes-incubator/bootkube/pull/382

**Comment by aaronlevy** [comment]
Closing as we should have the hack examples at least initially covered now.
