### ISSUE TITLE
hack/multi-node example does not manage to start flannel on worker node with self-hosted etcd

### ISSUE THREAD

**Issue by MarkusTeufelberger** [kubernetes-incubator/bootkube#341]
Using current master branch (https://github.com/kubernetes-incubator/bootkube/commit/9c57fa86563b925e0cc9b619395e7f53121b7816) and running with SELF_HOST_ETCD=true ./bootkube-up the setup seems to run reasonably well on the c1 node, but fails on the w1 node. This means there is no etcd running. Yes, I've read the "WARNING: THIS IS NOT YET FULLY WORKING - merely here to make ongoing testing easier" line in the beginning, this issue is to document where it currently seems to hang.

Flannel seems to try to connect to 10.3.0.1:443, fails doing so (obviously --> c1 is actually at 10.0.2.15) and this means etcd and kube-dns don't have /run/flannel/subnet.env available and thus are caught in a restart loop.

Flannel error:

    E0301 13:25:25.328558       1 main.go:127] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-wjm47': Get https://10.3.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-wjm47: dial tcp 10.3.0.1:443: getsockopt: connection refused

Googling this error seems to point to issues flannel might have with etcd (duh, it's not even running yet!), probably it requires some other hardcoded IPs to properly start.

After a lot of looking around, docker inspect [flannel container hash on w1] offers a better insight:
Apparently KUBERNETES_SERVICE_HOST is set to 10.3.0.1 in the container environment vars, which is wrong.

kube-flannel.yaml should contain the actual port + IP conbinations of the controller as far as I understand it, then probably it would be able to actually run with self-hosted etcd.

**Comment by MarkusTeufelberger** [comment]
Probably https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L596 needs to be extended to have the correct IP addresses in the environment variable, I'll try to manually step through the process and modifying the file before running vagrant to see if it helps.

**Comment by aaronlevy** [comment]
@MarkusTeufelberger just to make sure that all existing assets are cleaned up, can you reproduce the issue with the following steps:

```
cd hack/multi-node
rm -rf cluster
vagrant destroy -f
SELF_HOST_ETCD=true ./bootkube-up
```

If you happen to be changing any of the network settings - it's possible you're running into: https://github.com/kubernetes-incubator/bootkube/issues/329

But with no changes the above steps should work. It may take a few minutes for all components to settle (e.g. some of the flannel pods will not immediately be able to contact the api-server when they're first launched, but will after a couple minutes).

**Comment by MarkusTeufelberger** [comment]
Weird, this time it worked, even though I didn't change any configs the first time either.

I can't reproduce it atm., feel free to close this issue. :-/
