### ISSUE TITLE
bootkube on baremetal with Container Linux, rkt and flannel

### ISSUE THREAD

**Issue by dragoschiplink** [kubernetes-incubator/bootkube#347]
Hello,

I am trying to setup a cluster with Container Linux, rkt and flannel + bootkube.

This is my kubelet.service: http://pastebin.com/n9wX0JvN 

Bootkube is not starting...

http://pastebin.com/hP6XaetQ

Can someone help me with this?

Regards.

Dragos

**Comment by dghubble** [comment]
Have you followed https://github.com/coreos/matchbox/blob/master/Documentation/bootkube.md? What version of bootkube? I'd expect a much longer paste log if bootkube is timing out and failing.

**Comment by dragoschiplink** [comment]
Hi,

The documentation is not up to date and it does not provide all the steps (for exampe the bootkube service is not documented).

I used this to generate the config and start bootkube (version v0.3.8):

wget https://github.com/kubernetes-incubator/bootkube/releases/download/v0.3.8/bootkube.tar.gz
tar xzf bootkube.tar.gz
./bin/linux/bootkube render --asset-dir=assets --api-servers=https://CoreOS01.cloud:443
copy bootstrap-kubeconfig on all nodes
start bootkube with the generated assets files

Here is a extended log: http://pastebin.com/EA8Rhcwi

Regards.

Dragos

**Comment by dghubble** [comment]
You should skip v0.3.8, TLS bootstrapping was reverted. Matchbox docs will bump to v0.3.9 in a bit.

**Comment by dragoschiplink** [comment]
Can you provide also some info on bootkube.service?

**Comment by dghubble** [comment]
It just runs `bootkube start` with rkt to save you having to copy the correct bootkube binary to the host. And makes it easy to journal.

```
[Unit]
Description=Bootstrap a Kubernetes control plane with a temp api-server
[Service]
Type=simple
WorkingDirectory=/opt/bootkube
ExecStart=/opt/bootkube/bootkube-start
```

Btw, you can run `systemctl cat bootkube` to find this out in future.

**Comment by dragoschiplink** [comment]
On a fresh install of Container linux I do not have a bootkube.service and there is no /opt/bootkube/bootkube-start :)

**Comment by dghubble** [comment]
Your PXE infrastructure and matchbox are responsible for bare-metal CoreOS nodes being provisioned with the expected services (kubelets, etcd cluster) and files.

You might checkout the matchbox [concepts](https://coreos.com/matchbox/docs/latest/matchbox.html) and revisit the guide on using [bootkube](https://github.com/coreos/matchbox/blob/master/Documentation/bootkube.md) once you're setup. This is intended for large networks which provision machines from the network.

**Comment by dragoschiplink** [comment]
My PXE setup generates something similar to the matchbox examples. The only difference that I can think of is that the kubelet.service is using rkt (--container-runtime=rkt) and flannel is started before bootkube...

**Comment by dghubble** [comment]
Self-hosted Kubernetes does not use rkt as the container runtime.

**Comment by dragoschiplink** [comment]
So that is the problem :)

Thank you for your help.

**Comment by dghubble** [comment]
np
