### ISSUE TITLE
emptyDir volume was lost after node restart

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes-incubator/bootkube#357]
What?

In self hosted etcd mode, etcd pod was using `emptyDir` volume, which is expected to endure node crash.

In`$BOOTKUBE_PATH/hack/multi-node/`, run
```
$ SELF_HOST_ETCD=true ./bootkube-up
```

After `boot-etcd` is deleted, check etcd data dir:
```
$ kubectl --kubeconfig=cluster/auth/kubeconfig exec -n kube-system -ti kube-etcd-0000 -- /bin/sh
... in etcd pod now ...
$ ls /var/etcd/data/member/
snap  wal
```

Then restart node:
```
$ vagrant ssh c1
... in c1 box now ...
$ sudo reboot
```

After restart, two weird things happened.

### etcd pod exit (1) because emptyDir volume was lost

ssh into c1 again.

`docker ps` showed that
```
02f18b251d2b        quay.io/coreos/etcd:v3.1.0                                                 "/bin/sh -c 'ls /var/"   27 seconds ago      Exited (1) 21 seconds ago                               k8s_etcd.ba4f961f_kube-etcd-0000-172.17.4.101_kube-system_359b9af4ae91e38bdfd51d3efa83a399_6d8020e9
```

**Note**: this is custom etcd pod that will first `ls /var/etcd/data/ || true ; ls /var/etcd/data/member/wal || true ; ls /var/etcd/data/member/snap || true`.

`docker logs 02f18b251d2b` showed that
```
ls: /var/etcd/data/: No such file or directory
ls: /var/etcd/data/member/wal: No such file or directory
ls: /var/etcd/data/member/snap: No such file or directory
```

### etcd pod was created twice

Soon after the previous etcd pod failed, another was created:
```
$ docker ps
f3bdf21851d7  quay.io/coreos/etcd:v3.1.0  "/bin/sh -c 'ls /var/"   5 seconds ago       Exited (1) Less than a second ago                       k8s_etcd.ba4f961f_kube-etcd-0000-172.17.4.101_kube-system_359b9af4ae91e38bdfd51d3efa83a399_047ab2d3
02f18b251d2b  quay.io/coreos/etcd:v3.1.0  "/bin/sh -c 'ls /var/"   27 seconds ago      Exited (1) 21 seconds ago                               k8s_etcd.ba4f961f_kube-etcd-0000-172.17.4.101_kube-system_359b9af4ae91e38bdfd51d3efa83a399_6d8020e9
```

Although its log might not be related, it showed:
```
ls: /var/etcd/data/member/wal: No such file or directory
member
db
```

**Comment by hongchaodeng** [comment]
@aaronlevy @ethernetdan @xiang90 

For more context, we need persistence through (master) node crash for etcd pods

**Comment by aaronlevy** [comment]
@hongchaodeng empty-dir is not expected to survive node crash. empty-dir is just within the pod filesystem - it only survives for as long as the pod does

**Comment by hongchaodeng** [comment]
@aaronlevy 

OK. I re-read the docs. Seems like I have misunderstood "crash". The crash seems to refer to container crash/restart
