### ISSUE TITLE
kubernetes GC bug could cause self-hosted etcd mode to fill up disk quickly and fail

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes-incubator/bootkube#371]
For k8s 1.5 or less, kubernetes GC has an issue: https://github.com/kubernetes/kubernetes/issues/39816 . This bug will cause GC to spam unuseful error logs like `unable to get REST mapping for kind` and eventually fill up the disk. After that, kubernetes control plane, potentially etcd, might fail due to disk fullness.

More tracks on this issue:
- There is a sooth (coming k8s 1.6) that reduce to log to print only once: https://github.com/kubernetes/kubernetes/pull/42862
- There is a plan to fix it in k8s 1.7: https://github.com/kubernetes/kubernetes/pull/42615

**Comment by odacremolbap** [comment]
That can be solved adding `- --enable-garbage-collector=false` to apiserver and controller manager rendered files until k8s 1.6 is released.

**Comment by lblackstone** [comment]
I disabled the GC unconditionally, but that could be revised to only happen if etcd is self-hosted if that makes more sense.

**Comment by aaronlevy** [comment]
This should be resolved now that we're using v1.6 in bootkube
