### ISSUE TITLE
self hosted etcd: reboot/poweroff testing

### ISSUE THREAD

**Issue by xiang90** [kubernetes-incubator/bootkube#379]
To get enough confidence around self hosted etcd recovery, we want to stress out the full control panel rebooting, full control panel power off, partial control panel rebooting, partial control panel power off cases. 

Initially, we want to setup a self hosted etcd cluster with 3 master nodes. We simulated the above 4 cases with random concurrent machine reboots and power off (shutdown the machine and not restart immediately).

We want to ensure that once the all the machines are up again, the K8S control panel can recover.

The test should be a long running one that can run 7 * 24.

/cc @aaronlevy @pbx0 @ethernetdan

**Comment by hongchaodeng** [comment]
What's the length of poweroff do we expect/define?

**Comment by xiang90** [comment]
@hongchaodeng Probably from  rand(1 minute, 10 minutes) initially?

**Comment by pbx0** [comment]
We just need to divide this up into individual tests. How does this sound:
- reboot single master with single etcd. Ensure k8s comes back up (we just need to enable this)
- reboot 3 master with 3 etcd simultaneously. Enure k8s comes back up
- reboot 3 master with 3 etcd one node at a time and ensure availability during each reboot. (If we want to test availability via the api-server we need to support setting up true multi-master where the api-server will be available via a load-balancer somehow or never reboot the first node with the api-server on it)
- setup 4 master nodes and 3 etcd pods. Fully decommission a master node and see if etcd-cluster heals eventually
- make long-running versions of some of the former tests 

@xiang90 Did I interpret that right?

**Comment by xiang90** [comment]
@pbx0 

This would be a good start. Let's build what you described initially.

I have a few clarification (suggestion) on the ideal tests:

- We need to differentiate a reboot and power failure (shutdown)

A reboot server will come up within 5 minutes. A power failed server might come back online > 30 minutes. Quite a few components in self hosted stack have hard coded health checking limit. We should understand what might go wrong if one or a few nodes are offline for quite a whil

- We should do some random failure injection

We usually design our systems for what we know and understand. We design our test in the same way as our system. We will miss some interesting cases if we only do deterministic testing.

**Comment by ericchiang** [comment]
Self-hosted etcd has been removed from bootkube for the time being. Will re-open if/when we add it back in.
