### ISSUE TITLE
Support for offline installs

### ISSUE THREAD

**Issue by alekssaul** [kubernetes-incubator/bootkube#393]
Today bootkube manifests seem to be built into binary. This requires access to quay.io/gcr.io. 

There are few companies that are interested in using an internal registry to bootstrap the cluster without having direct access to quay.io/gcr.io.

Would be great if there was a way to pass registry hostname as a variable to bootkube. Users can sync/mirror contents from quay.io/coreos/* and gcr.io/google-containers/* to internal registry for offline deployment of Kubernetes via Bootkube.

**Comment by MarkusTeufelberger** [comment]
This would also allow for using different images than the Debian based ones by CoreOS which contain several vunerabilities: https://quay.io/repository/coreos/hyperkube?tag=latest&tab=tags
