### ISSUE TITLE
hack/quickstart needs to support locally built binary & container releases

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#399]
Now that we're moving to a release-branch pattern (https://github.com/kubernetes-incubator/bootkube/issues/397) the current hack/quickstart setup doesn't work as well.

It currently uses a particular bootkube-image version, which comes from an official release - however, if master is the place where new work is being integrated - the changes may not work with the older image releases (but would if we were using locally built binary).

I would like to support using the quickstart guides with locally built binaries - because it makes testing during development much easier. However, we also need to support "This is how you get started with a release" -- which might just be documentation.

An initial thought:

- the `init-master` and `init-worker` scripts get new env var that can use local binary or a release image.
- If release image is selected, we have versioned directories for the kubelet service (e.g. `hack/quickstart/kubelet-0.3` ?? As this is likely the thing to break between versions (kubelet flags change, for example).

Not super excited about the above - so wanted to open this to get other's thoughts.

/cc @yifan-gu @derekparker @dghubble @ericchiang @pbx0

**Comment by pbx0** [comment]
Just to add: for PR testing, we build bootkube from the PR and push to `quay.io/coreos/bootkube-dev:<git-hash>` and we also use the service files in the hack dir from that same PR commit. This keeps everything in sync for testing except when, for the above reasons, we occasionally wait to update the service files for the kubelet until an official release is out.

If we default to using local binaries instead of defaulting to the latest release, then we can keep quickstart guides fully in-sync with the rest of the tree.

I think it does make sense for developers to build locally and use that in any test setups. If we build a test tool in-tree it makes sense for that to support this as well.

**Comment by rmenn** [comment]
If im not intruding on the process, the release branch method could solve certain problems ( i see this as an end user ), Once a branch a cut then let things go to the next branch make changes to code and hack/* which people can actually consume, if `bootkube:<commit>` is being built then thats great, i had this question some time ago, i didnt find an answer.

 But i dont believe the images are being built per commit, atleast i dont see them on `https://quay.io/repository/coreos/bootkube?tab=tags`

I also agree that developers need to build there locally, but it just need to be made slightly friendly for newer developers or have proper instructions ( dont know if i missed it ). 

So came here to say im on board with the release branch and then keep the next branch up to date with experimentation

**Comment by aaronlevy** [comment]
Definitely not intruding - good to get feedback for how people end up using bootkube.

The easiest from a developer standpoint would be to use the vagrant examples, which can be spun up using the `make run-single` or `make run-multi` - as those will recompile bootkube, then launch a cluster. But often-times it might be easier to test in a cloud provider (e.g. in CI) so we do also need to add the ability to run from source to all hack/* examples.

We also have an internal backlog item to do builds off the master branch. It would likely end up in an alternative repo under: `quay.io/coreos/bootkube-git` with each tag bing the git hash from latest master. A few people have asked for this - so something we'll hopefully add soon

**Comment by aaronlevy** [comment]
I'm also thinking that we move all guides under `hack/` to use locally build binaries. Then we link out to projects, like [tectonic-installer](https://github.com/coreos/tectonic-installer) / https://github.com/kubernetes-incubator/bootkube/issues/406 that use the actual release images for launching non-development clusters

**Comment by aaronlevy** [comment]
closed by https://github.com/kubernetes-incubator/bootkube/pull/428
