### ISSUE TITLE
Support etcd+TLS

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#403]
We should have options for both "bring your own etcd" and "self-hosted" etcd. And this should be the default installation method.

- The etcd TLS assets needed by the api-server should be populated in a secret
- The data that needs to end up on etcd nodes (non-self-hosted) will need to be plumbed through all `hack/*` examples (e.g. when launching etcd-member.service, it needs to have the generated TLS assets available).
- self-hosted etcd will likely require changes to the etcd-operator - as that is responsible for launching the etcd pods - and we would need to add secret volumes to distribute the TLS assets.

Related:
https://github.com/kubernetes-incubator/bootkube/issues/244
https://github.com/kubernetes-incubator/bootkube/issues/389

**Comment by mfburnett** [comment]
Related: https://github.com/coreos/tectonic-forum/issues/86

**Comment by hongchaodeng** [comment]
@aaronlevy @mfburnett 
Are there any well-defined use case for TLS setup? How does user want to generate certs?
Implementing TLS is simple, but is also permanent.

**Comment by vmatekole** [comment]
@aaronlevy  and @mfburnett ... I attempted to enable auto-tls in etcd3  within the tectonic-controller.yaml.tmpl  located in the published Ignition assets from the installer to Provisioner:
```
systemd:
  units:
    - name: etcd-member.service
      enable: true
      dropins:
        - name: 40-etcd-cluster.conf
          contents: |
            [Service]
            Environment="ETCD_IMAGE_TAG=v3.1.2"
            {{- if index . "external_etcd"}}
            ExecStart=
            ExecStart=/usr/lib/coreos/etcd-wrapper gateway start \
                --listen-addr=0.0.0.0:2379 \
                --endpoints={{.etcd_endpoints}}
            {{- else}}
            Environment="ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379"
            ETCD_INITIAL_CLUSTER="node0=https://etcd0.seedbloom.it:2380,node1=https://etcd1.seedbloom.it:2380,node2=https://etcd2.seedbloom.it:2380
            Environment="ETCD_ADVERTISE_CLIENT_URLS=https://{{.domain_name}}:2379"
            Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=https://{{.domain_name}}:2380"
            Environment="ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380"
            Environment="ETCD_NAME={{.etcd_name}}"
            Environment="ETCD_AUTO_TLS=true"
            Environment="ETCD_PEER_AUTO_TLS=true"
            Environment="ETCD_STRICT_RECONFIG_CHECK=true"
            {{- end}}
```

etcd3 cluster is healthy and nodes are talking to each other. However, there is a problem with Kubernetes and publishing information to the controllers. Spent quite a bit of time on this to no avail, we're waiting on this feature to ship instead as it seems Tectonic isn't purposed yet for etcd over TLS and therefor a showstopper for a planned production cluster. Looking forward to when this is shipped.:
```
Mar 28 08:16:58 etcd0.seedbloom.it kubelet-wrapper[817]: E0328 08:16:58.227005     817 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get https://controllers.seedbloom.it:443/api/v1/nodes?fieldSelector=metadata.name%3Detcd0.seedbloom.it&resourceVersion=0: dial tcp 45.76.92.226:443: getsockopt: connection refused
Mar 28 08:16:58 etcd0.seedbloom.it kubelet-wrapper[817]: E0328 08:16:58.228994     817 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get https://controllers.seedbloom.it:443/api/v1/services?resourceVersion=0: dial tcp 45.76.92.226:443: getsockopt: connection refused
Mar 28 08:16:58 etcd0.seedbloom.it kubelet-wrapper[817]: E0328 08:16:58.230066     817 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get https://controllers.seedbloom.it:443/api/v1/pods?fieldSelector=spec.nodeName%3Detcd0.seedbloom.it&resourceVersion=0: dial tcp 45.76.92.226:443: getsockopt: connection refused
Mar 28 08:16:59 etcd0.seedbloom.it kubelet-wrapper[817]: E0328 08:16:59.244123     817 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node 'etcd0.seedbloom.it' not found
Mar 28 08:16:59 etcd0.seedbloom.it kubelet-wrapper[817]: E0328 08:16:59.245925     817 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get https://controllers.seedbloom.it:443/api/v1/nodes?fieldSelector=metadata.name%3Detcd0.seedbloom.it&resourceVersion=0: dial tcp 45.76.92.226:443: getsockopt: connection refused
Mar 28 08:16:59 etcd0.seedbloom.it kubelet-wrapper[817]: E0328 08:16:59.246420     817 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get https://controllers.seedbloom.it:443/api/v1/pods?fieldSelector=spec.nodeName%3Detcd0.seedbloom.it&resourceVersion=0: dial tcp 45.76.92.226:443: getsockopt: connection refused
Mar 28 08:16:59 etcd0.seedbloom.it kubelet-wrapper[817]: E0328 08:16:59.246765     817 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get https://controllers.seedbloom.it:443/api/v1/services?resourceVersion=0: dial tcp 45.76.92.226:443: getsockopt: connection refused
```

**Comment by diegs** [comment]
https://github.com/kubernetes-incubator/bootkube/pull/433 addresses the "bring your own etcd" case.

Some additional work remains on the etcd operator side to support the self-hosted etcd case.

**Comment by aaronlevy** [comment]
I'll close this and open a new tracking issue for self-hosted etcd (as that is primarily going to be an external dependency).

**Comment by aaronlevy** [comment]
Opened https://github.com/kubernetes-incubator/bootkube/issues/445 to track self-hosted etcd + tls
