### ISSUE TITLE
v1.6.0 deprecated flag --minumum-container-ttl-duration

### ISSUE THREAD

**Issue by pbx0** [kubernetes-incubator/bootkube#404]
Running the v1.6.0 kubelet produces a warning:
```
Flag --minimum-container-ttl-duration has been deprecated, Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.
```

Its not clear that the eviction flags are drop-in replacements for this flag, see: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-eviction.md

**Comment by aaronlevy** [comment]
We should just drop this flag for now and not worry about replacement (and rely on eviction defaults for now). It was originally added to make debugging easier (docker was GCing old images too quickly).

**Comment by diegs** [comment]
Yes, that was gong to be my recommendation based on reading the docs.
