### ISSUE TITLE
hack: deprecate cluster spin-up in favor of tectonic installer

### ISSUE THREAD

**Issue by philips** [kubernetes-incubator/bootkube#406]
The [tectonic-installer](https://github.com/coreos/tectonic-installer) should be a more flexible and better tested setup for spinning up and down self-hosted clusters using bootkube. Perhaps we can drop the hack directories and move to it instead after addressing https://github.com/coreos/tectonic-installer/issues/133

**Comment by MarkusTeufelberger** [comment]
Doesn't Tectonic also require a matchbox server and PXE booting etc.? Seems a bit convoluted to set up for tests.

**Comment by dghubble** [comment]
@MarkusTeufelberger I can clear up some of the confusion.

On cloud providers, `hack` and Tectonic Installer (both official GUI app and terraform alphas) communicate with the relevant cloud provider API. `matchbox` isn't involved.

matchbox is an open-source service and API for creating **bare-metal** CoreOS Container Linux clusters.

* If you're interested in creating bootkube (i.e. self-hosted) Kubernetes clusters on bare-metal, please see the usual [docs](https://github.com/coreos/matchbox/blob/master/Documentation/bootkube.md) which use matchbox.
* If you're interested in creating Tectonic clusters on bare-metal, see [Tectonic Bare-Metal](https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html). This is what the `tectonic-installer`'s official bare-metal release links to as well. This uses matchbox and requires a Tectonic license.

I hope that clears things up.

**Comment by MarkusTeufelberger** [comment]
I know, right now the "hack" testbed for bootkube rolls out one or more CoreOS (now "Container Linux by CoreOS") Vagrant boxes and spins up Kubernetes in there.

Using tectonic-installer would either mean re-implementing some functionality that Tectonic already has to provision these CLbC machines using a dedicated Matchbox VM to get a full bootstrapping experience or to use a more streamlined process using pre-built images from whereever that remove some of the steps along the way. This would also make sure that Bootkube tests don't get impacted by Tectonic problems, but risks that some things that are present in pre-built images are assumed to be provided in the general case.

The examples in "hack" could be rewritten to be provisioned the "cloud" way (get a known precompiled image and proceed from there) or the "bare metal" way (spin up a few VMs and spell out exactly what to install where and how to configure everythign from scratch). Both paradigms might have their merits, at the moment the open sourced parts of Tectonic don't seem to be capable of launching a cluster locally as far as I see it - I am sure that'll change soon though. :-)

**Comment by dghubble** [comment]
I don't have a stance, just wanted to clarify wrt matchbox.

Agreed. The hack examples for local use are nice to have and the open sourced parts of Tectonic don't handle those concerns currently. I'd look to bootkube maintainers to make a good choice about the examples and testing strategies that make sense for this project.

**Comment by MarkusTeufelberger** [comment]
Thanks for the clarification! Yes, I was a bit too terse there and assumed more knowledge about Tectonic than what might be expected by someone just stumbling over this feature request. :+1:

**Comment by aaronlevy** [comment]
I would prefer to keep the hack/* examples for spinning up local clusters using locally built binaries (related issue about converting the quickstart guides to using locally build binaries: https://github.com/kubernetes-incubator/bootkube/issues/399)

Bootkube is meant to be a building-block - so I think it might make sense to link out to tools which are more fully featured that can be used to launch full clusters (related: https://github.com/kubernetes-incubator/bootkube/issues/297#issuecomment-284513240). But the hack examples really are for quick development / testing - so I don't think they'll go away completely.

**Comment by omkensey** [comment]
Honestly it's not even necessary to spin up matchbox to make bootkube work with bare metal.  If you just create `/var/coreos/metadata` on a preinstalled system, add `COREOS_PRIVATE_IPV4` and `COREOS_PUBLIC_IPV4` variable declarations, and then add a line to source that file at the top of `init-master.sh` and `init-node.sh`, everything should work fine.  Matchbox has value as part of a persistent infrastructure, but for somebody who's trying to "quickstart" it may be more effort to set up than is strictly necessary.
