### ISSUE TITLE
Build pod-checkpointer images for multiple architectures

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#424]
For kubeadm to make use of the pod-checkpointer, we need to start building container images for upstream supported architectures.

Need a list of the architectures that are required - but opening this issue to track.

/cc @luxas

**Comment by luxas** [comment]
amd64, arm, arm64, ppc64le and s390x are the architectures that are needed

Should be as easy as setting GOARCH really. Please prioritize this as using the checkpointer is a necessary requirement for reliable selfhosting in v1.7 :+1:

**Comment by luxas** [comment]
friendly ping @aaronlevy
