### ISSUE TITLE
Add TLS support for self-hosted etcd clusters

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#445]
The etcd-operator will likely need changes to support this - but opening an issue to track that need.

**Comment by dghubble** [comment]
Unblocked by https://github.com/coreos/etcd-operator/pull/1103? cc @xiang90 @hongchaodeng

**Comment by xiang90** [comment]
@dghubble Yes. It is unblocked now.

**Comment by dghubble** [comment]
Closed by #582
