### ISSUE TITLE
nit: Use `operator: Exists` for tolerations

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#451]
We have a bunch of places in our manifests where we say `operator: Equals, value: ""` where we could just change that to `operator: Exists`:

example: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L104-L105

/cc @squat

**Comment by squat** [comment]
already made this, one issue ago :wink: https://github.com/kubernetes-incubator/bootkube/pull/450

**Comment by aaronlevy** [comment]
closed by https://github.com/kubernetes-incubator/bootkube/pull/450
