### ISSUE TITLE
self-hosted etcd pods need to tolerate master node taint

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#452]
Not sure if we can add tolerations to the spec: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/util/etcdutil/migrate.go#L127

Example of other master components: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L317-L322

/cc @hongchaodeng @xiang90

**Comment by xiang90** [comment]
hrm... i am wondering how tests can pass without toleration on etcd pods.

**Comment by xiang90** [comment]
@aaronlevy 

we need to add toleration to both the seed etcd pod (in bootkube) and the actual self hosted etcd pods, right?

**Comment by xiang90** [comment]
toleration is already added for etcd operator.

**Comment by aaronlevy** [comment]
@xiang90 tests are passing due to a bug in flannel that actually strips the taints -- but once we merge a fix for that (https://github.com/kubernetes-incubator/bootkube/issues/454) self hosted etcd stops working until we have tolerations on the etcd pods.

**Comment by aaronlevy** [comment]
Also seed pod is a static pod -- and the taints are only scheduler based right now (so static pods are unaffected).

**Comment by xiang90** [comment]
> Also seed pod is a static pod 

let's add the toleration anyway? in case it breaks in the future.

**Comment by aaronlevy** [comment]
Not opposed - but the taint is actually different for a kubelet enforced taint (noExec vs noScheduler) -- and noExec isn't implemented. We could tolerate all of them-- but seems overkill right now

**Comment by pbx0** [comment]
This may well be why scale test hasn't been passing: https://github.com/coreos/mantle/issues/567

**Comment by aaronlevy** [comment]
This was only just merged yesterday though: https://github.com/kubernetes-incubator/bootkube/pull/434

**Comment by xiang90** [comment]
> and noExec isn't implemented. 

good point. fine with me.

**Comment by squat** [comment]
etcd operator and etcd pods tolerate taints now. we can close this. cc @aaronlevy

**Comment by aaronlevy** [comment]
closed in https://github.com/kubernetes-incubator/bootkube/pull/461
