### ISSUE TITLE
Self hosted API server cannot resolve cluster DNS names due to hostNetworking

### ISSUE THREAD

**Issue by chancez** [kubernetes-incubator/bootkube#456]
See https://github.com/kubernetes/kubernetes/issues/17406 and https://github.com/kubernetes/kubernetes/pull/29378

Currently, the API server cannot resolve cluster DNS names because it inherits the hosts `/etc/resolv.conf`. This means, that the API server can't use DNS to access pods in the cluster for something like the webhook authorizer, or potentially an etcd cluster being accessed via a k8s service though a DNS name. Basically, any clusterIP service wouldn't be accessible to the API via DNS.

In 1.6, you will be able to use `DnsPolicy: ClusterFirstWithHostNet` which will fix the issue of resolving DNS.

**Comment by chancez** [comment]
Update: I did think this effected kubectl proxy, but it turns out those issues were user error. I updated the original issue to remove the concerns about the kubectl proxy.

**Comment by aaronlevy** [comment]
This is somewhat two discussions. I think one is changing the dns policy on api-server (which seems reasonable). Then there is another issue to track discussion about using host-network for apiserver.

Can we break this into two issues?

**Comment by chancez** [comment]
Broke of the other piece into it's own issue.

**Comment by xiang90** [comment]
> In 1.6, you will be able to use DnsPolicy: ClusterFirstWithHostNet which will fix the issue of resolving DNS.

have you tried this with 1.6? @hongchaodeng tried this the other day. and it does not seem to work.

**Comment by chancez** [comment]
I haven't tried it yet, no. If that's the case, there's still the option of figuring out how to make it use pod networking.

**Comment by thomastaylor312** [comment]
Little late on this issue, but we changed our self-hosted API server (spun up with bootkube) to use `ClusterFirstWithHostNet`. It seems to work well, but we get lots of flakes spinning up a cluster in a cloud provider (AWS in this case) because it can't resolve the API if the cluster DNS isn't ready
