### ISSUE TITLE
Deploy rescheduler to make use of "critical pod" annotations 

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#474]
This is technically an "alpha" feature - so we need to decide if this is something we want to do.

**Comment by aaronlevy** [comment]
It is not safe to run the rescheduler when we have the "critical pod" annotation added to the self-hosted scheduler and controller-manager. See discussion in https://github.com/kubernetes-incubator/bootkube/issues/519

**Comment by aaronlevy** [comment]
This should be blocked until https://github.com/kubernetes-incubator/bootkube/issues/689 is resolved

**Comment by diegs** [comment]
This is obsolete. The rescheduler is deprecated in favor of priorities.
