### ISSUE TITLE
Documentation: Running bootkube from a container

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#486]
We changed the hack/* scripts to use locally built binaries, so now there is no canonical example of using bootkbue from a container image. We should add brief documentation examples for this

**Comment by rmenn** [comment]
I believe i have something which can be used, you could assign this to me. RFC on what i use currently

https://github.com/rmenn/bootkube-osx/blob/master/controller.yml#L49-L69

**Comment by aaronlevy** [comment]
Yeah there might be a couple minor changes, like using `--dns=host` rather than explicit mount to `/etc/resolv.conf` (see https://github.com/coreos/tectonic-installer/blob/master/modules/bootkube/resources/bootkube.sh for reference). It might also be helpful to provide examples of using both `render` and `start` (e.g. mounting the same asset dir between them) & maybe even a docker example too.

It would be great if you could open a PR and we can do a review there. We could add it to the "usage" section here https://github.com/coreos/tectonic-installer/blob/master/modules/bootkube/resources/bootkube.sh -- or we maybe break that out into its own doc uder `Documentation/` and we link to a more thorough usage (binary and container based).

**Comment by aaronlevy** [comment]
It doesn't look like this lets me assign to you -- but if you're able to pick this up, that would be super helpful!

**Comment by v1k0d3n** [comment]
guess that was a no? :) jk. been looking into this as well, and yes I agree with `--dns=host`. I've also been using [hostess](https://github.com/cbednarski/hostess) for some situations where I need to idempotently change underlying `/etc/hosts` entries.

so what do you want to do with this issue @aaronlevy? i do think documentation would be helpful for users.

and just to keep this thread current for any other users stumbling here, the portion @rmenn referred to is [HERE](https://github.com/rmenn/bootkube-osx/blob/92ccf29e650bd456ba1891ec20bcc78792a3e59d/controller.yml#L49-L69). when running `bootkube start` completely from a container, wouldn't there need to be some v-mounts (i.e. `/etc/kuberentes/`)?

**Comment by v1k0d3n** [comment]
ahh...[maybe not i guess](https://github.com/aaronlevy/bootkube/blob/fd2bbc49eabc58a68a8f19176b6ed663cd5905e1/hack/multi-node/bootkube-up#L32).
