### ISSUE TITLE
Self-hosted etcd cannot survive pod deletion

### ISSUE THREAD

**Issue by dghubble** [kubernetes-incubator/bootkube#498]
Simply deleting the etcd pod in a single master setup (most common) seems to not reconcile and create a new pod, which causes a cluster outage. This is less resilient than the default on-host setup and other control plane pods, which can recover from pod failures. In the on-host case, one can repair any etcd issues (or systemd restarts them) as long as data is still present on disk.

Longer discussion: https://github.com/coreos/tectonic-installer/pull/601#issuecomment-300242512

**Comment by hongchaodeng** [comment]
There is only one etcd pod, right? If so, deleting it means losing the entire cluster.
We are working on disaster recovery at the moment.
For more info, please track on https://github.com/kubernetes-incubator/bootkube/issues/432 .
I think this is dup to that issue.

**Comment by aaronlevy** [comment]
This would be more akin to deleting `/etc/kubernetes/etcd-pod.yaml` or deleting the etcd-member.service` (essentially you're saying "this should no longer be running on this host").

simple pod failure *should* recover (e.g. kubelet will keep trying to restart it). Deletion is a little bit more questionable.

I'll actually move this into https://github.com/kubernetes-incubator/bootkube/issues/432
