### ISSUE TITLE
Remove log-flush-frequency flag

### ISSUE THREAD

**Issue by odacremolbap** [kubernetes-incubator/bootkube#53]
bootkube imports indirectly ```k8s.io/kubernetes/pkg/util.logs```, which is creating the global flag:

```
var logFlushFreq = pflag.Duration("log-flush-frequency", 5*time.Second, "Maximum number of seconds between log flushes")
```
As far as I can guess, this flag will not be used in bootkube, but it shows up through the Usage function.

```
$ ./bootkube version -h
Output version information

Usage:
  bootkube version [flags]

Global Flags:
      --log-flush-frequency=5s: Maximum number of seconds between log flushes
```

Can the flag be removed?

**Comment by aaronlevy** [comment]
closed in https://github.com/kubernetes-incubator/bootkube/pull/143
