### ISSUE TITLE
Bootstrap self-hosted etcd is using the 200th IP in the service range

### ISSUE THREAD

**Issue by dghubble** [kubernetes-incubator/bootkube#531]
Is there a reason to pick the 200th IP in the service range for bootstrap self-hosted etcd? The other IP offsets for apiserver, dns, and self-hosted etcd are 1, 10 and 15 respectively. Did you mean to pick 20?

https://github.com/kubernetes-incubator/bootkube/blob/master/cmd/bootkube/render.go#L24

I ask because this seems to assume the service range is a `/24` or larger. I'd expect inputing a `/25` would quietly fail with self-hosted etcd enabled.

**Comment by dghubble** [comment]
This doesn't affect me directly, but I know some users were using a `/27`.

**Comment by diegs** [comment]
@dghubble I picked something out of the way because I didn't want to conflict with any permanent self-hosted services.

I can change it to something lower, though, if using `/27` is something users do.

**Comment by dghubble** [comment]
:+1: This will fix one thing @redbeard was experiencing.
