### ISSUE TITLE
Use atomic writes instead of WriteFile

### ISSUE THREAD

**Issue by philips** [kubernetes-incubator/bootkube#534]
Periodically I am getting null Object kinds on one of my nodes.

```
May 20 00:07:02 ip-10-0-2-146 kubelet-wrapper[3854]: E0520 00:07:02.551201    3854 file_linux.go:113] can't process config file "/etc/kubernetes/manifests/kube-system-pod-checkpointer-tk4lx.json": /etc/kubernetes/manifests/kube-system-pod-checkpointer-tk4lx.json: read '', but couldn't parse as pod(Object 'Kind' is missing in 'null').
```

This line of code is the cause, need to use WriteAtomic https://github.com/kubernetes-incubator/bootkube/blob/57674db6ef97a7d73ba7d92d0203ecefaf4e0695/cmd/checkpoint/main.go#L683

Some more logs: https://gist.github.com/philips/565552abf726e8c9aec7a3dbbd2ca4e9

**Comment by philips** [comment]
cc @aaronlevy

**Comment by chancez** [comment]
Add by WriteAtomic you mean write to a tmpfile and rename?

**Comment by fxposter** [comment]
I guess @philips talks about https://github.com/kubernetes-incubator/bootkube/blob/57674db6ef97a7d73ba7d92d0203ecefaf4e0695/cmd/checkpoint/main.go#L794

**Comment by aaronlevy** [comment]
closed in https://github.com/kubernetes-incubator/bootkube/pull/537
