### ISSUE TITLE
Use tags for checkpointer releases

### ISSUE THREAD

**Issue by diegs** [kubernetes-incubator/bootkube#545]
Currently we are using hashes, which is a little unwieldy.

**Comment by aaronlevy** [comment]
It would feel a little weird to have checkpointer specific release tags in this repo. Or it means we have to tie checkpointer version to bootkube version. Kind of leaning toward relying on hashes unless the checkpointer is moved outside this repo (then it can have its own release tags)

**Comment by diegs** [comment]
Closing in favor of moving to a separate incubator project.
