### ISSUE TITLE
hack/terraform-quickstart flake

### ISSUE THREAD

**Issue by pbx0** [kubernetes-incubator/bootkube#552]
Occasionally terraform will successfully complete but the IP address in the output variable for the bootstrap node is blank, causing the start scripts to fail.

1 example: https://jenkins-kube-lifecycle.prod.coreos.systems/job/bootkube-e2e-pr-selfetcd/55/

**Comment by aaronlevy** [comment]
job info not public, so for posterity:

```
Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: 

Outputs:

bootstrap_node_ip = 
master_ips = [
    ,
    x.x.x.x
]
self_host_etcd = true
worker_ips = [
    y.y.y.y
]
./init-master.sh: line 4: $1: unbound variable
Build step 'Execute shell' marked build as failure
```

**Comment by pbx0** [comment]
terraform was bumped to 0.9.6, but the issue was still witnessed.

**Comment by pbx0** [comment]
This should be solved now by issuing `./terraform refresh` a few seconds after the resources are created. I added that to all PR e2e jobs, we can re-open if the issue is seen again.
