### ISSUE TITLE
Set resource requirements for self-hosted etcd

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes-incubator/bootkube#563]
Currently we haven't set any resource requirements for self-hosted etcd pods. This could be done via cluster spec.

For each etcd pod, we should require at least 1GB mem and 1 core cpu.

**Comment by hongchaodeng** [comment]
cc @xiang90 @aaronlevy

**Comment by ericchiang** [comment]
Self-hosted etcd has been removed from bootkube for the time being. Will re-open if/when we add it back in.
