### ISSUE TITLE
Use versioned config file in render/start as replacement of flags

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#565]
Before going 1.0 bootkube should have some compatibility enforcement. It's difficult to do this with flags, so we probably should move to something like a versioned config file that is consumed by both the `render` and `start` subcommands.

**Comment by colemickens** [comment]
`start` currently only takes two flags: `--asset-dir` and `--pod-manifest-path`.

I would suggest that we treat `--asset-dir` as the pointer to the state+configuration for the cluster. Any configuration file would be implicitly part of the asset dir. In the asset dir, we could introduce a new configuration file `bootkube.yaml` or some such, with cluster-specific details, like the kubelet pod manifest path location.

We could continue to support the flags for some time, persisting them into the asset-dir as we `render`, and encourage users to move to a configuration file and then eventually drop the individual flags we support in `render` / `start` other than `--asset-dir`.

Alternatively, we might consider adopting either `kubeadm`'s "MasterConfiguration" yaml config file and supporting a subset of fields, or probably better, support the new [Cluster API](https://github.com/kubernetes/kube-deploy/tree/master/cluster-api) which seems built for tools like `bootkube`.
