### ISSUE TITLE
Link to related upstream proposals for self-hosted in README

### ISSUE THREAD

**Issue by chancez** [kubernetes-incubator/bootkube#57]
I've been getting more questions about self-hosted as 1.3 approaches and since I've been talking about self-hosted in a couple of SIGs.

I've gotten feedback that this is awesome work, but the README in the repo doesn't really provide any information about the actual implementation/upstream work involved.

It would be great if we just documented this in some more detail, as well as linking to the upstream proposals this project is related to. I might submit a PR for this when I get some free time, but opening here to document the feedback.

**Comment by aaronlevy** [comment]
Closed in: https://github.com/kubernetes-incubator/bootkube/pull/289
