### ISSUE TITLE
Proposal: change flannel port to 4789

### ISSUE THREAD

**Issue by lblackstone** [kubernetes-incubator/bootkube#575]
The [tectonic-installer](https://github.com/coreos/tectonic-installer/commit/b620c16f0a4b82ee65b2d248fd98512a9f7e430e) repo uses 4789 as the IANA-defined port for flannel. If it doesn't break anything, it might be worth updating here as well.

Related links:
## bootkube
[flannel-cfg](https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L1043-L1049)
[port doc](https://github.com/kubernetes-incubator/bootkube/blob/master/Documentation/network-requirements.md)

## tectonic-installer
[flannel-cfg](https://github.com/coreos/tectonic-installer/blob/4ea97a0/modules/bootkube/resources/manifests/kube-flannel.yaml#L18-L24)
[port doc](https://github.com/coreos/tectonic-installer/blob/master/Documentation/generic-platform.md)

**Comment by aaronlevy** [comment]
That change seems reasonable to me

**Comment by lblackstone** [comment]
Fixed by #982
