### ISSUE TITLE
Add TLS to self-hosted etcd

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes-incubator/bootkube#582]
Currently self-hosted etcd mode doesn't have TLS option. We want to make use of static TLS feature in etcd operator and provide that in self-hosted etcd.

Attach plan in bootkube:
- ~~Add flags to pass in etcd server's client and peer communication x509 certs~~
- [X] Auto-generate 3 (CA, key, cert) certificate suites for self-hosted etcd (https://github.com/kubernetes-incubator/bootkube/issues/585)
  - operator etcd client SAN: none
  - etcd server client port SAN:
    - etcd service IP
    - boot etcd service IP
    - 127.0.0.1
    - localhost
    - `*.kube-etcd.kube-system.svc.cluster.local`
    - `kube-etcd-client.kube-system.svc.cluster.local`
  - etcd server peer port SAN:
    - boot etcd service IP
    - `*.kube-etcd.kube-system.svc.cluster.local`
    - `kube-etcd-client.kube-system.svc.cluster.local`
- [x] Render (etcd client's x509 CA, key, cert), (etcd server's client communication x509 CA, key, cert), (etcd server's peer communication x509 CA, key, cert) into secrets (https://github.com/kubernetes-incubator/bootkube/pull/586)
- [x] Auto-detect TLS assets in self-hosted and create secure etcd client as needed. (https://github.com/kubernetes-incubator/bootkube/pull/587)
- [x] Have option to start secure self-hosted etcd cluster and enable it by default (https://github.com/kubernetes-incubator/bootkube/pull/592)
  - Add static TLS with above secrets to etcd TPR
  - Change bootstrap etcd to use TLS
  - Change APIServer to use https to talk to etcd

**Comment by hongchaodeng** [comment]
@diegs @aaronlevy 
To continue discuss at https://github.com/kubernetes-incubator/bootkube/pull/583#discussion_r122050298,
I have updated the top comment to reflect what would be included in auto-generated certs.

**Comment by aaronlevy** [comment]
Are localhost and 127.0.0.1 necessary?

I'm unsure about only adding san's for the full dns name (`.kube-system.svc.cluster.local`) You don't actually have to use full domain. Would we want to have san's, for example, of:

kube-etcd-client
kube-etcd-client.kube-system
kube-etcd-client.kube-system.svc
kube-etcd-client.kube-system.cluster.local
*.kube-etcd
*.kube-etcd.kube-system
*.kube-etcd.kube-system.svc
*.kube-etcd.kube-system.cluster.local

Also, fwiw `cluster.local` could be changed (although we don't recommend this and it's hard-coded elsewhere too). Just mentioning, don't know that we care to support changes to it right now.

**Comment by hongchaodeng** [comment]
> Are localhost and 127.0.0.1 necessary?

Yes.
`localhost` is used by operator to do health-checking. It is also useful to do inspection when failure happens.
`127.0.0.1` is used by bootstrap control plane.

> I'm unsure about only adding san's for the full dns name (.kube-system.svc.cluster.local) You don't actually have to use full domain.

We need to use FQDN. This is an assumption made in etcd operator.
It is possible to make it configurable. I'm not sure we might need to try it out.

> Also, fwiw cluster.local could be changed (although we don't recommend this and it's hard-coded elsewhere too). Just mentioning, don't know that we care to support changes to it right now.

Definitely aware of this.
See https://github.com/coreos/etcd-operator/issues/1021
We can prioritize this work if needed.

**Comment by diegs** [comment]
> localhost is used by operator to do health-checking. It is also useful to do inspection when failure happens.
> 127.0.0.1 is used by bootstrap control plane.

Should you also add `::1` then for ipv6 compatibility? IIRC you are only supposed to use ip addresses to talk to etcd, otherwise we could just change bootkube to use `localhost`.

**Comment by hongchaodeng** [comment]
> Should you also add ::1 then for ipv6 compatibility?

Bootkube only relies on `127.0.0.1` in its templates at the moment.

> we could just change bootkube to use localhost.

I totally agree with that.
For my PR, I don't want to achieve too many goals in one PR. Ideally I would make incremental changes to achieve all the goals eventually.

**Comment by dghubble** [comment]
What's the rationale for having a separate client certificate / key pair for the etcd operator? Is that motivated by some sort of isolation concern?

**Comment by hongchaodeng** [comment]
@dghubble 
What do you mean by "separate"?

**Comment by hongchaodeng** [comment]
TLS is done.
