### ISSUE TITLE
Bootkube PR/e2e tests take 30-40minutes

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes-incubator/bootkube#590]
bootkube CI is too long. It spends 30-40 mins to wait for each pass.

It is too flaky. I'm sure some correct changes would take 4-5 times to get all green passes.

**Comment by xiang90** [comment]
I agree. We should put some serious effort to make the tests more reliable. Almost all PRs are blocked by flaky tests right now.

/cc @aaronlevy

**Comment by aaronlevy** [comment]
I'm going to close this as specific issues pertaining to flaky tests should be opened / tracked through resolution (vs generic "tests are flaky" issue).

**Comment by xiang90** [comment]
@aaronlevy 

tests taking too long is still an issue? and worth to track?

**Comment by aaronlevy** [comment]
Sure, updated title and re-opened.
