### ISSUE TITLE
bootstrap process workflow, controller/scheduler podaffinity issue

### ISSUE THREAD

**Issue by alekssaul** [kubernetes-incubator/bootkube#594]
My understanding of the current bootkube workflow is;

1. bootkube comes up with temporary control plane including short lived bootstrap pods for API server/controller/scheduler
1. [apiTest()](https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/bootkube/create.go#L137-L156) waits for API server to be ready
1. Then we inject the long lived assets (kube-dns, flannel, api server ds, controller deployment, scheduler deployment etc)

In a multi-master deployment, once step 2 is executed nodes still report themselves as "Not Ready". This is because Network/CNI is not yet deployed and functional, and kubelet is not reporting `Ready` back to the API server. Hence temporary Scheduler pod cannot make appropriate scheduling decisions to apply pod affinity rules. Step 3 takes over and all assets are deployed, nodes start reporting ready, however during the process Scheduler was not effective and multiple scheduler/controller pods end up getting scheduler on the master node where bootkube was executed.

I believe the process may be tweaked to (at a high level):
1. bootkube comes up with temporary control plane including short lived bootstrap pods for API server/controller/scheduler
1. [apiTest()](https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/bootkube/create.go#L137-L156) waits for API server to be ready
1. CNI/Flannel stack is deployed
1. New Function checks to make sure all registered nodes (or just master nodes) report ready
1. we inject the long lived assets (kube-dns, flannel, api server ds, controller deployment, scheduler deployment etc)

I've tested this via forking bootkube to stop the process once API server comes up and deployed a cluster with it;
```
kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                        READY     STATUS    RESTARTS   AGE       IP             NODE
kube-system   bootstrap-etcd-master0                      1/1       Running   0          2m        192.168.2.61   master0
kube-system   bootstrap-kube-apiserver-master0            1/1       Running   0          2m        192.168.2.61   master0
kube-system   bootstrap-kube-controller-manager-master0   1/1       Running   0          2m        192.168.2.61   master0
kube-system   bootstrap-kube-scheduler-master0            1/1       Running   0          2m        192.168.2.61   master0
```
```
kubectl get nodes
NAME      STATUS     AGE       VERSION
master0   NotReady   4m        v1.6.4+coreos.0
master1   NotReady   4m        v1.6.4+coreos.0
master2   NotReady   4m        v1.6.4+coreos.0
worker0   NotReady   4m        v1.6.4+coreos.0
```
Once the short lived control plane was up, I've deployed flannel
```
kubectl -n kube-system create -f ./generated/manifests/kube-flannel.yaml 
configmap "kube-flannel-cfg" created
daemonset "kube-flannel" created
```
```
kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                        READY     STATUS    RESTARTS   AGE       IP             NODE
kube-system   bootstrap-etcd-master0                      1/1       Running   0          5m        192.168.2.61   master0
kube-system   bootstrap-kube-apiserver-master0            1/1       Running   0          5m        192.168.2.61   master0
kube-system   bootstrap-kube-controller-manager-master0   1/1       Running   0          4m        192.168.2.61   master0
kube-system   bootstrap-kube-scheduler-master0            1/1       Running   0          4m        192.168.2.61   master0
kube-system   kube-flannel-2tzln                          2/2       Running   0          24s       192.168.2.71   worker0
kube-system   kube-flannel-5lnz3                          2/2       Running   0          24s       192.168.2.62   master1
kube-system   kube-flannel-9nh04                          2/2       Running   0          24s       192.168.2.63   master2
kube-system   kube-flannel-cstgh                          2/2       Running   0          24s       192.168.2.61   master0
```
The nodes reported status ready
```
 kubectl get nodes
NAME      STATUS    AGE       VERSION
master0   Ready     6m        v1.6.4+coreos.0
master1   Ready     6m        v1.6.4+coreos.0
master2   Ready     6m        v1.6.4+coreos.0
worker0   Ready     6m        v1.6.4+coreos.0
```
deployed controller manager and scheduler deployments
```
kubectl -n kube-system create -f ./generated/manifests/kube-scheduler.yaml 
deployment "kube-scheduler" created
kubectl -n kube-system create -f ./generated/manifests/kube-controller-manager.yaml 
deployment "kube-controller-manager" created
```
controller and scheduler long lived pods are scheduled to master1 and master2 servers as they have pod affinity rules
```
kubectl get pods --all-namespaces -o wide | grep -E 'kube-scheduler|kube-controller'
kube-system   bootstrap-kube-controller-manager-master0   1/1       Running             0          9m        192.168.2.61   master0
kube-system   bootstrap-kube-scheduler-master0            1/1       Running             0          9m        192.168.2.61   master0
kube-system   kube-controller-manager-2248957630-87gcv    0/1       ContainerCreating   0          3m        <none>         master1
kube-system   kube-controller-manager-2248957630-c4xr5    0/1       ContainerCreating   0          3m        <none>         master2
kube-system   kube-scheduler-1310662694-381nh             0/1       ContainerCreating   0          3m        <none>         master2
kube-system   kube-scheduler-1310662694-gdsgf             0/1       ContainerCreating   0          3m        <none>         master1
```

**Comment by aaronlevy** [comment]
This seems like a reasonable approach - but that being said, we've tended towards trying to keep as few coordination points as possible to reduce the internal complexity of bootkube. Although not a hard rule (e.g. we've considered it for other things like making sure DNS service IP doesn't get stolen: https://github.com/kubernetes-incubator/bootkube/issues/136 )

However, with that in mind, I still think we can get to the desired end state without necessarily needing to adding coordination points around CNI & master count.

The master-count can become problematic, for example, because then the assets you've generated might only "work" if you happen to deploy the cluster in a specific way.

Similarly with CNI, this might become more cumbersome to generically support other CNI plugins (calico, weave, etc.) - as their "coordination" points might actually differ.

Instead, the option we're moving forward with at the moment (in tectonic) is to use coordination around labels + required anti-affinity rules.

PR: https://github.com/coreos/tectonic-installer/pull/1129
Related discussion: https://github.com/coreos/tectonic-installer/issues/347#issuecomment-307177869

This would work for supporting both single master and multi-master installations - and essentially allows for co-located pods during version skew (e.g. an "update"), but requires anti-affinity otherwise (so will force replica pods to be spread across hosts).

**Comment by alekssaul** [comment]
Missed the latest updates on this topic, thanks @aaronlevy .

Gave 1129 a try, initial provisioning placement looks great to me;
```
kubectl get pods --all-namespaces -o wide | grep -E 'kube-scheduler|kube-controller'
kube-system       kube-controller-manager-2150839064-68f4n   1/1       Running             1          5m        10.2.3.4       master0
kube-system       kube-controller-manager-2150839064-wsxpl   1/1       Running             0          5m        10.2.2.2       master1
kube-system       kube-scheduler-3187535986-qjd0j            1/1       Running             0          5m        10.2.2.3       master1
kube-system       kube-scheduler-3187535986-x6s2f            1/1       Running             0          5m        10.2.3.2       master0
``` 

I am good to close this
