### ISSUE TITLE
Readme instructions for `go get` don't work

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#602]
Not sure when they ever did, but I don't think we expect this to be `go get` able.

**Comment by radhikapc** [comment]
thanks :-)

**Comment by radhikapc** [comment]
more issues:
`Radhikas-MBP:bin pcradhika$ make install
make: *** No rule to make target `install'.  Stop.`

**Comment by ericchiang** [comment]
There aren't any instructions in the README for `go get`

/assign
/close
