### ISSUE TITLE
CI matrix is larger now that we have Calico option

### ISSUE THREAD

**Issue by pbx0** [kubernetes-incubator/bootkube#605]
Currently our CI runs a set of e2e tests with 2 cluster configurations: with self-hosted etcd and without. We have a new Calico flag that has been added. So technically we should have 4 CI jobs kick off on each PR for each cluster configuration. I propose that maybe we just do 3 since maybe its not so important that calico is tested both with self-hosted etcd and without. So we could have:
```
SelfHostEtcd:true Calico: false
SelfHostEtcd:true Calico: true
SelfHostEtcd: false Calico: false
```
The Calico e2e test is going to have to make it it skips when calico is not used. One reason in favor of not doing the entire matrix is that if you have any probability of flakiness at all, running more of the same tests increases your likely hood of hitting the flake.

**Comment by pbx0** [comment]
I believe it got set to on by default to make the new network policy tests pass. I should have made this issue a stopper for reviewing/merging looking back. So at minimum we need the network policy tests to self-skip in absence of Calico and then turn calico back to false by default or set explicitly in CI. Then we could add a third test later to keep those tests getting exercised. Maybe gate it under `coreosbot run network tests`

**Comment by aaronlevy** [comment]
Closing based on https://github.com/kubernetes-incubator/bootkube/pull/639 - which disables test if calico is not running
