### ISSUE TITLE
etcd TLS paths are inconsistent or disorganized

### ISSUE THREAD

**Issue by dghubble** [kubernetes-incubator/bootkube#611]
When experimental self-hosted etcd is enabled, there are some particular expectations about the naming and structure of various etcd certificates and keys in code. For downstreams doing their own rendering (like Tectonic) this could be inconvenient:

- Inconsistent suffix ".crt" or ".key" vs ".pem"
- Undocumented uses of each certificate pair type
- Some of these paths are hard requirements (coded into bootkube recovery), some are not

In practice, downstreams seem to be creating a CA pair, peer pair, and client pair and copying them into some of the different paths. That seems less than ideal for all involved.

```
AssetPathEtcdCA                         = "tls/etcd-ca.crt"
AssetPathEtcdClientCert                 = "tls/etcd-client.crt"
AssetPathEtcdClientKey                  = "tls/etcd-client.key"
AssetPathEtcdPeerCert                   = "tls/etcd-peer.crt"
AssetPathEtcdPeerKey                    = "tls/etcd-peer.key"
AssetPathSelfHostedOperatorEtcdCA       = "tls/operator/etcd-ca-crt.pem"
AssetPathSelfHostedOperatorEtcdCert     = "tls/operator/etcd-crt.pem"
AssetPathSelfHostedOperatorEtcdKey      = "tls/operator/etcd-key.pem"
AssetPathSelfHostedEtcdMemberClientCA   = "tls/etcdMember/client-ca-crt.pem"
AssetPathSelfHostedEtcdMemberClientCert = "tls/etcdMember/client-crt.pem"
AssetPathSelfHostedEtcdMemberClientKey  = "tls/etcdMember/client-key.pem"
AssetPathSelfHostedEtcdMemberPeerCA     = "tls/etcdMember/peer-ca-crt.pem"
AssetPathSelfHostedEtcdMemberPeerCert   = "tls/etcdMember/peer-crt.pem"
AssetPathSelfHostedEtcdMemberPeerKey    = "tls/etcdMember/peer-key.pem"
```

cc @hongchaodeng per earlier slack discussion and @s-urbaniak

**Comment by aaronlevy** [comment]
Agree we should get this more consistent.

Also a little confused by all the certs. Is there a reason that the operator gets its own set of certs (is it not just a client of etcd?) and why do we generate etcd client/peer certs, then generate different etcd/peer certs for an etcd member?

**Comment by hongchaodeng** [comment]
>  Is there a reason that the operator gets its own set of certs (is it not just a client of etcd?)

Ideally, operator has its own cert, which is different from apiserver's. This can be reduced to couple apiserver and operator's cert. But I'm also afraid of that coupling. Do you want that? Is it a big problem have another cert?

> why do we generate etcd client/peer certs, then generate different etcd/peer certs for an etcd member?

These are required to bootstrap secure etcd cluster.

**Comment by diegs** [comment]
I think it's clearer to have separate copies of things for each component, since it's easier to reason about the dependencies for each (even if the contents are the same).

**Comment by xiang90** [comment]
@diegs 

agree.

**Comment by dghubble** [comment]
In bootkube render, the same etcd client certs are copied for both apiserver and operator, right?
 https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/tls.go#L192

I'm not opposed to the separate cert design, I've faithfully reproduced what bootkube render does in https://github.com/coreos/bootkube-terraform which is used for matchbox examples. I would consider the inconsistent suffixes something to be addressed.

I noticed Tectonic implemented creating these certs differently (may affect recovery) and opened a separate issue for that  https://github.com/coreos/tectonic-installer/issues/1186

**Comment by aaronlevy** [comment]
I agree about the suffixes. Let's get those in sync across all assets. I could go either way `-crt.pem` or `.crt` -- Does anyone have any preference?

Also @hongchaodeng @xiang90 can you validate if the tectonic implementation needs to be changed?

**Comment by aaronlevy** [comment]
Actually given that these are new certs, I'd probably prefer to change them to be more in-line with our existing generated certs (`.crt` & `.key`).

**Comment by dghubble** [comment]
@aaronlevy I'd agree about `.crt` and `.key`, because the existing certs are used in some locksmithd configs on some clusters and I'd prefer to leave those unchanged.

**Comment by aaronlevy** [comment]
@hongchaodeng can you expand on the difference between `AssetPathEtcdPeerKey/Cert` and `AssetPathSelfHostedEtcdMemberPeerKey/Cert`. I'm not clear on why two different peer certs are required to bootstrap the cluster.

**Comment by hongchaodeng** [comment]
> I'm not clear on why two different peer certs are required to bootstrap the cluster.

No. Only one exist.

`AssetPathEtcdPeerKey` is for non-self-hosted case.
`AssetPathSelfHostedEtcdMemberPeerKey` is used for self-hosted case. Self-hosted certs naming needs to following some rules described in https://github.com/coreos/etcd-operator/blob/master/doc/user/cluster_tls.md .

**Comment by aaronlevy** [comment]
@hongchaodeng  So why do we define both? We are generating this data - and only one is being used, why not just have a 'peer' key/cert? What is the point of both (I'm trying to understand the complexity here - because we'll need to explain it in docs.

**Comment by hongchaodeng** [comment]
@aaronlevy 
The definite answer is we don't need to define both. But to keep one, we can only keep `AssetPathSelfHostedEtcdMemberPeerKey`.

**Comment by diegs** [comment]
Why only `AssetPathSelfHostedEtcdMemberPeerKey`? Do you want to drop support for non-hosted etcd + TLS?

Why not just use `AssetPathEtcdPeerKey` since it's shorter and can apply to both..?

**Comment by aaronlevy** [comment]
So we could effectively reduce this set to:

```
AssetPathEtcdCA                         = "tls/etcd-ca.crt"
AssetPathEtcdClientCert                 = "tls/etcd-client.crt"
AssetPathEtcdClientKey                  = "tls/etcd-client.key"
AssetPathEtcdPeerCert                   = "tls/etcd-peer.crt"
AssetPathEtcdPeerKey                    = "tls/etcd-peer.key"
AssetPathSelfHostedOperatorEtcdCA       = "tls/operator/etcd-ca-crt.pem"
AssetPathSelfHostedOperatorEtcdCert     = "tls/operator/etcd-crt.pem"
AssetPathSelfHostedOperatorEtcdKey      = "tls/operator/etcd-key.pem"
```

**Comment by hongchaodeng** [comment]
See https://github.com/kubernetes-incubator/bootkube/issues/611#issuecomment-311153186 .

>  Self-hosted certs naming needs to follow some rules described in https://github.com/coreos/etcd-operator/blob/master/doc/user/cluster_tls.md .

**Comment by hongchaodeng** [comment]
I think I haven't explained clearly enough.
So there are two options here:
1. have two separate paths for self-hosted and non-self-hosted, which is what we've done.
2. converge them. But they need to follow self-hosted path due to some naming constraint. Thus drop the non-self-hosted paths.

**Comment by hongchaodeng** [comment]
Two things that can be changed:
1. var name like `AssetPathSelfHostedEtcdMemberPeerKey`.
2. cert dir, like `tls/whatever`.

**Comment by dghubble** [comment]
@hongchaodeng I think that page you linked shows the files etcd-operator expects to find, which are mounted via Kubernetes secrets, so it constrains the field names used in the secrets and not the organization of `bootkube render` files

**Comment by hongchaodeng** [comment]
@dghubble 
That's right. The current `secretFromAssets()` func assumes the file basename to be the key. Would you like to refactor it and make this flexible?

**Comment by aaronlevy** [comment]
This is kind of why I wanted https://github.com/coreos/etcd-operator/issues/552 -- this model where the podspec is hard-coded (including filepaths) makes integration with other tools really fragile.

**Comment by dghubble** [comment]
I see. The bootkube `secretFromAssets()` behavior seems reasonable to me already then and approach was need to conform to the key names coded inside etcd-operator.

**Comment by aaronlevy** [comment]
I might just prefer that all of this complexity be contained in etcd-operator specific utilities. This is essentially adding a bunch of new assets to work around hard-coded names. I'm thinking I'd rather that complexity end up in self-contained code, rather than implicitly in file structures.

**Comment by hongchaodeng** [comment]
To sum up offline slack discussion, we will have only one set of assets:
```
etcd-client.key
etcd-client.crt
etcd-peer.key
etcd-peer.crt
etcd-ca.key
etcd-ca.crt
```
means to unify both self-hosted and non-self-hosted paths.

**Comment by xiang90** [comment]
> I might just prefer that all of this complexity be contained in etcd-operator specific utilities. This is essentially adding a bunch of new assets to work around hard-coded names. 

All the static TLS related things are already pretty much self contained in etcd operator. etcd operator is not designed to be smart and try to understand how external users want to name or organize the key/cert. Instead, external users must follow the format defined in etcd operator. Also, I cannot see the benefits to make it flexible. 

External tools, like bootkube, can do whatever they want internally to hide the inconsistency from the user. 

>  I'm thinking I'd rather that complexity end up in self-contained code, rather than implicitly in file structures.

This might be a reasonable request, but I am not sure now. The data point is too few. You can open an issue in etcd operator about this specific problem: allow users to define the path/filename for key/cert in the secret. But I do not feel this will be a priority for us to do right now.

**Comment by aaronlevy** [comment]
> external users must follow the format defined in etcd operator right now

Ultimately I agree with this. We have to conform to the upstream tool's requirements - and in this case that is hard-coded paths. It's just somewhat unfortunate / makes communicating how to properly create tls assets more complex (if static, do X - if self-hosted do Y).

> I'm thinking I'd rather that complexity end up in self-contained code, rather than implicitly in file structures.

I actually meant this as a change in bootkube itself. Rather than relying on render creating assets that directly match the expected etcd-operator format, we continue rendering the same set of assets we have been, but when combining those into a secret, we transform them into the format etcd-operator expects.

This allows decoupling the expectations of etcd-operator from implicit file paths, and instead puts the expectations in code.

The downside is that we end up needing to do this same translation for things like `bootkube recover` -- where we need to read the data out of secret, then translate it into our "expected" local format -- which is very much not ideal either.

**Comment by s-urbaniak** [comment]
@hongchaodeng It seems there is a consensus now on the TLS asset directory/file layout as outlined in https://github.com/kubernetes-incubator/bootkube/issues/611#issuecomment-311202308 which (I think) reflects the current setup used in Tectonic.

To make it more concrete can I assume the following cert usage patterns?

```
etcd-client.key
- api-server via --etcd-keyfile
- non-self-hosted etcd via --key-file
- self-hosted bootstrap etcd via --key-file and host-mount
- "etcd-member-client-tls" secret via client-key.pem
- "etcd-operator-client-tls" secret via etcd-key.pem

etcd-client.crt
- api-server via --etcd-certfile
- non-self-hosted etcd via --cert-file
- self-hosted bootstrap etcd via --cert-file and host-mount
- "etcd-member-client-tls" secret via client-crt.pem
- "etcd-operator-client-tls" secret via etcd-crt.pem

etcd-peer.key
- non-self-hosted etcd via --peer-key-file
- self-hosted bootstrap etcd via --peer-key-file and host-mount
- "etcd-member-peer-tls" secret via peer-key.pem

etcd-peer.crt
- non-self-hosted etcd via --peer-cert-file
- self-hosted bootstrap etcd via --peer-cert-file and host-mount
- "etcd-member-peer-tls" secret via peer-crt.pem

etcd-ca.key
(actually unused)

etcd-ca.crt
- api-server via --etcd-cafile
- non-self-hosted etcd via --peer-trusted-ca-file and --trusted-ca-file
- self-hosted bootstrap etcd via --peer-trusted-ca-file and --trusted-ca-file and host-mount
- "etcd-member-client-tls" secret via client-ca-crt.pem
- "etcd-operator-client-tls" secret via etcd-ca-crt.pem
- "etcd-member-peer-tls" secret via peer-ca-crt.pem
```

**Comment by hongchaodeng** [comment]
@s-urbaniak 
Mostly true.
Operator will have its own asset of certs:
```
AssetPathSelfHostedOperatorEtcdCA       = "tls/operator/etcd-ca-crt.pem"
AssetPathSelfHostedOperatorEtcdCert     = "tls/operator/etcd-crt.pem"
AssetPathSelfHostedOperatorEtcdKey      = "tls/operator/etcd-key.pem"
```

**Comment by aaronlevy** [comment]
Just had an in-person conversation with @hongchaodeng & @xiang90 about this:

The plan is to make the expected tls assets in the etcd-operator TPR more closely match what is expected by etcd itself. An example of a mismatch currently is that etcd expects 2 sets of certs:

```
--trusted-ca-file=
--key-file=
--cert-file=

--peer-trusted-ca-file=
--peer-key-file=
--peer-cert-file=
```

Whereas the etcd-operator TPR expects:

```
# For equivalent of --trusted-ca-file / --cert-file / --key-file
client-ca-crt.pem
client-crt.pem
client-key.pem

# For equivalent of an etcd client (e.g. operator):
etcd-ca-crt.pem
etcd-crt.pem
etcd-key.pem
```

This could become confusing because the `client-crt.pem` actually should just be a cert with server usage (and is not used as a client cert). Then the `etcd-crt.pem` is actually used as the client cert to contact etcd(by etcd-operator).

So moving forward the goals is to make the certs/secrets expected by etcd-operator - then other asset rendering tools (bootkube, tectonic, etc.) should adhere to this new format (but can choose what / how to generate their own certs). Potentially could look something like:

```
# Generate server keypair, only has server ExtUsage
# will be used by etcd --key-file / --cert-file
etcd-server.key
etcd-server.crt
etcd-ca # optional - could be same as cluster wide CA

# Generate peer keypair, has both server/client ExtUsage
# will be used by etcd --peer-key-file / --peer-cert-file
etcd-peer.key
etcd-peer.crt
etcd-peer-ca # optional - could be same as cluster wide CA

# Generate client keypair, only has client ExtUsage
# Used by apiserver to contact etcd (optionally used by etcd-operator as well)
etcd-client.key
etcd-client.crt
etcd-client-ca # optional - could be same as cluster wide CA

# (optional) Generate another client key for exclusive use by etcd-operator as client)
operator-client.key
operator-client-crt
```

In bootkube's case to keep everything simple, we would ideally generate the following assets (but other tools like tectonic could be more specific:

* cluster wide CA
* etcd-peer keypair
* etcd-server keypair
* etcd-client keypair.

Then all trusted CAs would be set to the cluster-wide CA. Etcd would be started with peer/cert certs. apiserver would get client cert, and the etcd-operator would also get the same client cert.

Let me know if that captures what you were thinking at @hongchaodeng @xiang90

Also last night (before this discussion) I put together a strawman PR to try and simplify some of the generation in bootkube, but this will need to be updated based on etcd-operator secret changes: https://github.com/kubernetes-incubator/bootkube/pull/614

**Comment by hongchaodeng** [comment]
In etcd operator side, the naming is gonna be simplified and more aligned with official docs as put in https://github.com/coreos/etcd-operator/pull/1227/files .

The corresponding in secrets would become:
```
peer.crt
peer.key
peer-ca.crt

server.crt
server.key
server-ca.crt

etcd.crt
etcd.key
etcd-ca.crt
```

**Comment by hongchaodeng** [comment]
We also need to write a formal doc for the certs assumption to run `bootkube start/recover`. Otherwise how could consumers of bootkube like @s-urbaniak mentioned above to know what to put into other render tool?
