### ISSUE TITLE
Build failure ../go/src/github.com/kubernetes-incubator/bootkube/pkg/asset/tls.go:216: etcdServers[i].Hostname undefined (type *url.URL has no field or method Hostname)

### ISSUE THREAD

**Issue by f0** [kubernetes-incubator/bootkube#641]
I got this failure with 0.5 and master

../go/src/github.com/kubernetes-incubator/bootkube/pkg/asset/tls.go:216: etcdServers[i].Hostname undefined (type *url.URL has no field or method Hostname)

**Comment by aaronlevy** [comment]
@f0 what version of go are you using? We are only testing against go `v1.8.x`.

**Comment by f0** [comment]
@aaronlevy   works with 1.8, thx
