### ISSUE TITLE
Recovery: must have clean docker/container state on recovery machine

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#651]
Copied from: https://github.com/kubernetes-incubator/bootkube/issues/612

Both docker state, active manifest and etcd state need to be cleaned up. Kubelet needs to be restarted.

We could add a `bootkube recovery cleanup` subcommand, or maybe add cleanup process into the bootkube recovery directly?

**Comment by robszumski** [comment]
In favor of adding it to the command itself, as we know you _need_ to do it.

**Comment by aaronlevy** [comment]
I'm not super clear on the steps needed, but if we're blowing away a bunch of host paths, I'd probably prefer we wrap it in a shell script to be super transparent about what it is doing. Could be convinced otherwise - but an `rm -rf /var/etcd` (that I'm seeing discussed in related issues) scares me a bit.
