### ISSUE TITLE
permission-problem rbac+psp

### ISSUE THREAD

**Issue by strowi** [kubernetes-incubator/bootkube#660]
Hi,

related to https://github.com/kubernetes/kubernetes.github.io/issues/4457#issuecomment-317485950
how is the controller-manager connection to the api-server? via secured port/rbac?

regards,
strowi

**Comment by aaronlevy** [comment]
The controller-manager is being run as a pod, so it uses a service-account to connect to the api-server (via secured port). Unless configured differently, it is using the default service-account for the kube-system namespace (but it doesn't necessarily have to - you can change that in the manifest).

**Comment by aaronlevy** [comment]
Per the upstream issue - I'm not immediately sure the needs of pod security policies (we don't have them enabled by default). However, this is something I'd like to support - so it might just be some additional digging on this feature specifically.

**Comment by strowi** [comment]
so to enable rbac + psps it might suffice to add `- --use-service-account-credentials` to the kube-controller-manager.yaml to restrict service-accounts?
The main use for us would be to prevent the use of privileged containers/ hostPaths etc.. 
everything that could destroy a node / the control-pane...

**Comment by aaronlevy** [comment]
We may also need to lock the KCM down further, however (just skimming https://github.com/kubernetes/kubernetes.github.io/pull/4423/files#r128599107)

**Comment by strowi** [comment]
Ok, so far i haven't had any luck adding `--use-service-account-credentials' , it seems other permissions are needed then..

**Comment by klausenbusk** [comment]
@strowi Did you ever figure this out?

**Comment by strowi** [comment]
tbh we ran into some other problems with psp, and decided to remove them altogether.
But maybe this has changed in more recent version..

**Comment by klausenbusk** [comment]
@aaronlevy Would it make sense to enable `PodSecurityPolicy` as default, or is it out of scope? From what I understand, it would require enabling the `PodSecurityPolicy` admission controller, starting `kube-controller-manager` with `--use-service-account-credentials` and adding a default `PodSecurityPolicy`.

Something like: https://github.com/coreos/tectonic-installer/pull/2102/ , but we don't need multi `PodSecurityPolicy`, as least not for a start.

**Comment by aaronlevy** [comment]
I do think that it is in scope - and something I'd like to have enabled. Opened an issue specifically about that to keep discussion in one place: https://github.com/kubernetes-incubator/bootkube/issues/782

**Comment by xvzup** [comment]
Today I tried what is described in this thread and it is working on a 1.8.5 cluster (bootkube v0.9.1)

The changes are described above, but this is what I did:

kube-apiserver
- Admission controller PodSecurityPolicy enabled
- - --runtime-config=extensions/v1beta1/podsecuritypolicy=true

kube-controller-manager:
- - --use-service-account-credentials

**Comment by redbaron** [comment]
FYI, I have it working without `-runtime-config=extensions/v1beta1/podsecuritypolicy=true`

**Comment by colemickens** [comment]
Looks like this is either addressed, or covered in a more specific Issue. Closing.
