### ISSUE TITLE
CNI: Include "portmap" plugin by default

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes-incubator/bootkube#662]
https://github.com/kubernetes-incubator/bootkube/pull/247 stated:
> There is a known issue with using CNI plugins that setting a hostPort on a pod will no longer work. This is because the hostPort relies on docker to configure the host -> pod bridge, but in the case of CNI network plugins, docker does not know about the pod, network and the CNI plugin is used instead.
>
> See upstream issues for more information:
> kubernetes/kubernetes#23920
> kubernetes/kubernetes#31307

That doesn't seems to be the case [anymore](https://github.com/coreos/flannel/issues/772), at least not with new [enough CNI binaries](https://github.com/containernetworking/plugins/issues/43#issuecomment-315690123).

So I propose that you update the CNI binaries (when a new stable release is available) and enable the `portmap` plugin as default.

BTW: The current CNI binaries seems to live in [quay.io/coreos/flannel-cni:0.1.0](https://github.com/kubernetes-incubator/bootkube/blob/532846591632317e72d19f5b03b1faf5204f9b6f/pkg/asset/images.go#L8) which I can't find the source for?

**Comment by aaronlevy** [comment]
@klausenbusk the source of the flannel-cni image is: https://github.com/coreos/flannel-cni

**Comment by klausenbusk** [comment]
I just get a 404, is it private?

Den 27. jul. 2017 2.05 AM skrev Aaron Levy <notifications@github.com>:

@klausenbusk<https://github.com/klausenbusk> the source of the flannel-cni image is: https://github.com/coreos/flannel-cni

**Comment by aaronlevy** [comment]
@klausenbusk woops, should be public now.

**Comment by klausenbusk** [comment]
CNI [v0.6.0](https://github.com/containernetworking/cni/releases/tag/v0.6.0) is out, so we just need a new flannel-cni release with v0.6.0 ([PR](https://github.com/coreos/flannel-cni/pull/3)), bumping bootkube to the new version, changing the `template` (?) and some testing.

**Comment by klausenbusk** [comment]
PR opened: https://github.com/coreos/flannel-cni/pull/5
