### ISSUE TITLE
support of etcd-operator v0.5.0

### ISSUE THREAD

**Issue by rimusz** [kubernetes-incubator/bootkube#666]
when the new version of bookube with etcd-operator v0.5.0 is planned?

**Comment by rimusz** [comment]
ping @aaronlevy

**Comment by aaronlevy** [comment]
@hongchaodeng @sym3tri

**Comment by hongchaodeng** [comment]
@rimusz 
Can you send a PR ?

**Comment by rimusz** [comment]
heh, it is just such simple change, but I can of course :)

**Comment by klausenbusk** [comment]
There is already a open PR: https://github.com/kubernetes-incubator/bootkube/pull/668

**Comment by klausenbusk** [comment]
I just took a stab on this, but I need a bit of help.

Firstly I can't figure out how to bump vendor etcd-operator to v0.5.0, the instructions in [RELEASING.md](./RELEASING.md) isn't working:
```
$ nano glide.yaml (change to v0.5.0)
$ make vendor
[ERROR]	--strip-vendor cannot be used without --strip-vcs
make: *** [Makefile:57: vendor] Error 1
```
Playing around with `glide` it change a lot of files, which seems unrelated to `etcd-operator`, I'm really not sure about what to do.

Secondly, I'm not sure if this is correct: https://github.com/kubernetes-incubator/bootkube/pull/686/files#diff-7bfb0002873c32485e88c09de5a2d1b8R124 and what I should change this to: https://github.com/kubernetes-incubator/bootkube/pull/686/files#diff-7bfb0002873c32485e88c09de5a2d1b8R161 .

**Comment by hongchaodeng** [comment]
@klausenbusk 
The rest path of CRD api is:
```
/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions
```

CRD api types could be found in:
https://github.com/kubernetes/apiextensions-apiserver

**Comment by klausenbusk** [comment]
@hongchaodeng Ready for review, if you have some time: https://github.com/kubernetes-incubator/bootkube/pull/686

I have tested with `hack/quickstart/init-master.sh` and `bootkube recover` and it seems to work without any issues.

**Comment by aaronlevy** [comment]
fixed in https://github.com/kubernetes-incubator/bootkube/pull/686
