### ISSUE TITLE
Using own SSL-Certificates / Certificate-Exchange

### ISSUE THREAD

**Issue by strowi** [kubernetes-incubator/bootkube#669]
Hi,

since the default certificates created by bootkube are only valid 1y, i was trying to replace them with my own, but seem to fail somehow when authenticating during bootstrap.

Here is what i did:
- 10.243.0.0/16 is the service-cidr
- removed all *crt *pub files in the tls-folder

- create new `apiserver.crt`:
```
~> cat > openssl_apiserver.cnf <<EOF
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster.local
DNS.5 = api.example.com

IP.1 = 10.243.0.1
EOF

~> openssl req -new -key apiserver.key -out apiserver.csr -subj "/O=kube-master, CN=kube-apiserver" -config openssl_apiserver.cnf
~> openssl x509 -req -in apiserver.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out apiserver.crt -days 3650 -extensions v3_req -extfile openssl_apiserver.cnf
```

same thing for the `kubelet.crt`:
```
~> cat > openssl_kubelet.cnf <<EOF
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
extendedKeyUsage       = serverAuth, clientAuth
keyUsage               = critical,digitalSignature, keyEncipherment
EOF

~> openssl req -new -key kubelet.key -out kubelet.csr -subj "/O=system:masters, CN=kubelet" -config openssl_kubelet.cnf
~> openssl x509 -req -in kubelet.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out kubelet.crt -days 3650 -extensions v3_req -extfile openssl_kubelet.cnf
```

And then i did replace the bas64-encoded parts in 
- auth/kubeconfig 
- manifests/kube-apiserver-secret.yaml
- kube-controller-manager-secret.yaml

But on bootkube-start i get the following authentication error:
```
Starting temporary bootstrap control plane...
Waiting for api-server...
W0802 07:14:31.346322       1 create.go:31] Unable to determine api-server readiness: API Server http status: 0
W0802 07:14:36.343600       1 create.go:31] Unable to determine api-server readiness: API Server http status: 0
W0802 07:14:41.343842       1 create.go:31] Unable to determine api-server readiness: API Server http status: 0
W0802 07:14:46.343672       1 create.go:31] Unable to determine api-server readiness: API Server http status: 0
W0802 07:14:51.343575       1 create.go:31] Unable to determine api-server readiness: API Server http status: 0
W0802 07:14:56.343890       1 create.go:31] Unable to determine api-server readiness: API Server http status: 0
W0802 07:15:01.343832       1 create.go:31] Unable to determine api-server readiness: API Server http status: 0
W0802 07:15:06.367023       1 create.go:31] Unable to determine api-server readiness: User "system:anonymous" cannot get namespaces in the namespace "kube-system". (get namespaces kube-system)
W0802 07:15:11.344025       1 create.go:31] Unable to determine api-server readiness: User "system:anonymous" cannot get namespaces in the namespace "kube-system". (get namespaces kube-system)
````

Which i believe is a problem with the kubelet-cert?

Am i missing some cert-option or another important step?

Is there an alternative easy way to replace the certificates?

thx in advance,
Roman

**Comment by klausenbusk** [comment]
`bootkube render` has a [`--ca-certificate-path`](https://github.com/kubernetes-incubator/bootkube/pull/42) switch, so I think (but I'm not sure at all) that you can just run:
```
bootkube render --asset-dir=foo --ca-certificate-path=<path to ca.crt> --ca-private-key-path=<path to ca.key> --api-servers=<something>
for f in $(foo/manifests/{*-secret,etcd*-tls}.yaml; do
    kubectl apply -f $f
done
```
I'm also looking into this, as the certificates is gonna expire at some point and I need to create some doc.

**Comment by strowi** [comment]
thx, this is a good start. in addition the ca.crt needs to be copied to /etc/kubernetes/ca.crt.
But that should be  all i guess. 
Not sure though, if/how the secrets are automatically being re-read

**Comment by ericchiang** [comment]
I don't inherently see anything wrong with those TLS assets but it's hard to tell without logs from your API server.

Closing for now. Consider taking a look at:

https://github.com/coreos/tectonic-installer/tree/master/modules/tls/kube/self-signed

Or:

https://github.com/poseidon/terraform-render-bootkube/blob/master/tls-etcd.tf
https://github.com/poseidon/terraform-render-bootkube/blob/master/tls-k8s.tf
