### ISSUE TITLE
Calico network policy daemonset cannot be removed

### ISSUE THREAD

**Issue by dghubble** [kubernetes-incubator/bootkube#698]
Found a reproducible way to cause what I experienced in https://github.com/kubernetes-incubator/bootkube/pull/694#issuecomment-325754554

We're not deploying Calico Network Policy in a way where it can be removed cleanly. It drops its own CNI configs on hosts which actually seem to take precedence over the flannel CNI config. Removing the calico daemonset after this point causes new pods to fail to create network namespaces.

UPDATE: Removing Calico network policy requires manually removing a file on each host.

## Reproduce

First, deploy a cluster with calico network policy enabled. You can do this at cluster creation time or by applying the manifests to an existing cluster. Later, delete the calico daemonset (perhaps you don't want network policy for some reason). All *looks* normal. Launch some new pods and observe that they're stuck in ContainerCreating.

```
1m            1m              1       kubelet, sm-x8dtu2.us-west1-m.dghubble.io                       Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "default-token-7db68" 
  1m            16s             8       kubelet, sm-x8dtu2.us-west1-m.dghubble.io                       Normal          SandboxChanged          Pod sandbox changed, it will be killed and re-created.
  1m            15s             9       kubelet, sm-x8dtu2.us-west1-m.dghubble.io                       Warning         FailedSync              Error syncing pod
```

The Kubelet finds CNI configs in `--cni-config-dir` is `/etc/kubernetes/cni/net.d`. After Calico is deployed on a cluster, the `calico` plugin is installed and so is a Calico CNI config (/etc/kubernetes/cni/net.d/10-calico.yaml). Checking logs, we see Kubelet seems to be calling calico to setup the network.

```
Aug 30 21:17:49 sm-x8dtu2.us-west1-m.dghubble.io kubelet-wrapper[6115]: time="2017-08-30T21:17:49Z" level=debug msg="Performing 'Get' for WorkloadEndpoint(node=sm-x8dtu2.us-west1-m.dghubble.io, orchestrator=k8s, workload=ingress.ingress-controller-public-3120200946-skdd2, name=eth0)"
Aug 30 21:17:49 sm-x8dtu2.us-west1-m.dghubble.io kubelet-wrapper[6115]: E0830 21:17:49.640629    6115 cni.go:312] Error deleting network: connection is unauthorized
Aug 30 21:17:49 sm-x8dtu2.us-west1-m.dghubble.io kubelet-wrapper[6115]: E0830 21:17:49.641458    6115 remote_runtime.go:114] StopPodSandbox "3450066ab9070003d37f6fb8126364066b780da98a17cb66e5d96a91dcdaa254" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "ingress-controller-public-3120200946-skdd2_ingress" network: connection is unauthorized
```

This will not recover.  SSH to a node and remove `/etc/kubernetes/cni/net.d/10-calico.conf`. Within a minute, that node can schedule pods again. Repeat.

```
sudo rm /etc/kubernetes/cni/net.d/10-calico.conf
```

### Underlying Cause

Talking to @squeed, it looks like the Kubelet is sorting CNI configs and picking the first one, which happens to be `10-calico.conf` instead of `10-flannel.conf`.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/cni/cni.go#L107

### Thoughts

* We should aim for Calico Network Policy manifests to be easily added/removed. They're not essential to the control plane, and more like optional addon manifests.
* Do we really need Calico's CNI config to take over to get Network Policy?
* If required, we need to have a note about this somewhere. Its rather dangerous it leaves the cluster *appearing* ok, until you try to create new pods. Its a recipe for an outage.

cc @aaronlevy @squeed

**Comment by squeed** [comment]
Some more random thoughts, oh boy:

* The kubelet CNI-network-selection is racy and frustrating, but it's hard to see how to fix it and keep backwards compat
* Because kubelet is constantly re-scanning for networks, we get ourselves in a strange situation where a pod can be created with network A and deleted with network B
* Therefore, It is essentially impossible to roll out calico network policy on a running cluster.

It's possible I'm missing something, and the Calico CNI plugin will handle a DELETE for a container that flannel ADD'ed. But this is extremely fragile, and I'd be scared to rely on it.

**Comment by dghubble** [comment]
> Therefore, It is essentially impossible to roll out calico network policy on a running cluster.

I agree, this seems dangerous - I'm worried about rolling this out on my clusters as well. But I don't get the "running cluster" distinction. If calico network policy can't safely be kubectl added to a running cluster, its not really safe for bootkube to have it in its initial manifests either, since there's not a clear line between bootstrapping and regular stages. I still think its useful to show how to add calico network policy to a cluster using flannel, if we can call out the current bugs / dangers.

> We should aim for Calico Network Policy manifests to be easily added/removed. They're not essential to the control plane, and more like optional addon manifests.

If bootkube's goal is to bootstrap a minimal control plane, there's not much reason Calico network policy needs to be a part of the bootkube repo. In the same way bootkube expects users to add an Ingress controller to make use of Ingress resources, bootkube should expect users to add Calico network policy to make use of NetworkPolicy resources. Calico would only be part of control plane bootstrapping if bootkube offered Calico for connectivity (as an alternative to flannel).

> Do we really need Calico's CNI config to take over to get Network Policy?

Apparently yes, this is how the policy directives are given to Calico.

**Comment by squeed** [comment]
> If calico network policy can't safely be kubectl added to a running cluster, its not really safe for bootkube to have it in its initial manifests either, since there's not a clear line between bootstrapping and regular stages.

I was a bit careless in my definition of "running cluster." In reality, it means "a cluster with pods using an existing CNI configuration." So it would be safe to deploy Calico to a fresh cluster as the *first* CNI plugin. However, Calico's need to be the controlling CNI plugin makes it very hard to deploy - you can't deploy it on a worker that already has active pods with connectivity through Flannel's CNI plugin.

**Comment by sstarcher** [comment]
After updating to the lastest(v0.6.2) bootkube I believe this is causing me an issue with recovering a full self-hosted etcd control plane.  I was able to recover using 0.5.1 with the older calico setup.

* kubelet
```
Sep 14 13:19:58 ip-10-0-3-133 kubelet-wrapper[21633]: I0914 13:19:58.815098   21633 kuberuntime_manager.go:457] Container {Name:kube-controller-manager Image:quay.io/coreos/hyperkube:v1.7.5_coreos.0 Command:[./hyperkube controller-manager --allocate-node-cidrs=true --configure-cloud-routes=false --cluster-cidr=10.2.0.0/16 --root-ca-file=/etc/kubernetes/secrets/ca.crt --service-account-private-key-file=/etc/kubernetes/secrets/service-account.key --leader-elect=true --cloud-provider=aws --kubeconfig=/kubeconfig/kubeconfig] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:secrets ReadOnly:true MountPath:/etc/kubernetes/secrets SubPath:} {Name:ssl-host ReadOnly:true MountPath:/etc/ssl/certs SubPath:} {Name:kubeconfig ReadOnly:true MountPath:/kubeconfig SubPath:}] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:10252,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:15,TimeoutSeconds:15,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Sep 14 13:19:58 ip-10-0-3-133 kubelet-wrapper[21633]: W0914 13:19:58.817320   21633 cni.go:258] CNI failed to retrieve network namespace path: Cannot find network namespace for the terminated container "af0c4f036d33195ff127f657ade5911380369114150ebe7173cf1b259cc1387f"
Sep 14 13:19:58 ip-10-0-3-133 kubelet-wrapper[21633]: E0914 13:19:58.899370   21633 cni.go:312] Error deleting network: connection is unauthorized
Sep 14 13:19:58 ip-10-0-3-133 env[849]: time="2017-09-14T13:19:58.900315536Z" level=error msg="Handler for POST /v1.24/containers/af0c4f036d33195ff127f657ade5911380369114150ebe7173cf1b259cc1387f/stop returned error: Container af0c4f036d33195ff127f657ade5911380369114150ebe7173cf1b259cc1387f is already stopped"
Sep 14 13:19:58 ip-10-0-3-133 kubelet-wrapper[21633]: E0914 13:19:58.900835   21633 remote_runtime.go:114] StopPodSandbox "af0c4f036d33195ff127f657ade5911380369114150ebe7173cf1b259cc1387f" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "bootstrap-kube-controller-manager-ip-10-0-3-133.us-west-2.compute.internal_kube-system" network: connection is unauthorized
Sep 14 13:19:58 ip-10-0-3-133 kubelet-wrapper[21633]: E0914 13:19:58.900907   21633 kuberuntime_manager.go:783] Failed to stop sandbox {"docker" "af0c4f036d33195ff127f657ade5911380369114150ebe7173cf1b259cc1387f"}
Sep 14 13:19:58 ip-10-0-3-133 kubelet-wrapper[21633]: E0914 13:19:58.900973   21633 kuberuntime_manager.go:572] killPodWithSyncResult failed: failed to "KillPodSandbox" for "ffff5184f78ea3ec9ac9f0ce499227a2" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"bootstrap-kube-controller-manager-ip-10-0-3-133.us-west-2.compute.internal_kube-system\" network: connection is unauthorized"
Sep 14 13:19:58 ip-10-0-3-133 kubelet-wrapper[21633]: E0914 13:19:58.901011   21633 pod_workers.go:182] Error syncing pod ffff5184f78ea3ec9ac9f0ce499227a2 ("bootstrap-kube-controller-manager-ip-10-0-3-133.us-west-2.compute.internal_kube-system(ffff5184f78ea3ec9ac9f0ce499227a2)"), skipping: failed to "KillPodSandbox" for "ffff5184f78ea3ec9ac9f0ce499227a2" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"bootstrap-kube-controller-manager-ip-10-0-3-133.us-west-2.compute.internal_kube-system\" network: connection is unauthorized"
```

* kubectl get pods -n kube-system   | grep -v Running
```
NAME                                                                            READY     STATUS              RESTARTS   AGE
bootstrap-kube-controller-manager-ip-10-0-3-133.us-west-2.compute.internal      0/1       ContainerCreating   0          3m
bootstrap-kube-scheduler-ip-10-0-3-133.us-west-2.compute.internal               0/1       ContainerCreating   0          3m
kube-apiserver-cnc89-ip-10-0-9-144.us-west-2.compute.internal                   0/1       CrashLoopBackOff    7          3m
kube-apiserver-zhqwg-ip-10-0-6-89.us-west-2.compute.internal                    0/1       CrashLoopBackOff    7          3m
```

* bootkube
```
Get https://api.internal.private/api/v1/namespaces/kube-system/pods: dial tcp 10.0.3.133:443: getsockopt: connection refused
[44867.580671] bootkube[5]: 	Pod Status:          kube-scheduler	Running
[44867.581217] bootkube[5]: 	Pod Status: kube-controller-manager	Running
[44867.581518] bootkube[5]: 	Pod Status:           etcd-operator	Running
[44867.581808] bootkube[5]: 	Pod Status:                kube-dns	Running
[44867.582107] bootkube[5]: 	Pod Status:        pod-checkpointer	Running
[44867.582415] bootkube[5]: 	Pod Status:          kube-apiserver	Running
[44867.582705] bootkube[5]: All self-hosted control plane components successfully started
[44867.582997] bootkube[5]: Migrating to self-hosted etcd cluster...
[44867.583579] bootkube[5]: I0914 13:19:14.697728       5 log.go:19] warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
[44867.583579] bootkube[5]: I0914 13:19:14.697728       5 log.go:19] warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
[45167.585153] bootkube[5]: Error: failed to wait for etcd TPR to be ready: timed out waiting for the condition
[45167.591298] bootkube[5]: Tearing down temporary bootstrap control plane...
[45167.591677] bootkube[5]: Error: failed to wait for etcd TPR to be ready: timed out waiting for the condition
[45167.591974] bootkube[5]: Error: failed to wait for etcd TPR to be ready: timed out waiting for the condition
[45167.592266] bootkube[5]: failed to wait for etcd TPR to be ready: timed out waiting for the condition
```

**Comment by dghubble** [comment]
Perhaps, its hard to be certain since recovery and bootstrap are complex in their own right. The "KillPodSandbox" error certainly looks familiar from when I was debugging this. If you need to recover the cluster, can you try removing `/etc/kubernetes/cni/net.d/10-calico.conf` from every host, trying the recovery tool, and the moment you have a functioning apiserver (before recovery completes) using kubectl to delete calico to ensure it doesn't reinstall that config. Also, looks like you have a bootstrapping scheduler and controller manager, but not apiserver. That pod died for some reason and the logs would be good to see.

**Comment by sstarcher** [comment]
@dghubble Using the same setup I disabled the calico setup and I was just able to restore successfully.  I'll rebuild with calico and try killing that file.

Just to make sure I have the steps in the right order.
* on all nodes rm /etc/kubernetes/cni/net.d/10-calico.conf
* bootkube recover
* bootkube start
* once api server is responding you want me to kubectl delete daemonset for calico?

**Comment by dghubble** [comment]
Well assuming your intention is removing Calico network policy, yes, because the Daemonset recreates the 10-calico.conf file. Re-reading, I don't know that you actually said that, I assumed based on this issue. If normal recovery is failing though and pods that uses non-host networking can't be scheduled, I agree this likely stems from both flannel and calico being in place and a possible mitigation is to remove Calico and see if that helps you recover.

**Comment by sstarcher** [comment]
Yes, I'm not interesting in removing calico.  I'm interesting in a mechanism that would allow me to restore the cluster.

**Comment by aaronlevy** [comment]
/reopen
(for @jlamillan)

**Comment by squeed** [comment]
FWIW, we fixed this in CRI-O. We now cache configuration files on a per-pod basis.

The solution is either to port dockershim to oci-cni, or switch to crio :-).
