### ISSUE TITLE
Worker nodes with taints are never ready

### ISSUE THREAD

**Issue by weikinhuang** [kubernetes-incubator/bootkube#699]
I'm trying to add nodes with pre-registered taints via the kubelet flag `--register-with-taints=foo=bar:NoSchedule`. However the node is never ready because certain pods like `kube-flannel` and `kube-proxy` will never be scheduled there even though they should be running on every node.

According to the documentation on taints https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/, perhaps some of these pods should specify tolerations to tolerate all taints. 

Ex.
```yaml
tolerations:
  - operator: "Exists"
```

**Comment by klausenbusk** [comment]
I have also experienced this, but I ended up just adding a taint for `bar`, but a tolerate to `tolerate all taints` is defiantly more effective.

I will create a PR shortly.

**Comment by klausenbusk** [comment]
PR opened: https://github.com/kubernetes-incubator/bootkube/pull/704

**Comment by weikinhuang** [comment]
Thanks!
