### ISSUE TITLE
Add option to specify etcd prefix for kube-apiserver

### ISSUE THREAD

**Issue by bzub** [kubernetes-incubator/bootkube#712]
Add an `--etcd-prefix` flag to bootkube render that generates the same flag in the kube-apiserver.yaml manifest. If it's not specified then the current behavior is not changed.

My use-case is to speed up and simplify provisioning short-lived bootkube clusters for CI purposes as well as shared etcd instances for low-usage long-lived clusters.

If this sounds good I can submit a PR for it. Thanks!

**Comment by aaronlevy** [comment]
Hi @bzub - unfortunately we wouldn't want to add that as a new configuration flag to `bootkube render`. The reasoning for these kinds of decisions is discussed in the [design principles doc](https://github.com/kubernetes-incubator/bootkube/blob/master/Documentation/design-principles.md). If we were to add these types of customizations, we eventually would just have all the flags for every kubernetes component in `bootkube render` - and it would essentially become unmaintainable.

Instead, we wanted to allow users the options of customizing the manifests between `render` and `start` to allow for complete flexibility - without trying to solve every use-case within the `render` step itself. In this case, you might be able to just do a `sed` of the etcd-prefix flag between running `render` and `start` in your CI runs.

I also added some thoughts to another proposed approach to customizations here: https://github.com/kubernetes-incubator/bootkube/pull/707#issuecomment-332604789

Although what I was proposing wouldn't work for your specific use-case initially (specifically single-flag customizations) -- but it might be able to be added later.

**Comment by dghubble** [comment]
I agree customizing the apiserver `--etcd-prefix` flag shouldn't be in the scope of bootkube render / start. Its a custom modification (sed, custom tools, etc.) I'll close soon unless there is something to be considered.
