### ISSUE TITLE
Calico upgrade from Kubernetes 1.7 to 1.8 - fails to start due to TPR

### ISSUE THREAD

**Issue by andrewwebber** [kubernetes-incubator/bootkube#724]
Upgraded a cluster creates using bootkube 0.6.1 using the flag **--experimental-calico-network-policy**

After following the [upgrade documentation](https://github.com/projectcalico/calico/tree/master/upgrade/v2.5) Calico still fails to start.

```bash
kubectl logs kube-calico-srjbt -n kube-system -c kube-calico

Checking datastore connection
Datastore connection verified
IPv4 address 172.20.11.75 discovered on interface enp3s0
No AS number configured on node resource, using global value
time="2017-09-29T13:42:45Z" level=error msg="Hit error initializing TPR" error="resource does not exist: {{ } {system-network-policy.alpha.projectcalico.org  kube-system    %!s(int64=0) 0001-01-01 00:00:00 +0000 UTC <nil> %!s(*int64=<nil>) map[] map[] [] [] } Calico System Network Policies [{v1}]}" 
time="2017-09-29T13:42:45Z" level=error msg="Hit error initializing TPR" error="resource does not exist: {{ } {global-config.projectcalico.org  kube-system    %!s(int64=0) 0001-01-01 00:00:00 +0000 UTC <nil> %!s(*int64=<nil>) map[] map[] [] [] } Calico Global Configuration [{v1}]}" 
time="2017-09-29T13:42:45Z" level=error msg="Hit error initializing TPR" error="resource does not exist: {{ } {ip-pool.projectcalico.org  kube-system    %!s(int64=0) 0001-01-01 00:00:00 +0000 UTC <nil> %!s(*int64=<nil>) map[] map[] [] [] } Calico IP Pools [{v1}]}" 
time="2017-09-29T13:42:45Z" level=error msg="Hit error initializing TPR" error="resource does not exist: {{ } {global-bgp-peer.projectcalico.org  kube-system    %!s(int64=0) 0001-01-01 00:00:00 +0000 UTC <nil> %!s(*int64=<nil>) map[] map[] [] [] } Calico Global BGP Peers [{v1}]}" 
time="2017-09-29T13:42:45Z" level=error msg="Hit error initializing TPR" error="resource does not exist: {{ } {global-bgp-config.projectcalico.org  kube-system    %!s(int64=0) 0001-01-01 00:00:00 +0000 UTC <nil> %!s(*int64=<nil>) map[] map[] [] [] } Calico Global BGP Configuration [{v1}]}" 
ERROR: Unable to set node resource configuration: Failed to ensure ThirdPartyResources exist: resource does not exist: {{ } {global-bgp-config.projectcalico.org  kube-system    %!s(int64=0) 0001-01-01 00:00:00 +0000 UTC <nil> %!s(*int64=<nil>) map[] map[] [] [] } Calico Global BGP Configuration [{v1}]}
Terminating
Calico node failed to start
```

**Comment by rmenn** [comment]
I just did this today, so currently the render produces calico with 2.4 which uses TPR, you will need the calico 2.5, which moved to CRD its available in #694 to get it to work. TPR was deprecated in 1.8.

**Comment by dghubble** [comment]
Perhaps of interest:

* Refreshed bootkube [upgrade guide](#720) - Mentions preparing the diff between assets produced by bootkube at the original version and target version (yes, there is no release with 1.8 yet). In your case, the diff between 0.6.1 and latest has the TPR -> CRD change you can attempt to apply.
* Next bootkube release will move `--experimental-calico-network-policy` to `--network-provider=canal`. There are also some warning about this configuration. See #723

**Comment by dghubble** [comment]
Thanks for fixing the link @aaronlevy

**Comment by dghubble** [comment]
Did this help with your issue? bootkube itself has switched to using CRDs and works properly. I don't know that there is an issue to be solved in this repo since upstream has documented the way to attempt an in-place migration.

**Comment by dghubble** [comment]
Calico should be working as expected on v1.8.1. If you encounter issues in a fresh setup, can you open an issue?

**Comment by andrewwebber** [comment]
@dghubble this did not work for me.

However my upgrade tests worked with 1.8.1 using --network-provider=flannel.

**Comment by dghubble** [comment]
As in, a fresh v1.8.1 cluster (bootkube v0.8.0) did not work for you or trying to migrate in-place?
