### ISSUE TITLE
Controller manager fails to start when configured with vsphere cloud provider

### ISSUE THREAD

**Issue by amarruedo** [kubernetes-incubator/bootkube#732]
Bootkube version: v0.7.0 

When configuring kube-controller-manager manifest to work with vsphere cloud provider, it crashes with following error:

```
I1009 09:01:59.841827       1 controllermanager.go:108] Version: v1.7.7+coreos.0
W1009 09:01:59.841987       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1009 09:01:59.845378       1 leaderelection.go:179] attempting to acquire leader lease...
I1009 09:01:59.864214       1 leaderelection.go:189] successfully acquired lease kube-system/kube-controller-manager
I1009 09:01:59.864759       1 event.go:218] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-controller-manager", UID:"84fdcff7-accb-11e7-9cf6-000c29ecb513", APIVersion:"v1", ResourceVersion:"2799", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' kube-controller-manager-4121409069-pksn4 became leader
F1009 09:02:02.045257       1 controllermanager.go:177] error building controller context: cloud provider could not be initialized: could not init cloud provider "vsphere": error retrieving vm uuid: open /sys/class/dmi/id/product_serial: permission denied
```
Workaround: configuring controller container to run privileged solves the issue:

```
...
containers:
- name: kube-controller-manager
  image: quay.io/coreos/hyperkube:v1.7.7_coreos.0
  securityContext:
      privileged: true
  command:
  - ./hyperkube
  - controller-manager
...
```

**Comment by dghubble** [comment]
bootkube is known to work with the "aws" and "azure" cloud-provider integrations and with no cloud provider (i.e. ""). Looks like the "vsphere" integration requires read access to:

```
-r--------. 1 root root 4096 Oct 12 19:34 /sys/class/dmi/id/product_serial
```

A quick google of their docs shows this is only accessed as the fallback VM identifier so perhaps it would be better to provide one of the identifiers rather than granting elevated privilege to the controller manager.

https://kubernetes.io/docs/getting-started-guides/vsphere/

I don't use vsphere to test this, but perhaps you can report back if that was a more reasonable option?

**Comment by amarruedo** [comment]
@dghubble sure, I'm out of the office right now, I'll try that next monday. Thanks for the tip!

**Comment by amarruedo** [comment]
I can confirm that using `vm-name` parameter on the `vsphere.conf` file solves the issue (my bad I didn't recheck vsphere guide, it has changed from last time I used it) and is the correct approach.

Thanks for your time.

**Comment by adnoh** [comment]
Setting the vm-name doesn't work for me. I don't see any further usage of this parameter in the provider.
I'm not a go Pro but I don't see any other way as giving access to /sys/class/dmi/id/product_serial because of vsphere.go:
```
// Deprecated as the virtual machines will be automatically discovered.
// VMUUID is the VM Instance UUID of virtual machine which can be retrieved from instanceUuid
// property in VmConfigInfo, or also set as vc.uuid in VMX file.
// If not set, will be fetched from the machine via sysfs (requires root)
VMUUID string `gcfg:"vm-uuid"`
```

```
func newControllerNode(cfg VSphereConfig) (*VSphere, error) {
if cfg.Global.VMUUID == "" {
		// This needs root privileges on the host, and will fail otherwise.
		cfg.Global.VMUUID, err = getvmUUID()
		if err != nil {
			glog.Errorf("Failed to get VM UUID. err: %+v", err)
			return nil, err
		}
}
```

My workaround is to do a ```/usr/bin/chmod 444 /sys/class/dmi/id/product_serial``` in the kubelet.service ExecStartPre. Not the beautifulest solution, but better than running privileged: true in my opinion.
@amarruedo wondering if using vm-name only is working for you

**Comment by amarruedo** [comment]
@adnoh yeah, specifying `vm-name` on `vSphere.conf` of master and worker nodes worked for me.

**Comment by SuneKjaergaard** [comment]
I agree with @adnoh. Also the Kubernetes doc for using vsphere as a cloud provider seems to be out of sync with VM Wares own doc: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html
Specifically it states:

> Below is summary of supported parameters in the vsphere.conf file for Kubernetes version 1.9.x
> user is the vCenter username for vSphere Cloud Provider.

> password is the password for vCenter user specified with user.
> port is the vCenter Server Port. Default is 443 if not specified.
> insecure-flag is set to 1 if vCenter used a self-signed certificate.
> server is the vCenter Server IP or FQDN
> datacenters is the names of the datacenters on which Node VMs are deployed.
> default-datastore is the default datastore to use for provisioning volumes using storage classes/dynamic provisioning.
> resourcepool-path is the path to resource pool where dummy VMs for Storage Profile Based volume provisioning should be created. It is optional parameter.
> folder VM Folder path where Node VMs can be present.

Meaning that vm-name is not supported for k8s 1.9.

**Comment by luis-silva** [comment]
Check the code [here](https://github.com/vmware/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L128).
The vm-uuid (VMUUID) and vm-name (VMName) parameters still exist but are deprecated and therefore should not be used, these values are auto discoverable by giving access to `/sys/class/dmi/id/product_serial`.
This issue should be reopened.

**Comment by luis-silva** [comment]
For information, looking at upcoming Kubernetes release 1.10, the vsphere cloud provider will no longer access `/sys/class/dmi/id/product_serial` or require those parameters (vm-uuid, vm-name) to be provided (PR [here](https://github.com/kubernetes/kubernetes/commit/a698bc73eb0661d879832da388feba49ff88740a))
It will get them from the [NodeInfo object](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/nodemanager.go#L261), which in term gets populated [here](hhttps://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/nodemanager.go#L79) and [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere_util.go#L542)

**Comment by kbrowder** [comment]
So in 1.10 I get this same error at vsphere.go:404
https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/cloudprovider/providers/vsphere/vsphere.go#L402

Isn't the following the problem:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere_util.go#L526?
