### ISSUE TITLE
Deprecate experimental self-hosted Kubelet

### ISSUE THREAD

**Issue by dghubble** [kubernetes-incubator/bootkube#735]
Originally, the experimental self-hosted kubelet feature (`--experimental-self-hosted-kubelet`) was an idea to run an on-host kubelet for bootstrapping and pivot to a scheduled, self-hosted kubelet daemonset. Today, the self-hosted Kubelet feature is not tested, not recommended, and not heavily used (or used at all?) in any [higher level projects](https://github.com/kubernetes-incubator/bootkube/blob/master/Documentation/users-integrations.md).

## Proposal

Phase out the `--experimental-self-hosted-kubelet` flag.

1. Rename `--experimental-self-hosted-kubelet` to `--deprecated-self-hosted-kubelet`. This acts as a forcing function so that any users relying on the setting discover a breakage, but can simply rename to continue using the feature and plan to migrate away from it and comment here. (e.g. 0.8.0?)
2. Remove the `--deprecated-self-hosted-kubelet` flag in a later release (e.g 0.9.0?)

## Feedback

If your organization is using this feature or has concerns, please raise them here. Thanks!

Closes #251 #355 
cc @aaronlevy

**Comment by rockwyc992** [comment]
So that, if I want to update kubelet version of my cluster, how should I do?

I think I will update `/etc/kubernetes/kubelet.env` on every node manually, or I will Install new node with new version to replace old one.   

These are not the best way to use Kubernetes. Does there is any operator to help my do this? (Like what container-linux-update-operator do)

**Comment by dghubble** [comment]
Yes, the kubelet should be run as a kubelet.service which may source a
kubelet.env file or set the version in the unit. Edit the version and
restart the service or just replace the node with another that has the
rev'd version.

It's your choice:
1. Configuration management to edit each host
2. Custom operator to edit each host
3. Immutable infrastructure to rolling replace nodes (i.e. new user-data)

I'm not aware of any public operator that will do this for you.

**Comment by klausenbusk** [comment]
> Does there is any operator to help me do this work? (Like what container-linux-update-operator do)
> 2. Custom operator to edit each host

Hmm, that shouldn't be that hard to implement.
Store the `kubelet.env` in a `ConfigMap`, create a container which keep the on disk `kubelet.env` in-sync with the `ConfigMap` and run it as a `DaemonSet`. Then when the on disk `kubelet.env` change send a dbus `UPDATE_STATUS_UPDATED_NEED_REBOOT` to [CLUO](https://github.com/coreos/container-linux-update-operator) `update-agent`. Job done..

**Comment by dghubble** [comment]
You only need to restart kubelet.service really. Not the whole machine.

**Comment by klausenbusk** [comment]
> You only need to restart kubelet.service really. Not the whole machine.

Correct, but then I would need to write my own logic to manage that. It is easier just to rely on the [CLUO](https://github.com/coreos/container-linux-update-operator) logic, ex: it prevent a bad update from affecting all nodes.

I could of course reimplement all that logic to save a reboot/draining, but that doesen't really adds up.

**Comment by dghubble** [comment]
Sure, an internal Tectonic operator does it exactly like that. Mainly due to broader scope and time constraints. I'd still recommend anyone exploring writing a custom operator consider lighter weight designs.

Anyway, self-hosted kubelet support is removed in #760
