### ISSUE TITLE
TLS Cert deprecation warning

### ISSUE THREAD

**Issue by thorfour** [kubernetes-incubator/bootkube#736]
`I1013 22:56:12.213179       5 logs.go:41] warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated`

**Comment by dghubble** [comment]
Are you working on a fix?

**Comment by dghubble** [comment]
Looks like this is just a bump. https://github.com/coreos/etcd/issues/7647

**Comment by dghubble** [comment]
Actually, I still see this in apiserver logs, even on clusters where the etcd cluster is v3.2.0.

**Comment by dghubble** [comment]
Just to clarify, etcd v3.2.0 does [remove the warning](https://github.com/coreos/etcd/blob/v3.1.10/pkg/transport/listener.go#L238-L240), but this issue was filed about the log line from the apiserver. which is still present.

**Comment by ericchiang** [comment]
Doesn't seem like we're going to take action on this. Closing.

**Comment by dghubble** [comment]
Yes, its external to us. Whenever upstream vendors in etcd 3.2.0, the warning should disappear.
