### ISSUE TITLE
Switch to upstream gcr.io hyperkube image

### ISSUE THREAD

**Issue by dghubble** [kubernetes-incubator/bootkube#744]
We no longer have a concrete need to use `quay.io/coreos/hyperkube:v1.8.x_coreos.y` over `gcr.io/google_containers/hyperkube:v1.8.x` starting with Kubernetes 1.8. The patches in the quay image are used for the Tectonic setup.

Perhaps we consider switching bootkube to the upstream images?

Pros:
* Faster turn around time to bump images when upstream releases them
* Possibly faster downloads for some users (a prior google groups thread mentioned quay.io vs gcr.io was a determining factor outside the US)
* Closer to "upstream" which may be a goal for a kubernetes-incubator project

Cons:
* The "unknown factor". What if we need to return to patching the image in future?
* Others?

**Comment by aaronlevy** [comment]
I'm fine with this. We've since moved off in-hyperkube CNI binaries and that was the last thing that was being patched.
