### ISSUE TITLE
Consider re-enabling self-hosted etcd tests

### ISSUE THREAD

**Issue by diegs** [kubernetes-incubator/bootkube#748]
The self-hosted etcd tests are too flaky to provide valuable signals during PRs, self-hosted etcd support is not being actively developed, and it is currently marked as experimental. As a result the self-etcd PR tests have been disabled. 

Opening this bug to track this fact, and consider re-enabling them in the future if self-hosted etcd is actively worked on again.

cc @aaronlevy

**Comment by ericchiang** [comment]
Self-hosted etcd has been removed from bootkube for the time being. Will re-open if/when we add it back in.
