### ISSUE TITLE
Update docs to refer to cloud-provider specific materials

### ISSUE THREAD

**Issue by dghubble** [kubernetes-incubator/bootkube#754]
Update https://github.com/kubernetes-incubator/bootkube/blob/master/hack/quickstart/quickstart-aws.md to mention any AWS-specific requirements for using `--cloud-provider=aws`. [aws.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go) appears to make quite a few assumptions about IAM roles, metadata access, tags, etc.

- [ ] Find upstream documentation, if any
- [ ] ~Update quickstart to obey requirements~

Original issue where user hit this issue and worked around it by adding a `KubernetesCluster=name` tag (called legacy in source code). #749

**Comment by ericchiang** [comment]
Best resource I could find was a doc by Heptio on this https://docs.google.com/document/d/17d4qinC_HnIwrK0GHnRlD1FKkTNdN__VO4TH9-EzbIY/edit?ts=59d7b23b#heading=h.2hif681swxfg

Would be a good starting point. Also might be better to just contribute these requirements upstream and link to them from bootkube's doc.

**Comment by aaronlevy** [comment]
I'm a bit hesitant to go down that road. We don't test cloud-provider specific features (conformance is just vanilla k8s). I might lean toward just documenting "If you're doing this for real, you should set the cloud-provider, and read X docs".

The intention with quickstart is just launch simple compute resources. Having to do things like setup iam roles, tags, etc. starts to just complicate something that shouldn't be used for "real" clusters anyway (and then need to mimic it on gcp, etc.)

**Comment by dghubble** [comment]
I'm not opposed to saying we only support/test clusters without a custom cloud-provider. Now that you mention it, the quickstart doesn't actually add cloud-provider=aws, my mistake I thought it was broken as shown. The issue reporter must have added that independently.

**Comment by dghubble** [comment]
Looking through that document, the requirements do seem much more involved than we want to get into with roles and tags, since bootkube is just showing examples. Plus I'd consider `ec2: *, elasticloadbalancer: *` somewhat egregious from a security standpoint anyway, I wouldn't want to endorse it here.

Let's keep the quickstart as is (no cloud-provider) and opt for documenting, "if you set a cloud provider, go read X". Maybe in the top level README?
