### ISSUE TITLE
validate api-servers flag contains both host:port

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#757]
the `--api-servers` flag expects there to be a port defined: https://github.com/kubernetes-incubator/bootkube/blob/master/cmd/bootkube/render.go#L69

But it looks like we don't validate that. If no port is defined, the `--secure-port` flag may be left empty: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L190 which is invalid

**Comment by omkensey** [comment]
IMHO if no port is specified, just defaulting to 443 and starting up makes sense.

**Comment by aaronlevy** [comment]
Technically the default is `6443`, so I'd probably lean in that direction if we're going to default the flags.

**Comment by dghubble** [comment]
kubeadm switched to 6443. I've disagreed with this in the past. Discussion: https://github.com/poseidon/terraform-render-bootkube/pull/17

**Comment by aaronlevy** [comment]
A big reason for this would be so that you can set the apiserver pod to not run as root (443 is privileged port + hostNetwork). I'd like to get default pod-security policies in place that don't allow running as root, and enforce it even on control-plane components (especially ones that are likely exposed to the internet).

**Comment by dghubble** [comment]
I left the possibility open before. We'd want to make sure it works with either port for a release cycle because of the impact on firewalls and load balancers / routers and other details in setups. (i.e. need to update a bunch of things).

**Comment by omkensey** [comment]
Would giving the non-root apiserver container CAP_NET_BIND_SERVICE solve the binding problem?

**Comment by aaronlevy** [comment]
Yes, but with the way docker builds image layers, it basically doubles the size (two copies of the binary). Also I believe you still have to give the pod that capability too then.

**Comment by omkensey** [comment]
I meant giving it that capability at runtime via securityContext in the pod spec.  There shouldn’t be a need to actually rebuild the container then should there?

**Comment by wking** [comment]
I like the `CAP_NET_BIND_SERVICE` approach myself (minimal privledhe escalation risk, and staying on 443 raises the bar a bit for any would-be-middlemen).  But with `kubeadm` using 6443 as mentioned above, and us using 6443 since #789, just defaulting to 6443 seems best.
