### ISSUE TITLE
bootkube

### ISSUE THREAD

**Issue by beatlejuse** [kubernetes-incubator/bootkube#769]
my system does not have a command "bootkube":
"-bash: bootkube: command not found".
you forgot to write in the instructions, how and where to install the bootkube so that it will work!

**Comment by dghubble** [comment]
You can either build [from source](https://github.com/kubernetes-incubator/bootkube/blob/master/Documentation/development.md) or use the prebuilt binary in [release tarballs](https://github.com/kubernetes-incubator/bootkube/releases) provided for convenience.

**Comment by beatlejuse** [comment]
Thank you!
