### ISSUE TITLE
etcd migration

### ISSUE THREAD

**Issue by beatlejuse** [kubernetes-incubator/bootkube#770]
in this video (https://youtu.be/EbNxGK9MwN4 from 31:30) described the process of transition from native etcd cluster to etcd-cluster in kubernetes.
How can i use this automation element in my cluster automation process?
i'm deploying my cluster by PXE. i'm using CoreOS. for start kubernetes, i'm using etcd-cluster in CoreOS.
After start kubernetes, i need migrate etcd-cluster to kubernetes and i want to use etcd-operator (https://github.com/coreos/etcd-operator) to servicing it.

**Comment by klausenbusk** [comment]
Have you read https://github.com/kubernetes-incubator/bootkube/issues/738 ?

**Comment by rockwyc992** [comment]
[here](https://github.com/coreos/etcd-operator/blob/master/CHANGELOG.md#release-031) is the way to migrate your etcd to self-hosted.
But you need to change the etcd endpoints for kube-apiserver by yourself.


BTW, I think self-hosted EtcdCluster is a good idea to manage and recover your EtcdCluster.

**Comment by rockwyc992** [comment]
[here](https://github.com/kubernetes-incubator/bootkube/blob/master/Documentation/disaster-recovery.md#if-an-etcd-backup-is-available-self-hosted-etcd) is the way tell you how to recover a Kubernetes with self-hosted EtcdCluster from a backup-file.

Don't try etcd-operator version greater than "v0.5.0". You may meet some problems about compatibility.

**Comment by beatlejuse** [comment]
Thank you very much! I'll try it and will write about the result

**Comment by dghubble** [comment]
Unfortunately, we're no longer prioritizing time for Kubernetes backed by self-hosted etcd, per #738. Tests have been disabled for now, but may be resumed if things change #748 

As such, we're not encouraging migrating to it.

**Comment by hongchaodeng** [comment]
@aaronlevy @dghubble 

Why close this issue? This is a problem and should be kept open until it is fixed. Right?

> Unfortunately, we're no longer prioritizing time for Kubernetes backed by self-hosted etcd, per #738. 

Who is "we"? And why we should close an issue that users reported problems?

cc @philips

**Comment by hongchaodeng** [comment]
This should be reopen-ed.
Let's discuss on the following Monday for permissions to close issues.

**Comment by dghubble** [comment]
Would you like to be assigned?

**Comment by hongchaodeng** [comment]
Sure. Thanks for re-opening it.

**Comment by ericchiang** [comment]
Self-hosted etcd has been removed from bootkube for the time being. Will re-open if/when we add it back in.
