### ISSUE TITLE
[Feat] add an option to allow to select the backend that is used by flannel

### ISSUE THREAD

**Issue by JrCs** [kubernetes-incubator/bootkube#771]
Actually "vxlan" is hard coded in flannel configuration file.
Can you add an option to allow to configure the backend that is used by flannel (like "[host-gw](https://github.com/coreos/flannel/blob/master/Documentation/backends.md#host-gw)" ) ?

**Comment by ericchiang** [comment]
Bootkube generally doesn't add flags for every option. You can easily tweak the results of `bootkube render` though, or render your own manifests and just use `bootkube start` for further customization.

**Comment by JrCs** [comment]
Ok i understand
