### ISSUE TITLE
Use same certificate folder as kubeadm

### ISSUE THREAD

**Issue by rothgar** [kubernetes-incubator/bootkube#773]
Bootkube uses /etc/kubernetes/kubelet/tls for storing certificates. Kubeadm uses /etc/kubernetes/pki

It may be nice to use a common folder for admins/users to not have to remember or look in two places.

Opening this after #663 discussion

**Comment by ericchiang** [comment]
In #663 `/etc/kubernetes/kubelet/tls` is only for rotated kubelet certs.  I think kubeadm stores _all_ of its certificate data in `/etc/kubernetes/pki`, like the CA, administrative client certs, etc.

It looks like kubeadm doesn't set the `--cert-dir` argument, so it should default to `/var/lib/kubelet/pki`.

https://github.com/kubernetes/kubernetes/blob/v1.9.0-alpha.2/build/debs/10-kubeadm.conf

We might just want to use `/var/lib/kubelet/pki` from the start.

**Comment by ericchiang** [comment]
Also since this is a kubelet configuration, bootkube itself doesn't rely on this being any particular directory. Users of bootkube can configure it to whatever they want (though they'll likely just copy our examples).

**Comment by ericchiang** [comment]
#663 is now merged.
