### ISSUE TITLE
Integrate support for Cilium CNI

### ISSUE THREAD

**Issue by jpds** [kubernetes-incubator/bootkube#779]
I'd like to use cilium.io as my CNI with a Typhoon deployment at some point, however it looks like bootkube requires support for this first before support can be added there.

**Comment by dghubble** [comment]
No specific changes need to be made to `bootkube start` for the self-hosted control plane to use a particular CNI provider. You can independently swap the flannel manifests for your Cilium manifests and try to get it to work correctly.

If you're interested in adding Cilium, a good starting point would be adding the DaemonSet and sidecar (to lay down the CNI plugins on hosts) manifests to `bootkube render` and verifying you can bootstrap clusters and container networking works as expected. Separately, we'd want to decide whether its worth supporting and testing as this takes time.

**Comment by jpds** [comment]
PR now at: https://github.com/poseidon/terraform-render-bootkube/pull/34
