### ISSUE TITLE
Improve log collection for e2e tests

### ISSUE THREAD

**Issue by ericchiang** [kubernetes-incubator/bootkube#783]
- [ ] Organize log artifacts based on which node they we captured from.
- [x] All logs should include timestamps.
- [ ] Stop depending on the fluentd manifests compiled into https://github.com/coreos/ktestutil

We should consider removing fluentd since we still have to SSH to the master to grab them off disk (it's not configured to actively send logs to s3 or something like that). If the master restarts and fails to boot the control plane, fluentd doesn't come back up and we lose all logs for the test.

Consider just SSH'ing to the nodes to fetch logs directly from Docker and journald. Here's a script that does that pretty well.

```bash
#!/bin/bash -e

for CID in $( docker ps -a -q ); do
  if [ "$( docker inspect $CID | jq '.[0].Path' )" == "\"/pause\"" ]; then
    # Ignore pause pods
    continue
  fi

  NAME=$( docker inspect $CID | jq '.[0].Name' -r | sed 's/^\/k8s_//g' )
  echo $NAME
  docker logs -t $CID > "container-$NAME.log" 2>&1
done

for UNIT in $( echo "kubelet docker" ); do
  echo $UNIT
  journalctl \
    -o short-iso \
    --no-hostname \
    -u $UNIT > "service-$UNIT.log"
done
```

**Comment by rphillips** [comment]
nit, ```for unit in "kubelet docker"; do ...``` the echo is superfluous

**Comment by rphillips** [comment]
Some tweaks to store in a logs directory, so they are easily copied.

```bash
#!/bin/bash

# dependencies
#   jq
#   docker
#   journalctl

set -euo pipefail

LOG_DIR=${LOG_DIR-$PWD/logs}

rm -rf ${LOG_DIR} && mkdir -p ${LOG_DIR}

for CID in $( docker ps -a -q ); do
  if [ "$( docker inspect $CID | jq '.[0].Path' )" == "\"/pause\"" ]; then
    # Ignore pause pods
    continue
  fi

  NAME=$( docker inspect $CID | jq '.[0].Name' -r | sed 's/^\/k8s_//g' )
  docker logs \
    -t $CID > "${LOG_DIR}/container-$NAME.log" 2>&1
done

for UNIT in kubelet docker; do
  journalctl \
    -o short-iso \
    --no-hostname \
    -u $UNIT > "${LOG_DIR}/service-$UNIT.log"
done

echo DONE
```

**Comment by rphillips** [comment]
Fixed with the previous PR.

**Comment by rphillips** [comment]
Woops. Need to bump the vendor deps to pull in the fix.

**Comment by ericchiang** [comment]
@rphillips I think it'd still be a good long term goal to get rid of depending on a fluentd manifests compiled into coreos/ktestutil. Maybe I can make that a different issue.

**Comment by rphillips** [comment]
We could still do that in this issue.

**Comment by rphillips** [comment]
Vendor Bump: https://github.com/kubernetes-incubator/bootkube/pull/805

**Comment by rphillips** [comment]
Fluentd doesn't support a custom output format (really strange). It's just a machine log forwarder, so cleaning up the json log lines is tricky.
