### ISSUE TITLE
bootkube should tolerate uninitialized nodes

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes-incubator/bootkube#800]
I think all the `bootkube` manifest should tolerate the `node.cloudprovider.kubernetes.io/uninitialized` taint.

This would make it possible to bootstrap a cluster with a external CCM (Cloud Controller Manager) and `--cloud-provider=external` and should make it safe to switch a running cluster to a CCM.

Per the design docs: https://github.com/kubernetes/community/blob/930ce65595a3f7ce1c49acfac711fee3a25f5670/contributors/design-proposals/cloud-provider/cloud-provider-refactoring.md , I don't think this would cause any issue.
```
Among these controller loops, the following are cloud provider dependent.
    nodeController
    volumeController
    routeController
    serviceController
```
```
    Node Controller: For checking the cloud provider to determine if a node has been deleted in the cloud after it stops responding
    Route Controller: For setting up routes in the underlying cloud infrastructure
    Service Controller: For creating, updating and deleting cloud provider load balancers
    Volume Controller: For creating, attaching, and mounting volumes, and interacting with the cloud provider to orchestrate volumes
```
per https://kubernetes.io/docs/concepts/overview/components/

**Comment by klausenbusk** [comment]
See also: https://github.com/projectcalico/calico/pull/1286

**Comment by ericchiang** [comment]
@colemickens I know you got CCM running with bootkube before. Can you comment on this?

**Comment by colemickens** [comment]
I would agree with this assesment: https://github.com/colemickens/tectonic-installer/commit/4e948bd7326a0729dd18d31dd22fd475b096cc4a#diff-83beaecec190e3958db827dd8a570b14R60
