### ISSUE TITLE
DNS Port migration off of privileged ports

### ISSUE THREAD

**Issue by rphillips** [kubernetes-incubator/bootkube#809]
In writing the root-requirements document, @aaronlevy mentioned we might be able to have the dns service listen on a non-priviledged port and use a Service to expose port 53.

related to: https://github.com/kubernetes-incubator/bootkube/pull/808

**Comment by ericchiang** [comment]
For some unrelated reasons, kube-dns can't be run as non-root today https://github.com/kubernetes/dns/issues/190
