### ISSUE TITLE
Apiserver doesn't survive node reboot in non HA mode

### ISSUE THREAD

**Issue by weikinhuang** [kubernetes-incubator/bootkube#822]
After a node reboot or kube-apiserver version update (when there is only 1 instance of the api-server), the api server never recovers and will go into a crashloop with the following message:

```
Flag --etcd-quorum-read has been deprecated, This flag is deprecated and the ability to switch off quorum read will be removed in a future release.
I0103 18:41:26.195707       1 server.go:121] Version: v1.8.5
Error: unable to load server certificate: open /etc/kubernetes/secrets/apiserver.crt: permission denied
```

This issue started somewhere between bootkube 0.8.1 and 0.9.1.

**Comment by xiang90** [comment]
> This issue started somewhere between bootkube 0.8.1 and 0.9.1.

Can you help to investigate this problem more, and identify the specific version? We also hope to see the more concrete steps to reproduce this problem if possible. Thanks!

**Comment by weikinhuang** [comment]
I can try, but I don't really have the hardware to do so. I'm just running this at home, and the reboot happens when coreos updates.

In this instance, I tried adding the `--runtime-config=api/all=true` flag to the apiserver then doing a `kubectl apply -f manifests/kube-apiserver.yaml` (running this on bootkube v0.9.1)

**Comment by weikinhuang** [comment]
Tried reproducing, unable to get the error to happen again. And have since rebuilt the cluster from scratch. However the 2 conditions above are when I have encountered it.

**Comment by prafull01** [comment]
I have faced the same issue on K8S 1.10.3, the issue was related to cgroup driver of kubelet and docker. This issue happens with the cgroup driver as systemd on kubelet and docker. If you change cgroup driver to cgroupfs on both docker and kubelet the node restart fine.
