### ISSUE TITLE
e2e: TestReboot test doesn't wait for real control plane to be restored, can cause flakes in TestSmoke

### ISSUE THREAD

**Issue by ericchiang** [kubernetes-incubator/bootkube#837]
TestReboot only waits for the nodes to be ready. Based on my testing, the control plane is just the checkpointed control plane, not the actual one. When the control plane does come back, there's a point where neither is running, which can impact the TestSmoke test.

In https://github.com/kubernetes-incubator/bootkube/pull/831 I tried to wait for the API server to loose the checkpointer annotation, which showed that it can take more than 5 min (!) for the real control plane to come back up.

Output here:

https://jenkins-kube-lifecycle.prod.coreos.systems/job/bootkube-pr-e2e/716/console

Example of pods with the checkpointer annotation on them in kube-system:

```
00:10:36 [163005.176363] golang[6]: E0113 00:10:36.181749    2147 main_test.go:161] attempt 12: kube-system still has checkpoint pods=["kube-apiserver-f22bh-ip-10-8-0-153.ec2.internal" "pod-checkpointer-95fbd-ip-10-8-0-153.ec2.internal"], non-checkpoint pods=["kube-controller-manager-c5c47f48-bthqh" "kube-controller-manager-c5c47f48-fcmpz" "kube-dns-ff8f6db49-z48r4" "kube-flannel-sjfrx" "kube-flannel-trvbt" "kube-proxy-dhd99" "kube-proxy-vt9g4" "kube-scheduler-546ff4f59b-6kqqw" "kube-scheduler-546ff4f59b-7nqbl" "pod-checkpointer-95fbd"]
```

cc @colemickens

**Comment by xiang90** [comment]
> which showed that it can take more than 5 min (!) for the real control plane to come back up.

this issue itself might worth investigation and a separate github issue tracking. i do not expect it can take such a long time.

**Comment by dghubble** [comment]
Is 5 minutes excluding the time for the node to shutdown and come back up? I don't see it in logs, but maybe its there.

**Comment by ericchiang** [comment]
5 min after all nodes are marked ready.

**Comment by ericchiang** [comment]
I have a hypothesis that removing the API server flock (https://github.com/kubernetes-incubator/bootkube/pull/616) might make the API server hand-off less clean and increase the amount of time it takes to recover. We should still ensure the test waits for the real control plane to come back up, but it might be worth trying to add the flock back in.

**Comment by diegs** [comment]
@ericchiang adding the flock back in makes it difficult to run the apiserver as a non-root user, since its current implementation relies on using a host-mounted lock file in `/var/lock`

**Comment by ericchiang** [comment]
@diegs yeah, but if it impacts reboot times this much I'm in favor of a revert.

Let's open a PR once https://github.com/kubernetes-incubator/bootkube/pull/847 gets in. Then if it was an issue we can discuss trade-offs.

**Comment by colemickens** [comment]
Yes, I will do this in a separate PR. We can discuss a less-privileged location to place the lock file as well. (I'll go ahead and update the PR description to reflect the removal of the revert. Thanks)

**Comment by diegs** [comment]
@colemickens @ericchiang another reason not to use the flock is because (at least the one that was in the old hyperkube image) didn't propagate signals properly, so terminating the apiserver was broken. There's an issue somewhere here about it (probably closed now)

**Comment by diegs** [comment]
Ah yes #502
