### ISSUE TITLE
Render should always use TLS for etcd

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#853]
We shouldn't encourage the use of insecure etcd in our render step - and should probably just remove this option (`etcdUseTLS`). If a user wants insecure etcd - they could still provide assets they have modified to the `start` phase.

**Comment by klausenbusk** [comment]
We run etcd on all master nodes and use TLS for peer communication, but not for client communection (etcd just listen on localhost). Is that a valid/secure use-case?

**Comment by aaronlevy** [comment]
@klausenbusk - that's a good point to consider, thanks for bringing it up.

Thinking about it more - co-locating apiserver with etcd is somewhat common in the wider community (especially on single-node clusters).
