### ISSUE TITLE
Extend recover command to support temp control plane.

### ISSUE THREAD

**Issue by coresolve** [kubernetes-incubator/bootkube#857]
In some cases a misconfiguration of the apiserver opject in etcd causes the control plane to crash.
At this point there are not great options to correct it. 

A current work around is to: 

1. Use bootkube recovery to make static assets. 
2. Copy the tls directory contents to /etc/kubernetes/bootstrap-secrets
3. View and possibly modify the config of the apiserver manifest in bootstrap-manifests.
4. Copy the apiserver manifest from bootstrap-manifests to /etc/kubernetes/manifests

Since this is done outside of bootkube control the temp control plane will exist until we tear it down by removing the bootstrap apiserver manifest  from /etc/kubernetes/manifests

Allowing time to modify the object in etcd leveraging the temp apiserver

I think it would be great to extend bootkube recover or document this approach to help recover clusters that have persisted a bad apiserver config to etcd.

Potentially if you are unsure about the change you are making to the apiserver you can use this method proactively. At this point when you make the change to the config you have a fallback apiserver in case your changes don't apply correctly.

**Comment by xiang90** [comment]
@coresolve 

Another way is to modify/fix the API configuration in etcd directly before recovery. API machinery is working on a tool to make it easier to do that in a k8s centric way, see https://github.com/jpbetz/auger

**Comment by xiang90** [comment]
I am not against allowing a user defined temporary API server teardown process as @coresolve proposed. But I hope to see a clean, supported and well-documented method.
