### ISSUE TITLE
bootkube should determine if etcd has previous content in it. 

### ISSUE THREAD

**Issue by coresolve** [kubernetes-incubator/bootkube#862]
Bootkube assumes that it's filling an empty etcd cluster. If one runs bootkube twice in a row on the same etcd cluster there will be conflicts and bootkube will fail. 

An example failure:
```
Jan 24 14:58:18 node1.example.com bootkube-start[3054]: [ 1508.462650] bootkube[7]: E0124 14:58:18.889455       7 create.go:50] Error creating assets: error when creating "/assets/manifests/kube-dns-svc.yaml": Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.3.0.10": provided IP is already allocated
Jan 24 14:58:18 node1.example.com bootkube-start[3054]: [ 1508.463460] bootkube[7]: Error creating assets: error when creating "/assets/manifests/kube-dns-svc.yaml": Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.3.0.10": provided IP is already allocated
```

I think it makes sense to determine if there are entries in etcd before doing work. If so complain about that and exit.

**Comment by xiang90** [comment]
@coresolve 

There are quite a bit per-checking we can do around etcd:

1. is the etcd version supported
2. is the etcd empty
3. is the etcd endpoints belonging to the same cluster
4. is the etcd deployment performant enough to support k8s

I am not sure if bootkube is the right place to do any of these per-checking. Or the installer that invokes bootkube should. As far as I can see, we never try to make bootkube a full installation solution.

/cc @aaronlevy

**Comment by ericchiang** [comment]
Possible dup of https://github.com/kubernetes-incubator/bootkube/issues/700 ?
