### ISSUE TITLE
More TestReboot/TestSmoke flakes

### ISSUE THREAD

**Issue by ericchiang** [kubernetes-incubator/bootkube#864]
We're still seeing issues with TestReboot and TestSmoke, despite https://github.com/kubernetes-incubator/bootkube/pull/847 (which I still believe helped significantly).

https://jenkins-kube-lifecycle.prod.coreos.systems/job/bootkube-pr-e2e/781/console
https://github.com/kubernetes-incubator/bootkube/pull/830

```
19:28:11 [1182860.546921] golang[6]: --- FAIL: TestReboot (704.78s)
19:28:11 [1182860.607223] golang[6]: 	reboot_test.go:25: rebooting 2 nodes
19:28:11 [1182860.607840] golang[6]: 	reboot_test.go:43: waiting for control plane: get pods in kube-system: Get https://34.230.36.237:6443/api/v1/namespaces/kube-system/pods: dial tcp 34.230.36.237:6443: getsockopt: connection refused
19:28:11 [1182860.608165] golang[6]: === RUN   TestSmoke
19:38:11 [1183460.605986] golang[6]: --- FAIL: TestSmoke (600.06s)
19:38:11 [1183460.608772] golang[6]: 	smoke_test.go:13: Test nginx creation failed: error creating deployment nginx-lkcdt: Post https://34.230.36.237:6443/apis/extensions/v1beta1/namespaces/bootkube-e2e-5f498998/deployments: dial tcp 34.230.36.237:6443: getsockopt: connection refused
```

https://jenkins-kube-lifecycle.prod.coreos.systems/job/bootkube-pr-e2e/778/console
https://github.com/kubernetes-incubator/bootkube/pull/854

```
06:07:30 [1134819.834158] golang[6]: --- PASS: TestReboot (160.80s)
06:07:30 [1134819.834738] golang[6]: 	reboot_test.go:25: rebooting 2 nodes
06:07:30 [1134819.834955] golang[6]: === RUN   TestSmoke
06:08:02 [1134850.974773] golang[6]: --- FAIL: TestSmoke (31.14s)
06:08:02 [1134850.975368] golang[6]: 	smoke_test.go:13: Test nginx creation failed: error creating service nginx-78k4r: Post https://54.208.161.236:6443/api/v1/namespaces/bootkube-e2e-1efd07cc/services: dial tcp 54.208.161.236:6443: getsockopt: connection refused
```

cc @colemickens in case you have any thoughts.

**Comment by colemickens** [comment]
Not any thoughts yet, it's definitely a different failure, but also concerning since it looks like apiserver is down/unhealthy. I was going to take another look at TestSmoke to add waiting for control plane, I'll keep an eye on apiserver as well during that 10 minute window.

Also strange that it fails with that continuously for 10 minutes, rather than being intermittent.

**Comment by ericchiang** [comment]
@colemickens I think we need better logs. Ref https://github.com/kubernetes-incubator/bootkube/issues/783

(cc @rphillips)

**Comment by ericchiang** [comment]
closing in favor of #824
