### ISSUE TITLE
CI: be able to re-run individual e2e tests

### ISSUE THREAD

**Issue by ericchiang** [kubernetes-incubator/bootkube#865]
We plan on migrating CI soon. I'd be really good to have this.

**Comment by colemickens** [comment]
I'm not sure this is achievable without upstream changes to `ghprb` to allow for "arguments" to flow from comments into Jenkins as build parameters. (Which sounds a bit dicey too, build parameters include the sha1 hash [security vector], or the base hyperkube image [again, security], etc).

Even if it were possible to pass through params like this... when that job runs and executes a single e2e test, it lacks the context for which GitHub indicator to update. A single test can't really update the full e2e test result (how does it know it's the only re-queued test, etc). If it updates it's own one-off context status, then the full e2e suite would remain red.

I'll keep thinking a bit about this, but without having a separate job invocation for each unit test that each post their own status back (which could be orchestrated with job-dsl fairly easily), this would be a fairly large ask.

**Comment by ericchiang** [comment]
I think this would be a nice to have but not a blocker. Non-flaky tests would work even better.

Closing for now. Can re-open once we have the new CI running.
