### ISSUE TITLE
kube-dns failed to resolve domain names due to lack of arg --kubecfg-file in kube-dns container starting command

### ISSUE THREAD

**Issue by LihuaWu** [kubernetes-incubator/bootkube#871]
## environment: 
bootkube version: 83b93c1c626c97feffb5ea50a62fc1be6a1e5a13
OS: centos7.2
kubelet version: 1.9.1
network-provider: flannel
Host Network: not connected to internet, behind a proxy

## what happened:
kube-dns failed to resolve domain names, due to connected to wrong apiserver(https://cluster-ip:443).

## How to solve it:
The solution works in my case, as follows:
1.  mount `kubeconfig-in-cluster` configmap as volume in `kube-dns-deployment.yaml `
2.  add `--kubecfg-file` in container `kube-dns` start args.

If above solution is OK, I can open an PR.

**Comment by ericchiang** [comment]
Is the problem that you've configured your API server's DNS name to point at the proxy? But kube-dns needs to reference an alternative name?

**Comment by LihuaWu** [comment]
No,  AFAIK,  the problem has no relation with proxy. 

It happened simply because it didn't use a kubecfg-file as its start command parameter. And then it connected to a wrong apiserver as its default behavior.

**Comment by ericchiang** [comment]
> It happened simply because it didn't use a kubecfg-file as its start command parameter. And then it connected to a wrong apiserver as its default behavior.

Can you elaborate on what "wrong API server" means? Kube-dns sholud attempt to connect to the API server endpoint, which is an internal IP address.

```
$ kubectl get endpoints -n default kubernetes -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2018-02-05T17:18:44Z
  name: kubernetes
  namespace: default
  resourceVersion: "7"
  selfLink: /api/v1/namespaces/default/endpoints/kubernetes
  uid: 9e4248aa-0a98-11e8-ae49-0615bdbc521a
subsets:
- addresses:
  - ip: 10.0.25.45
  ports:
  - name: https
    port: 443
    protocol: TCP
```

**Comment by LihuaWu** [comment]
> Kube-dns sholud attempt to connect to the API server endpoint, which is an internal IP address.

In my case, the `internal IP address` is within a subnet(10.3.0.0/24) I built for kube-dns to use.
the kube-dns tried to connect to an ip that didn't work at that moment. 
It seemed like a chicken-egg problem.

> Can you elaborate on what "wrong API server" means?

the `wrong API server` is `https://10.3.0.1:443`

```
kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.3.0.1     <none>        443/TCP   6d
my-nginx     ClusterIP   10.3.0.90    <none>        80/TCP    4d
```
 To make things clear, the ip `10.153.43.107` is a nodeIp or hostIp
```
kubectl get endpoints -n default kubernetes -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2018-01-30T08:53:10Z
  name: kubernetes
  namespace: default
  resourceVersion: "757342"
  selfLink: /api/v1/namespaces/default/endpoints/kubernetes
  uid: ffcf56c1-059a-11e8-837f-aaaaaa1bb37c
subsets:
- addresses:
  - ip: 10.153.43.107
  ports:
  - name: https
    port: 6443
    protocol: TCP
```
