### ISSUE TITLE
add --endpoint-reconciler-type=lease starting flag for kube-apiserver.yaml

### ISSUE THREAD

**Issue by LihuaWu** [kubernetes-incubator/bootkube#879]
when running HA apiserver,  the --endpoint-reconciler-type=lease flag should be added.

Detailed description see below links:
https://kubernetes.io/docs/admin/high-availability/building/#endpoint-reconciler

**Comment by ericchiang** [comment]
Some previous discussion:

https://github.com/kubernetes-incubator/bootkube/pull/850
https://github.com/kubernetes/kubernetes/issues/57617
https://github.com/kubernetes/kubernetes/pull/58474

TL;DR we need some e2e tests to promote this to beta. Until then we're resistant to turning it on in bootkube.

I'll note that we're trying to get the e2e tests running against bootkube, which would allow us to do this testing, but that's a much longer term plan.

**Comment by LihuaWu** [comment]
ok. sorry for hadn't checked history issues before.
I will close the issue.
thanks.

**Comment by ericchiang** [comment]
I'm going to keep this open if you don't mind. We do want to add this, and this issue would be a good place to track that progress :)

**Comment by klausenbusk** [comment]
> when running HA apiserver, the --endpoint-reconciler-type=lease flag should be added.

As we selfhost `kube-apiserver` we could just disable the reconciler and create a `kubernetes` service which use a selector to match the `kube-apiserver` pod.

However, I'm not sure which approach is the best.

**Comment by colemickens** [comment]
area/render

**Comment by rphillips** [comment]
Lease Endpoint is going to be the default in 1.11. We may not even need the flag.
