### ISSUE TITLE
checkpointer doesn't start if master is a url

### ISSUE THREAD

**Issue by carlos-licea** [kubernetes-incubator/bootkube#881]
Checkpointer doesn't start if I render assets with a url rather than an IP. I tried but I couldn't even retrive logs. It looks to me that it's not even scheduled even though the daemonset is created. 

Rendring with --api-server=https://master.kubernetes.int:6443

I can even kubectl into the boostrap API server but the new API server pod is not scheduled becasue checkpointer is not started.

How may I provide more useful information?

**Comment by ericchiang** [comment]
Do you have any logs from the checkpointer? We use URLs for API servers in other projects and it works just fine.

**Comment by carlos-licea** [comment]
I'm gonna try but how could I if it's not scheduled? still fairly new to kubernetes, would you point out to me which logs should I look into?

**Comment by ericchiang** [comment]
When debugging the bootstrap components you generally ssh onto the node and
run docker commands to get logs from the failing containers.

**Comment by colemickens** [comment]
If it's not getting scheduled, it would be helpful to get the `kubectl describe pod ...` output that might tell us why it's failing to schedule. (are your nodes not healthy?)
