### ISSUE TITLE
bootcube doesn't allow pre-existing/mounted assets folder

### ISSUE THREAD

**Issue by MPV** [kubernetes-incubator/bootkube#884]
**When I:**
...try to mount an existing `assets` folder into a container with `bootkube` and ask it to render assets:
```
$ docker run --rm --entrypoint=/bootkube -v $(pwd)/assets:/assets \
    quay.io/coreos/bootkube:v0.10.0 render --asset-dir=/assets
```

**Expected:**
Files created under mounted `$(pwd)/assets` folder.

**Actual:**
This output (and no files generated):
```
Error: mkdir /assets: file exists
mkdir /assets: file exists
```

...whereas if I don't mount anything into the container, it can create the folder and generate the assets successfully.

**Comment by rphillips** [comment]
PR #886 should get the cleared up.

**Comment by diegs** [comment]
FWIW I believe this behavior originally existed to prevent users from accidentally overwriting previously-rendered and possibly customized assets. Not sure if that's still a compelling reason but it's something to consider.

**Comment by dghubble** [comment]
Yeah, I think this is expected to prevent overwriting like @diegs said. cc @rphillips

**Comment by dghubble** [comment]
Nvm, I think #886 handles this in a decent way.

**Comment by rphillips** [comment]
Thanks... Updated the PR to check for an empty directory.

**Comment by MPV** [comment]
Wonderful, thanks! 🙏
tis 13 feb. 2018 kl. 00:08 skrev Ryan Phillips <notifications@github.com>:
