### ISSUE TITLE
Allow cluster members identified by DNS name

### ISSUE THREAD

**Issue by dghubble** [kubernetes-incubator/bootkube#89]
Background:

We're migrating provisioning of cluster members to use DNS names instead of IPs to ensure reference clusters are similar to production https://github.com/coreos/coreos-baremetal/issues/291. This allows network settings to be provided by network DHCP server since the gatway, DNS server, IP, etc. can change over the life of the machine. I'll note we're using static MAC address to IP mappings which are fine for now, this is really to move away from hardcoding networkd configurations and instead respect the network setup.

Problem:

There are a few places in `bootkube` which still assume IPs will be used (`--hostname-override=$(MY_POD_IP)` via downward api) and I think we'll need the ability to toggle that assumption. In the absence of an explicit `--hostname-override`, the kubelet [exec](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/node/node.go#L33)'s `uname -n` to determine the hostname to use. During provisioning we can enforce that `/etc/hostname` is populated with the correct name to satisfy the kubelet, but we need `kubelet.yaml` to leave off the flag. Also, `kube-apiserver.yaml` also uses the downward api to set `- --advertise-address=$(MY_POD_IP)` which can be left off.

Desired Changes:

I'll share the tweaks I made which allowed bootkube to bootstrap a DNS-only cluster. The current behavior is that nodes are registered with their DNS name via on-host and then via their IP via the pod kubelet and `bootkube start` always times out.

**Comment by dghubble** [comment]
See #90

**Comment by aaronlevy** [comment]
Should be closed by: https://github.com/kubernetes-incubator/bootkube/pull/151

The advertise address change was reverted in: https://github.com/kubernetes-incubator/bootkube/pull/257 -- but lets open a separate issue for that if this was a concern.
