### ISSUE TITLE
simplified bootkube status output

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#91]
Bootkube currently displays a lot of log output from apiserver+scheduler+controller-manager. This can be confusing and makes it difficult to determine if things are "going well".

We should provide some simplified output of bootkube state (although I think we still need to preserve the log output, as that is the primary means for debugging issues.).

The simplified output might be something like:

control-plane started
manifests created
pods pending
done

One option is to split log vs state output on stdout and stderr.

/cc @sym3tri

**Comment by kenan435** [comment]
@aaronlevy not sure I understood the option you suggested. Would a log file approach on each start of provisioning be a good idea? Dump the verbose output into the log file while showing the sequence of steps of provisioning on the console.

**Comment by kenan435** [comment]
@aaronlevy not sure I understood the option you suggested. Would a log file approach on each start of provisioning be a good idea? Dump the verbose output into the log file while showing the sequence of steps of provisioning on the console.

**Comment by aaronlevy** [comment]
@kenan435 myy initial thought was do so something like putting log output on stdout & the "status" messages on stderr, which would allow a deployer to self-select what they see.

`bootkube foo` = see all messages (log + status)
`bootkube foo > log.txt` = redirect verbose log to file
`bootkube foo 2> status.txt` = redirect status messages to file
`bootkube foo &> all.txt` = redirect all output to file

Also was thinking that we could possibly send events to the kubernetes api, that way you could also see status as `kubectl get events --namespace=kube-system`

/cc @pbx0 as he's been taking a look at this

**Comment by pbx0** [comment]
I'm basically implementing it with the same stdout/stderr split for now.  I have them reversed at the moment, stdout is for status and stderr is for logs. I like it better in reverse now that you point it out.

**Comment by aaronlevy** [comment]
fixed in https://github.com/kubernetes-incubator/bootkube/pull/123
