### ISSUE TITLE
calico: update to version to v3.0.0

### ISSUE THREAD

**Issue by ericchiang** [kubernetes-incubator/bootkube#921]
https://github.com/kubernetes-incubator/bootkube/blob/2de93149749b07baa314cba9e3f5d8282d811725/pkg/asset/internal/templates.go#L1461-L1514

* Cluster roles aren't namespaced, so that role shouldn't include a namespace field.
* Merge common resources (e.g. instead of two rules for namespaces and pods, just have single rule with the list ["namespaces", "pods"]

cc @rithujohn191

**Comment by dghubble** [comment]
Pods are supposed to also have "patch" so no need to merge those two. https://github.com/projectcalico/calico/commit/5c04a90c507c6ce23811624ee5f56ba88a568aed

**Comment by ericchiang** [comment]
Ah looks like we're just behind on the times. https://github.com/projectcalico/calico/commit/35fff4814a38751134be09652aa34cb91d99bd26#diff-242dec77d33255ee47800ceb35e7af19 :)

**Comment by rithujohn191** [comment]
Shall I change this issue to updating the calico version to v3.0.0?

**Comment by ericchiang** [comment]
Works for me!

**Comment by ericchiang** [comment]
https://github.com/kubernetes-incubator/bootkube/pull/927 is in. Thanks!
