### ISSUE TITLE
pkg/bootkube: create Namespaces before other resources

### ISSUE THREAD

**Issue by ericchiang** [kubernetes-incubator/bootkube#926]
Namespaces, like CRDs, have explicit ordering. You have to create the namespace object before creating resources in that namespace.

See the fun naming here: https://github.com/coreos/tectonic-installer/tree/a996e37a97d307b5b07c3166937ae0f8a1fbcac6/modules/bootkube/resources/manifests

We should just automatically detect this case.

/assign @rphillips 

Ryan if you're busy, feel free to assign to someone else.

**Comment by aaronlevy** [comment]
If we go down this route, please add documentation that outlines the ordering in which manifests are applied (with https://github.com/kubernetes-incubator/bootkube/pull/919 and this PR it would be that CRDs and Namespaces are special, all other files are lexicographic order).
