### ISSUE TITLE
Use latest kube-dns

### ISSUE THREAD

**Issue by chancez** [kubernetes-incubator/bootkube#93]
kube-dns got a rewrite in 1.3, and is required for features like federation to work properly. It's also lighter weight/simpler. Bootkube is deploying the old kube-dns, it should get upgraded (also while at it the file should be renamed to a -deployment suffix since its no longer an RC).

**Comment by aaronlevy** [comment]
closed in https://github.com/kubernetes-incubator/bootkube/pull/126
