### ISSUE TITLE
Checkpointer fails to get pod status using v1.10-rc1

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#934]
Getting repeated errors:

```
E0321 23:44:16.429921       1 runtime_service.go:47] failed to list running sandboxes: rpc error: code = 12 desc = unknown service runtime.RuntimeService
E0321 23:44:21.447718       1 runtime_service.go:125] ListPodSandbox with filter "&PodSandboxFilter{Id:,State:&PodSandboxStateValue{State:SANDBOX_READY,},LabelSelector:map[string]string{},}" from runtime sevice
 failed: rpc error: code = 12 desc = unknown service runtime.RuntimeService
E0321 23:44:21.447821       1 runtime_service.go:47] failed to list running sandboxes: rpc error: code = 12 desc = unknown service runtime.RuntimeService
E0321 23:44:26.461873       1 runtime_service.go:125] ListPodSandbox with filter "&PodSandboxFilter{Id:,State:&PodSandboxStateValue{State:SANDBOX_READY,},LabelSelector:map[string]string{},}" from runtime sevice
 failed: rpc error: code = 12 desc = unknown service runtime.RuntimeService
```

The checkpointer then never pivots from the checkpointed copy of the apiserver, to the "real" apiserver pod.

Tested using v1.9.3 and it did not have this same behavior

**Comment by ericchiang** [comment]
This error is coming from our use of CRI

https://github.com/kubernetes-incubator/bootkube/blob/8a9a588f6c19223f00c6c91d88c307e1387eb288/pkg/checkpoint/runtime_service.go#L107-L115

**Comment by ericchiang** [comment]
The CRI service switched from v1alpha1 to v1alpha2 between 1.9 and 1.10

https://github.com/kubernetes/kubernetes/tree/v1.9.6/pkg/kubelet/apis/cri
https://github.com/kubernetes/kubernetes/tree/v1.10.0-rc.1/pkg/kubelet/apis/cri

**Comment by ericchiang** [comment]
CRI made a breaking change over 1.10 https://github.com/kubernetes/kubernetes/pull/58973

https://github.com/kubernetes-incubator/cri-tools/issues/236

From what I can see this is expected. I don't see a way for us to support both 1.9 and 1.10 CRI.
