### ISSUE TITLE
Surface asset creation errors to e2e tests

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#937]
So we don't end up with issues like https://github.com/kubernetes-incubator/bootkube/issues/932 - our e2e tests should expose any asset creation errors as test failures.

We don't fail on these errors in the normal case as it's usually easier to debug the resulting cluster if we don't fail early (https://github.com/kubernetes-incubator/bootkube/pull/933#issuecomment-375161442).

Not sure best course here - maybe something like a "strict" mode on start that fails on any error? The bash -set euo equivalent?

**Comment by colemickens** [comment]
Unfortunately, right now the e2e won't fail until a bunch or all of the terraform completes since `render` runs remotely. It would be good if we could also run the render locally and fail faster.

**Comment by aaronlevy** [comment]
This would be for the `start` phase technically (which is remote regardless)

**Comment by rphillips** [comment]
@aaronlevy https://github.com/kubernetes-incubator/bootkube/pull/939/files
