### ISSUE TITLE
Update sonobuoy and run conformance

### ISSUE THREAD

**Issue by dghubble** [kubernetes-incubator/bootkube#941]
bootkube should still pass the original sonobuoy conformance tests, but sonobuoy has changed a good bit over the last few months. I ran sonobuoy v0.11.0 and there were a few failures. I'll note, its unclear how to control exactly which version of the Kubernetes e2e tests get run and whether these failures represent anything real (given e2e spews v1.9.4-beta).

```
Kubernetes version: v1.9.6
Platform: AWS
```

```
Summarizing 2 Failures:

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [BeforeEach] validates that NodeSelector is respected if not matching  [Conformance] 
/workspace/anago-v1.9.4-beta.0.53+bee2d1505c4fe8/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:88

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [BeforeEach] validates that NodeSelector is respected if matching  [Conformance] 
/workspace/anago-v1.9.4-beta.0.53+bee2d1505c4fe8/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:88

Ran 125 of 782 Specs in 2775.605 seconds
FAIL! -- 123 Passed | 2 Failed | 0 Pending | 657 Skipped --- FAIL: TestE2E (2775.82s)
```

I hastily wrote (an admittedly terrible) nightly conformance test for bootkube and left it running on Jenkins (look for cncf-conformance?). Probably two action items:

- [ ] Update nightly job to use a recent-ish sonobuoy setup (they have a CLI tool now)
- [ ] Investigate failures (node selectors seem fine in practice)

**Comment by dghubble** [comment]
Btw, that sonbuoy job is not a replacement for the official bootkube-conformance e2e job that should get run on every Kubernetes bump.

**Comment by aaronlevy** [comment]
Just as an update, I opened an internal JIRA ticket for someone to take a look at the conformance tests (both upstream + sonouoy). 

cc @rphillips
