### ISSUE TITLE
Bootkube recover does not wait long enough for recovery in certain scenarios

### ISSUE THREAD

**Issue by robertglen** [kubernetes-incubator/bootkube#974]
In the event you lose all nodes running the control plane in its entirety, and have nothing but a functioning etcd cluster, bootkube is unable to recover successfully on its own once you introduce a new master node to run the recovery on.

My observations during a trial DR scenario using bootkube v0.12.0 is that the 'bootkube start' finishes with a successful control plane bootup, then tears down the temp control plane leaving nothing running in docker.

I believe the reason is because the old master nodes are still in etcd, and master control plane pods are still considered running because the bootkube's controller-manager quit before it could discover the non-existing nodes are actually gone.  If it stayed online long enough to see the old master nodes transition to a NotReady state, it would have evicted the pods owned by that node, and then new apiserver, controller-manager, and scheduler pods would be started within docker on the bootkube node.

Here is a slack chat that captures the theory from the bootkube channel.

rglen [10:45 AM]
just tried with 0.12.0  it at least launched the apiserver, controller-manager, and scheduler pods during the recovery attempt, (0.9.1 only ever launched apiserver)

but once it finished, it still wound up with no docker containers running
so same end result

rglen [11:06 AM]
I think it’s because the node objects of the destroyed EC2 instances were still registered but NotReady
well, I mean I wonder if that’s part of why it didn’t bother scheduling new controller managers, and schedulers, cause once I started up bare apiserver, controller-manager, and scheduler on the outter host node the old fashioned way..I could then run kubectl commands and it revealed that it still thought a controller manager and scheduler were running on the destroyed nodes
and those destroyed nodes were obviously still part of the k8s cluster, I had to do a kubectl delete node which eventually lead to the pods that were running on them disapparing
its almost like there needs to be a way to remove the node objects directly from etcd and delete the pods that were associated with them so that when the static pods are spawned by bootkube start, it knows it needs to schedule those pods to the host running bootkube

aaronlevy [10:41 AM]
@rglen Yeah, it sounds like the stale state (of “everything is good”) was still in the backup - so bootkube didn’t wait long enough before tearing down the bootstrap controller-manager/scheduler (so that real ones were in fact running). And then there’s nothing to actually update that state (controller-manager is what would have marked the nodes as down and then evicted the pods so they run somewhere else).
Not immediately sure best option here. Need to figure out some reasonable way for bootkube to not just see “these pods are running - I’m done”, because on restore that might actually be stale.

**Comment by klausenbusk** [comment]
Duplicate https://github.com/kubernetes-incubator/bootkube/issues/715 ?

**Comment by robertglen** [comment]
Ok, definitely sounds like the same.

**Comment by rphillips** [comment]
Closing in favor of #715
