### ISSUE TITLE
bootkube recover fails with TemplateGeneration on 1.10.x

### ISSUE THREAD

**Issue by schmitch** [kubernetes-incubator/bootkube#977]
Hello, currently I try running bootkube on a single node cluster (I modified the vagrant a little bit to suite my own needs, just removed vagrant and change the api-servers ip to my network).

I then did just the `bootkube render ...` and `bootkube start ...` everything started working. After that I tought, now let's check the recovery process and rebooted the node.

So I tried to recover via: `./bin/linux/bootkube recover --recovery-dir=recovered --etcd-ca-path=/etc/etcd/tls/etcd-client-ca.crt --etcd-certificate-path=/etc
/etcd/tls/etcd-client.crt --etcd-private-key-path=/etc/etcd/tls/etcd-client.key --etcd-servers=https://127.0.0.1:2379 --kubeconfig=/etc/kubernetes/kubeconfig`

Which failed with: 
```
Attempting recovery using etcd cluster at "https://127.0.0.1:2379"...
Error: converting (v1.DaemonSet).MinReadySeconds to (v1beta1.DaemonSet).MinReadySeconds: TemplateGeneration not present in src
```

The question would now be, how I'm able to recover?

**Edit:** 

<strike>I guess as long as the control plane keeps to be the same version than my cluster is I could just use `bootkube start --asset-dir my_created_assets_dir` ?</strike>

**Comment by bcg62** [comment]
also seeing this with v0.12.0

**Comment by CAR6807** [comment]
Any follow up?

**Comment by tomgco** [comment]
We are also seeing this here - which makes it impossible to recover a cluster when API resources are using v1 daemonsets.

I am happy to take a look at that, however I need some assistance in understanding where this conversion happens within the code-base...

**Comment by AndrewNeudegg** [comment]
Is it possible to reopen this issue, I am experiencing the same issue:

```
Error: converting (v1.DaemonSet).MinReadySeconds to (v1beta1.DaemonSet).MinReadySeconds: TemplateGeneration not present in src
```

On Bootkube versions `v0.14.0`, `v0.13.0` and `v0.12.0`.

**Comment by tomgco** [comment]
@AndrewNeudegg https://github.com/kubernetes-incubator/bootkube/pull/1040 has now been merged in, so it should fix the issue you are seeing, however, a new Bootkube release hasn't been cut yet with that patch.

**Comment by rporres** [comment]
I was able to recover a cluster using a `bootkube` command built from `master`

@tomgco thx for that fix! ❤️
