### ISSUE TITLE
Pod Checkpointer Prevents Updates to API Server

### ISSUE THREAD

**Issue by frankgreco** [kubernetes-incubator/bootkube#986]
It appears as though the behavior of the `pod-checkpointer` is as follows:
1. watch for a ds/kube-apiserver pod to become unhealthy
2. create an apiserver via static pod

If I issue a `kubectl patch` such that the API server needs to restart, the above will occur. However, when the ds version of the server attempts to come back up, I am greeted with:

```
failed to create listener: failed to listen on 0.0.0.0:6443: listen tcp 0.0.0.0:6443: bind: address already in use
```

This occurs because the static pod is bound to that port.

*UPDATE:* Is seems as though the apiserver/checkpointer eventually figure it out and recover but after an unknown amount of time.

**Comment by ericchiang** [comment]
> UPDATE: Is seems as though the apiserver/checkpointer eventually figure it out and recover but after an unknown amount of time.

I believe this is intended behavior. Since we removed our use of flock on the API server, they just battle for the port until the correct one comes up.
